Repository Axway/axway-open-docs, pull requests merged in 2019-08, with the labels that each got.

#41 IAP-2355: high-level fixes so the topics are pretty-formatted on website
  content/en/docs/apiportal_admin/_index.md
  content/en/docs/apiportal_admin/customize_APICatalog_overview.md
  content/en/docs/apiportal_admin/customize_css_styles.md
  content/en/docs/apiportal_admin/customize_getting_started.md
  content/en/docs/apiportal_admin/customize_page_content.md
  content/en/docs/apiportal_admin/localize_language.md
  content/en/docs/apiportal_admin/public_api_configure.md
  content/en/docs/apiportal_admin/role_mapping.md
  content/en/docs/apiportal_admin/sso/_index.md
  content/en/docs/apiportal_admin/sso/sso_config.md
  content/en/docs/apiportal_admin/sso/sso_mapping.md
  content/en/docs/apiportal_admin/sso_mapping.md
  content/en/docs/apiportal_admin/troubleshooting.md
  content/en/docs/contribution_guidelines/_index.md
Labels: documentation

#62 IAP-2356: change frontmatter format from JSON to YAML.
  content/en/docs/apiportal_releasenotes/_index.md
  content/en/docs/apiportal_releasenotes/fixed_issues.md
Labels: ReadMeFirst_Sprint57

#63 IAP-2496: docs for show/hide nickname column;
  content/en/docs/apiportal_admin/customize_APICatalog_overview.md
  static/Images/APIPortal/jai_customize_api_catalog.png
Labels: ReadMeFirst_Sprint57

#66 IAP-2356: update frontmatter format APIP Admin and APIC files
  content/en/docs/apiportal_admin/_index.md
  content/en/docs/apiportal_admin/customize_APICatalog_overview.md
  content/en/docs/apiportal_admin/customize_css_styles.md
  content/en/docs/apiportal_admin/customize_getting_started.md
  content/en/docs/apiportal_admin/customize_page_content.md
  content/en/docs/apiportal_admin/localize_language.md
  content/en/docs/apiportal_admin/public_api_configure.md
  content/en/docs/apiportal_admin/role_mapping.md
  content/en/docs/apiportal_admin/sso/_index.md
  content/en/docs/apiportal_admin/sso/sso_config.md
  content/en/docs/apiportal_admin/sso/sso_mapping.md
  content/en/docs/apiportal_admin/troubleshooting.md
  content/en/docs/central/_index.md
  content/en/docs/central/add_hybrid_env.md
  content/en/docs/central/build_hybrid_env.md
  content/en/docs/central/cli_proxy_flow.md
  content/en/docs/central/fundamental_concepts.md
  content/en/docs/central/hybrid_overview.md
  content/en/docs/central/overview.md
  content/en/docs/central/quickstart.md
  content/en/docs/central/secure_api_jwt.md
Labels: ReadMeFirst_Sprint57

#93 Update issue templates
  .github/ISSUE_TEMPLATE/documentation-issue-template.md
  .github/ISSUE_TEMPLATE/website-issue-template.md
Labels: ReadmeFirst_Sprint58

#96 Added gruntfile for npm build
  Gruntfile.js
  package.json
Labels: ReadmeFirst_Sprint58
