Repository Axway/axway-open-docs, pull requests merged in 2019-11, with the labels that each got.

#162 update contrib topics for maintainers
  content/en/docs/contribution_guidelines/_index.md
  content/en/docs/contribution_guidelines/deleting_a_repository.md
  content/en/docs/contribution_guidelines/maintain_customize.md
  content/en/docs/contribution_guidelines/setup_work_locally.md
Labels: Size: 2

#158 APIGOV-11275 - additional rate limit cli examples
  content/en/docs/central/cli_proxy_flow.md
  content/en/docs/central/proxy_rate_limit.md
Labels: Size: 2

#176 Update API Portal installation “install_unattended”
  content/en/docs/apiportal_install/install_unattended.md
Labels: Size: 2

#174 Update API Portal administration “apip_overview”
  content/en/docs/apiportal_admin/apip_overview.md
Labels: Size: 1

#171 update Creating and managing applications
  content/en/docs/apiportal_admin/apip_overview.md
Labels: Size: 1

#177 Manage Environments With CLI
  content/en/docs/central/cli_environments.md
  content/en/docs/central/cli_getstarted.md
  content/en/docs/central/cli_proxy_flow.md
Labels: Size: 3

#179 APIGOV-12428 AMPLIFY Central CFT Profile Documentation
  content/en/docs/central/cft_profile.md
  content/en/docs/central/cli_environments.md
  content/en/docs/central/cli_getstarted.md
  content/en/docs/central/cli_proxy_flow.md
  static/Images/central/app_identity_profiles.png
  static/Images/central/cft_profile.png
  static/Images/central/cft_profile_Save.gif
Labels: Size: 1

#185 Update AMPLIFY Central documentation “cli_proxy_flow”
  content/en/docs/central/cli_proxy_flow.md
Labels: Size: 1

#184 Update Apache Cassandra administration “cassandra_bur”
  content/en/docs/cass_admin/cassandra_bur.md
Labels: Size: 1
