Repository Axway/axway-open-docs, pull requests merged in 2019-10, with the labels that each got.

#126 update_TA_reference
  content/en/docs/central/hybrid_overview.md
Labels: Size: 1

#118 [WIP] APIGOV-10379 - rate limit docs
  content/en/docs/central/cli_proxy_flow.md
  content/en/docs/central/overview.md
  content/en/docs/central/proxy_rate_limit.md
  static/Images/central/proxy_no_rate_limit_box.png
  static/Images/central/proxy_rate_limit_box.png
Labels: Size: 3

#130 Update contribution guidelines
  content/en/docs/contribution_guidelines/_index.md
Labels: Size: 1

#131 bridging_update
  content/en/docs/central/proxy_rate_limit.md
Labels: Size: 1

#138 Update customize_APICatalog_overview.md
  content/en/docs/apiportal_admin/customize_APICatalog_overview.md
  static/Images/uploads/apiportal-jai-customize-api-catalog.png
Labels: Size: 1

#144 Update API Portal installation “secure_harden_portal”
  content/en/docs/apiportal_install/secure_harden_portal.md
Labels: Size: 1

#134 Update fundamental_concepts.md
  content/en/docs/central/fundamental_concepts.md
Labels: Size: 1

#143 Update CMS version and edit button
  content/en/docs/contribution_guidelines/_index.md
  i18n/en.toml
  layouts/partials/page-meta-links.html
  static/admin/config.yml
  static/admin/index.html
Labels: Size: 2

#151 Updates regard to deleting a fork
  content/en/docs/contribution_guidelines/_index.md
  content/en/docs/contribution_guidelines/deleting_a_repository.md
Labels: Size: 1

#156 new blog post and update guidelines for cms deploy preview
  content/en/blog/news/site_updates.md
  content/en/docs/contribution_guidelines/_index.md
  static/Images/contributing/cms_deploy_preview.png
Labels: Size: 1

#154 Update API Portal installation “secure_harden_portal”
  content/en/docs/apiportal_install/secure_harden_portal.md
Labels: Size: 1

#147 Apigov 11523 tls
  content/en/docs/central/backend_TLS.md
  static/Images/central/TLS_example.png
Labels: Size: 2

#153 Update API Portal installation “secure_harden_portal”
  content/en/docs/apiportal_install/secure_harden_portal.md
Labels: Size: 1
