Repository Axway/axway-open-docs, pull requests merged in 2020-10, with the labels that each got.

#1195 RDAPI-21764 Update 'API Gateway user roles' section with api.manager.orgadmin.selfservice.enabled system property
  content/en/docs/api_mgmt_overview/key_concepts/api_mgmt_orgs_roles.md
Labels: needs push to prod, size/XS

#1206 RDAPI-21825 Detail message attributes to aid with setting the orgs2Role header.
  content/en/docs/apim_administration/apimgr_sso/saml_sso_config.md
  static/Images/docbook/images/api_mgmt/sso_addheader.png
  static/Images/docbook/images/api_mgmt/sso_processing.png
Labels: needs push to prod, size/XS

#1226 APIM Sep20 Release note - add RDAPI-20021 to list of fixed issues
  content/en/docs/apim_relnotes/20200730_apimgr_relnotes.md
Labels: needs push to prod, size/XS

#1227 APIM Sep 20 Release note - Update 'YAML-based configuration store' and 'Deprecated features' sections
  content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
Labels: needs push to prod, size/XS

#1232 Update page in Connect API Manager “filtering-apis-to-be-discovered”
  content/en/docs/central/connect-api-manager/filtering-apis-to-be-discovered.md
Labels: netlify-cms/pending_review, size/XS

#1200 Update page in AMPLIFY Central CLI “cli_install”
  content/en/docs/central/cli_central/cli_install.md
  static/Images/central/cli_central/env_variables.png
Labels: needs push to prod, size/XS

#1231 APIM Release note - Add RDAPI-20923 to the list of fixed issues
  content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
Labels: needs push to prod, size/XS

#1235 Update page in Connect AWS Gateway “filtering-apis-to-be-discovered-1”
  content/en/docs/central/connect-aws-gateway/filtering-apis-to-be-discovered-1.md
Labels: netlify-cms/pending_publish, size/M

#1220 Remove Configure watchdogs section from API Manager settings
  content/en/docs/apim_reference/api_mgmt_config_web.md
Labels: needs push to prod, size/XS

#1238 APIGOV-16372 Verify links
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
Labels: size/S

#1239 APIGOV-16372 Verify links
  content/en/docs/central/connect-api-manager/Agent-security-api-manager.md
Labels: netlify-cms/pending_publish, size/XS

#1240 APIGOV-16372 Update page in Connect API Manager “agent-variables”
  content/en/docs/central/connect-api-manager/agent-variables.md
Labels: netlify-cms/pending_publish, size/S

#1241 APIGOV-16372 Update page in Connect API Manager “deploy-your-agents-quickstart”
  content/en/docs/central/connect-api-manager/deploy-your-agents-quickstart.md
Labels: netlify-cms/pending_publish, size/XS

#1242 APIGOV-16372 Update page in Connect API Manager “prepare-amplify-central”
  content/en/docs/central/connect-api-manager/prepare-amplify-central.md
Labels: netlify-cms/pending_publish, size/XS

#1244 APIGOV-16372 Update page in Connect API Manager “_index”
  content/en/docs/central/connect-api-manager/_index.md
Labels: netlify-cms/pending_publish, size/XS

#1245 APIGOV-16372 Update page in Connect API Manager “network-traffic-apimanager”
  content/en/docs/central/connect-api-manager/network-traffic-apimanager.md
Labels: netlify-cms/pending_publish, size/XS

#1251 APIGOV-16372 Update page in Connect AWS Gateway “_index”
  content/en/docs/central/connect-aws-gateway/_index.md
Labels: netlify-cms/pending_publish, size/XS

#1250 APIGOV-16372 Update page in Connect AWS Gateway “prepare-amplify-central-1”
  content/en/docs/central/connect-aws-gateway/prepare-amplify-central-1.md
Labels: netlify-cms/pending_publish, size/XS

#1249 APIGOV-16372 Update page in Connect AWS Gateway “prepare-aws-api-gateway”
  content/en/docs/central/connect-aws-gateway/prepare-aws-api-gateway.md
Labels: netlify-cms/pending_publish, size/XS

#1248 APIGOV-16372 Update page in Connect AWS Gateway “deploy-your-agents-quickstart”
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-quickstart.md
Labels: netlify-cms/pending_publish, size/XS

#1247 APIGOV-16372 Update page in Connect AWS Gateway “deploy-your-agents-1”
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-1.md
Labels: netlify-cms/pending_publish, size/S

#1246 APIGOV-16372 Update page in Connect AWS Gateway “agent-security-aws”
  content/en/docs/central/connect-aws-gateway/agent-security-aws.md
Labels: netlify-cms/pending_publish, size/XS

#1212 Update SSO Config - Configure SAML endpoint URLs section.
  content/en/docs/apim_administration/apiportal_sso/sso_config.md
Labels: needs push to prod, size/XS

#1216 Secure API Portal - update Encrypt database password section
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
Labels: needs push to prod, size/XS

#1222 Update yamles_known_limitations.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
Labels: needs push to prod, size/XS

#1228 Update page in APIP install section “connect_to_apimgr”
  .vscode/settings.json
  content/en/docs/apim_installation/apiportal_install/connect_to_apimgr.md
Labels: needs push to prod, size/XS

#1263 Update page in Connect AWS Gateway “cloud-administration-operation”
  content/en/docs/central/connect-aws-gateway/cloud-administration-operation.md
Labels: netlify-cms/pending_publish, size/M

#1230 IAP-3570 Move public api user docs to the correct page
  content/en/docs/apim_administration/apiportal_admin/public_api_configure.md
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
Labels: needs push to prod, size/XS

#1229 Update yamles_known_limitations.md - list a few more known bugs
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
Labels: needs push to prod, size/XS

#1236 Update page in instances and listeners section “general_remote_hosts”
  content/en/docs/apim_policydev/apigw_gw_instances/general_remote_hosts.md
Labels: needs push to prod, size/XS

#1234 Update page in APIM release note section “20200930_apimgr_relnotes”
  content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
Labels: needs push to prod, size/XS

#1237 Update page in APIG admin section “general_certificates”
  content/en/docs/apim_administration/apigtw_admin/general_certificates.md
Labels: needs push to prod, size/XS

#1243 Update page in Mesh management “add_env”
  content/en/docs/central/mesh_management/add_env.md
Labels: needs push to prod, size/XS

#1282 Synchronize AWS and Azure ref arch common content
  content/en/docs/apim-reference-architectures/container-aws/_index.md
  content/en/docs/apim-reference-architectures/container-azure/_index.md
Labels: needs push to prod, size/M

#1233 [RDAPI-21807] Documentation changes for clarification on OneVersion update
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_system_props.md
  content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
Labels: needs push to prod, size/M

#1267 RDAPI-21746 Update page in APIG admin section “general_certificates”
  content/en/docs/apim_administration/apigtw_admin/general_certificates.md
Labels: needs push to prod, size/XS

#1270 Add note that YAML configuration is not supported for production use
  content/en/docs/apim_yamles/_index.md
Labels: needs push to prod, size/XS

#1272 Update YAML Config Known limitations on develop branch for Nov20 release
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
Labels: size/XS

#1276 APIGOV-16543 Update instructions for installing and authorizing the AMPLIFY Central CLI
  content/en/docs/central/cli_central/cli_install.md
Labels: needs push to prod, size/XS

#1277 RDAPI-21027 Cassandra re-index script changes
  content/en/docs/cass_admin/cassandra_bur.md
Labels: needs push to prod, size/XS

#1295 Update page in Connect AWS Gateway “agent-security-aws”
  content/en/docs/central/connect-aws-gateway/agent-security-aws.md
Labels: netlify-cms/pending_publish, size/S

#1271 Update page in APIG install section “system_requirements”
  content/en/docs/apim_installation/apigtw_install/system_requirements.md
Labels: needs push to prod, size/XS

#1298 Update page in Connect API Manager “subscription-for-the-consumer”
  content/en/docs/central/connect-api-manager/subscription-for-the-consumer.md
Labels: netlify-cms/draft, size/M

#1254 RDAPI-20564 APIM YamlES update
  content/en/docs/apim_yamles/yamles_externalized_files.md
  content/en/docs/apim_yamles/yamles_structure.md
Labels: size/S

#1287 [RDAPI-20919] Update Idle Timeout description in general_settings.md
  content/en/docs/apim_reference/general_settings.md
Labels: needs push to prod, size/XS

#1317 APIGOV-16527 Update page in Connect API Manager “discovery-agent-flags”
  content/en/docs/central/connect-api-manager/discovery-agent-flags.md
Labels: netlify-cms/pending_review

#1318 APIGOV-16527 Update page in Connect API Manager “agent-variables”
  content/en/docs/central/connect-api-manager/agent-variables.md
Labels: netlify-cms/pending_review

#1316 APIGOV-16527 Update page in Connect API Manager “_index”
  content/en/docs/central/connect-api-manager/_index.md
Labels: netlify-cms/pending_review

#1319 APIGOV-16209 - Update page in Connect API Manager “deploy-your-agents-quickstart”
  content/en/docs/central/connect-api-manager/deploy-your-agents-quickstart.md
Labels: netlify-cms/draft, size/S

#1279 Update Customize API Catalog settings
  content/en/docs/apim_administration/apiportal_admin/customize_APICatalog_overview.md
  static/Images/APIPortal/api-catalog.png
Labels: size/XS

#1323 Add code owners to some guides so the owners will be automatically assigned as Reviewers
  .github/CODEOWNERS
Labels: size/S, size/XS

#1296 IAP-3644 update API Portal installation dependency section in order to support RHEL 8
  content/en/docs/apim_installation/apiportal_install/install_dependencies.md
Labels: needs push to prod, size/XS

#1297 IAP-3644 update API Portal redis section in order to support RHEL 8
  content/en/docs/apim_installation/apiportal_install/install_software_redis.md
Labels: needs push to prod, size/XS

#1306 Correct wording of "HTTP 1.1" sections for accuracy
  content/en/docs/apim_administration/apigtw_admin/admin_performance.md
Labels: needs push to prod, size/XS

#1290 Update API Gateway July 20 release to add RDAPI-19028 to the list of issues
  content/en/docs/apim_relnotes/20200730_apimgr_relnotes.md
Labels: more info needed, needs push to prod, size/XS

#1307 Yaml ES RDAPI-20990 RDAPI-20564 support of windows and special chars
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
  content/en/docs/apim_yamles/yamles_cli.md
  content/en/docs/apim_yamles/yamles_structure.md
Labels: size/XS

#1315 Update page in APIP admin section “manage_privacy_personal_data”
  content/en/docs/apim_administration/apiportal_admin/manage_privacy_personal_data.md
Labels: needs push to prod, size/XS

#1322 Update page in YAML configuration section “yamles_environmentalization”
  content/en/docs/apim_yamles/yamles_environmentalization.md
Labels: netlify-cms/pending_review, size/S

#1339 Revert "Add code owners to some guides so the owners will be automatically assigned as Reviewers"
  .github/CODEOWNERS
Labels: size/S

#1343 RDAPI-21984 Update 20200930_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
Labels: needs push to prod, size/XS

#1303 Update the configuation of SSL connection between API Portal and DB (“install_software_configure_database”)
  content/en/docs/apim_installation/apiportal_install/install_software_configure_database.md
Labels: needs push to prod

#1324 [RDAPI-21055] Improve upgrade documentation for multi node setups
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
  static/Images/UpgradeGuide/APIgw_upgrade_multinode_topology.png
Labels: size/S

#1345 Fix link to Streams documentation in _index.html
  content/en/_index.html
Labels: needs push to prod, size/XS

#1356 RDAPI-21101 New page for release change log
  content/en/docs/apim_reference/allReleasesChangeLog.md
Labels: size/M

#1360 Create Pages and collection for AMPLIFY Central Release notes Oct 2020
  content/en/docs/central/amplify_relnotes/_index.md
  static/admin/config.js
Labels: needs push to prod, size/S

#1352 APIGOV-15487 - extra file to remove
  content/en/docs/central/connect-api-manager/Deploy your agents with AMPLIFY CLI
Labels: size/S

#1361 Create page in AMPLIFY Release notes section “20201030_ampc_relnotes”
  content/en/docs/central/amplify_relnotes/20201030_ampc_relnotes.md
Labels: size/M
