Repository Axway/axway-open-docs, pull requests merged in 2020-05, with the labels that each got.

#684 Apim alert jira integration
  content/en/docs/api_mgmt_overview/key_concepts/policies.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_alerts.md
Labels: needs push to prod, size/XS

#692 Add new checks for sensitive info, fix lint errors
  .github/ISSUE_TEMPLATE/documentation-issue-template.md
  .github/ISSUE_TEMPLATE/website-issue-template.md
  .github/pull_request_template.md
Labels: size/XS

#689 Update codeowners
  .github/CODEOWNERS
Labels: size/S

#672 Create page in AMPLIFY Unified Catalog “authenticate-an-api-secured-with-oauth-published-from-an-external-gateway”
  content/en/docs/central/catalog/authenticate-an-external-gateway-api.md
  static/Images/central/catalog/catalog-details.png
  static/Images/central/catalog/postman-edit-auth.png
  static/Images/central/catalog/postman-edit-dots.png
  static/Images/central/catalog/postman-generate-collection.png
  static/Images/central/catalog/postman-get-token-button.png
  static/Images/central/catalog/postman-import.png
  static/Images/central/catalog/postman-select-file.png
  static/Images/central/catalog/postman-select-method.png
  static/Images/central/catalog/postman-token-details.png
  static/Images/central/catalog/postman-try-method.png
  static/Images/central/catalog/postman-update-collection-auth.png
  static/Images/central/catalog/postman-use-token.png
  static/Images/central/catalog/support-spec.png
Labels: size/S

#696 #671 Videos now sourced from Axway API-YT channel
  content/en/docs/api_mgmt_overview/api_mgmt_components/apibuilder.md
  content/en/docs/api_mgmt_overview/api_mgmt_components/pipeline.md
  content/en/docs/api_mgmt_overview/api_mgmt_components/stoplight.md
  content/en/docs/api_mgmt_overview/api_mgmt_components/tools.md
Labels: needs push to prod, size/XS

#678 APIGOV-14679 Restructure Central and Catalog navigation
  content/en/docs/catalog/_index.md
  content/en/docs/catalog/discover-and-consume-catalog-assets-3.md
  content/en/docs/catalog/manage_subscriptions.md
  content/en/docs/central/mesh_management/_index.md
  content/en/docs/central/mesh_management/add_env.md
  content/en/docs/central/mesh_management/build_hybrid_env.md
  static/admin/config.js
Labels: size/S

#703 Replace video with official version from Axway YT
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_alerts.md
Labels: needs push to prod, size/XS

#701 Fix Catalog pages structure
  content/en/_index.html
  content/en/docs/_index.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_admin.md
  content/en/docs/apim_administration/apimgr_sso/saml_sso_config.md
  content/en/docs/catalog/_index.md
  content/en/docs/catalog/authenticate-an-external-gateway-api.md
  content/en/docs/catalog/discover-and-consume-catalog-assets-3.md
  content/en/docs/catalog/discover-and-consume-catalog-assets.md
  content/en/docs/catalog/testing-an-api-from-the-browser.md
  content/en/docs/central/_index.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-1.md
  content/en/docs/central/mesh_management/add_env.md
  content/en/docs/central/mesh_management/build_hybrid_env.md
  content/en/docs/shared_services/_index.md
  content/en/docs/streams/_index.md
  content/en/docs/streams/subscribers/subscriber-webhook.md
Labels: size/M

#704 Fix link in AMPLIFY Unified Catalog “testing-an-api-from-the-browser”
  content/en/docs/catalog/testing-an-api-from-the-browser.md
Labels: size/XS

#706 Update page in AMPLIFY Central section “cli_getstarted”
  content/en/docs/central/cli_getstarted.md
Labels: needs push to prod, netlify-cms/pending_review, size/S

#708 Fix formatting of general_file_transfer
  content/en/docs/apim_policydev/apigw_gw_instances/general_file_transfer.md
Labels: size/XS

#709 Fix formatting of general_ftp_scanner
  content/en/docs/apim_policydev/apigw_gw_instances/general_ftp_scanner.md
Labels: size/XS

#710 Fix formatting of general_directory_scanner
  content/en/docs/apim_policydev/apigw_gw_instances/general_directory_scanner.md
Labels: size/XS

#711 Fix formatting of general_pop_client
  content/en/docs/apim_policydev/apigw_gw_instances/general_pop_client.md
Labels: size/XS

#712 Fix formatting of general_aws_poller
  content/en/docs/apim_policydev/apigw_gw_instances/general_aws_poller.md
Labels: size/XS

#713 Fix formatting of general_crypto_accel
  content/en/docs/apim_policydev/apigw_gw_instances/general_crypto_accel.md
Labels: size/XS

#714 Fix formatting of general_cors
  content/en/docs/apim_policydev/apigw_gw_instances/general_cors.md
Labels: size/XS

#715 Fix formatting of common_compress_encoding
  content/en/docs/apim_policydev/apigw_gw_instances/common_compress_encoding.md
Labels: size/XS

#666 APIGOV-14719 Rathna review
  content/en/docs/central/connect-api-manager/_index.md
  content/en/docs/central/connect-api-manager/deploy-your-agents.md
  content/en/docs/central/connect-api-manager/discovery-agent-variables.md
  content/en/docs/central/connect-api-manager/prepare-amplify-central.md
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
  content/en/docs/central/connect-api-manager/traceability-agent-variables.md
  content/en/docs/central/connect-aws-gateway/_index.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-1.md
  content/en/docs/central/connect-aws-gateway/prepare-amplify-central-1.md
  content/en/docs/central/connect-aws-gateway/prepare-aws-api-gateway.md
  content/en/docs/central/connect-aws-gateway/subscription-for-the-consumer.md
Labels: size/M

#720 [RDAPI-19450] Removed the note on the Java keystore support as part o…
  content/en/docs/apimgmt_security/c_secgd_config_secconfig.md
Labels: needs push to prod, size/XS

#693 Issue 521: Update contrib guidelines
  content/en/docs/contribution_guidelines/_index.md
  content/en/docs/contribution_guidelines/writing_markdown.md
  static/Images/contributing/cms_workflow_draft.png
  static/Images/contributing/failed_checks.png
Labels: size/M

#661 Update page in pol filter ref section “attributes_retrieve”
  content/en/docs/apim_policydev/apigw_polref/attributes_retrieve.md
Labels: size/XS

#723 PolicyStudio/ConfigStudio SP steps - May2020
  content/en/docs/apim_relnotes/20200530_apimgr_relnotes/_index.md
Labels: needs push to prod, size/XS

#725 Fixing link to the correct GitHub-Project
  content/en/docs/api_mgmt_overview/api_mgmt_components/pipeline.md
Labels: size/XS

#727 Use the issue template when creating issues from website
  layouts/partials/page-meta-links.html
Labels: size/XS

#724 Update contrib guidelines for creating Github issues
  content/en/docs/contribution_guidelines/_index.md
Labels: size/S

#732 Update page in APIM SSO section “c_saml_trouble”
  content/en/docs/apim_administration/apimgr_sso/c_saml_trouble.md
Labels: size/XS

#733 Update page in APIG admin section “tracing”
  content/en/docs/apim_administration/apigtw_admin/tracing.md
Labels: needs push to prod, size/XS

#736 Revert "Update page in APIG admin section “tracing”"
  content/en/docs/apim_administration/apigtw_admin/tracing.md
Labels: size/S

#735 Update page in APIP admin section “customize_getting_started”
  content/en/docs/apim_administration/apiportal_admin/customize_getting_started.md
Labels: size/XS

#737 Revert "Update page in APIM SSO section “c_saml_trouble”"
  content/en/docs/apim_administration/apimgr_sso/c_saml_trouble.md
Labels: size/XS

#739 RDAPI-18387 Update Security Guide Best practices
  content/en/docs/apimgmt_security/c_secgd_bp_intro.md
Labels: size/S

#734 added "how-to" guide on IBM MQ server TLS setup
  content/en/docs/apim_howto_guides/_index.md
  content/en/docs/apim_howto_guides/apigw_mqclient_tlssetup.md
  static/Images/APIGateway/extconn_jms_service_ibmmq_advanced.png
  static/Images/APIGateway/extconn_jms_service_ibmmq_settings.png
  static/admin/config.js
Labels: needs push to prod, size/M

#740 Update page in Connect API Manager “_index”
  content/en/docs/central/connect-api-manager/_index.md
Labels: netlify-cms/pending_review, size/XS

#738 Protect sensitive information by adding git-secrets
  content/en/docs/contribution_guidelines/setup_work_locally.md
  scripts/git_secrets_setup.sh
Labels: size/M

#726 Improve the UX and navigation for the 77 release notes
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
  content/en/docs/apim_relnotes/201904_apimgr_relnotes/_index.md
  content/en/docs/apim_relnotes/201904_release/_index.md
  content/en/docs/apim_relnotes/201904_release/apig_fixedissues.md
  content/en/docs/apim_relnotes/201904_release/apig_relnotes.md
  content/en/docs/apim_relnotes/201904_release/apim_fixedissues.md
  content/en/docs/apim_relnotes/201904_release/apim_relnotes.md
  content/en/docs/apim_relnotes/201904_release/apip_relnotes.md
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20200130_apip_relnotes.md
  content/en/docs/apim_relnotes/20200330_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20200330_apip_relnotes.md
  content/en/docs/apim_relnotes/20200530_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20200530_apip_relnotes.md
  content/en/docs/apim_relnotes/_index.md
  static/admin/config.js
Labels: needs push to prod, size/M

#742 Corrected case numbers in APIM March release notes
  content/en/docs/apim_relnotes/20200330_apimgr_relnotes.md
Labels: needs push to prod, size/XS

#743 Fix CMS RN issues
  .github/CODEOWNERS
  content/en/docs/apim_relnotes/201904_release/_index.md
  content/en/docs/apim_relnotes/201904_release/apig_relnotes.md
  content/en/docs/apim_relnotes/201904_release/apim_relnotes.md
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20200330_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20200530_apimgr_relnotes.md
  content/en/docs/apim_relnotes/_index.md
  static/admin/config.js
Labels: size/S

#747 Update page in APIM release note section “20200530_apimgr_relnotes”
  content/en/docs/apim_relnotes/20200530_apimgr_relnotes.md
Labels: needs push to prod, size/XS

#756 Remove all config files that are no longer used
  Gruntfile.js
  docsy-config.toml
Labels: size/XS

#755 Update page in APIM release note section “20200530_apip_relnotes”
  content/en/docs/apim_relnotes/20200530_apip_relnotes.md
Labels: size/XS

#759 Cms/tsjohns9/axway open docs/mesh management/build hybrid env
  content/en/docs/central/mesh_management/build_hybrid_env.md
Labels: size/XS

#751 Update page in APIM release note section “20200530_apimgr_relnotes”
  content/en/docs/apim_relnotes/20200530_apimgr_relnotes.md
Labels: needs push to prod, size/S

#762 Update page in APIP install section “install_software”
  content/en/docs/apim_installation/apiportal_install/install_software.md
Labels: needs push to prod, size/XS

#753 Update page in APIM release note section “20200530_apimgr_relnotes”
  content/en/docs/apim_relnotes/20200530_apimgr_relnotes.md
Labels: needs push to prod, size/S

#766 Update page in APIM release note section “20200330_apimgr_relnotes”
  content/en/docs/apim_relnotes/20200330_apimgr_relnotes.md
Labels: needs push to prod, size/XS

#763 Update page in APIP install section “secure_harden_portal”
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
Labels: needs push to prod, size/XS

#757 Update page in APIP install section “upgrade_automatic”
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
Labels: needs push to prod, size/XS

#758 Update page in APIP install section “install_software”
  content/en/docs/apim_installation/apiportal_install/install_software.md
Labels: needs push to prod, size/XS

#767 Update page in APIM release note section “20200530_apimgr_relnotes”
  content/en/docs/apim_relnotes/20200530_apimgr_relnotes.md
Labels: needs push to prod, size/S

#768 Update page in instances and listeners section “general_services”
  content/en/docs/apim_policydev/apigw_gw_instances/general_services.md
Labels: size/XS

#760 Use DEPLOY_PRIME_URL in build command for develop
  netlify.toml
Labels: size/XS

#772 Trigger CI on develop branch
  .github/workflows/ciworkflow.yml
Labels: size/XS

#774 RDAPI-20086. Token Information Endpoint API.
  content/en/docs/apim_policydev/apigw_oauth/oauth_flows/oauth_flows_token_info.md
Labels: needs push to prod, size/XS

#775 try getting branch from URL
  static/admin/config.js
Labels: size/XS

#769 Update page in pol filter ref section “routing_common”
  content/en/docs/apim_policydev/apigw_polref/routing_common.md
Labels: needs push to prod, size/XS

#694 Update system_requirements.md
  content/en/docs/apim_installation/apigtw_install/system_requirements.md
Labels: needs push to prod, size/XS

#746 Update page in APIG admin section “tracing”
  content/en/docs/apim_administration/apigtw_admin/tracing.md
Labels: needs push to prod, size/XS

#748 Update page in APIM SSO section “c_saml_trouble”
  content/en/docs/apim_administration/apimgr_sso/c_saml_trouble.md
Labels: needs push to prod, size/XS

#771 Update api_mgmt_config_web.md
  content/en/docs/apim_reference/api_mgmt_config_web.md
Labels: needs push to prod, size/XS

#765 IAP-3163 Add Encrypt db password section to Upgrade API Portal page
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
Labels: needs push to prod, size/XS

#777 Update page in APIP install section “install_software_configure_database”
  content/en/docs/apim_installation/apiportal_install/install_software_configure_database.md
Labels: size/XS

#778 Create page in Connect API Manager “security-concerns”
  content/en/docs/central/connect-api-manager/security-concerns.md
  static/Images/central/connect-api-manager/agents-proxy.png
Labels: netlify-cms/pending_review, size/S

#770 Add code owners for missing and updated sections
  .github/CODEOWNERS
Labels: size/S

#776 Update page in APIP install section “install_software_prereqs”
  content/en/docs/apim_installation/apiportal_install/install_software_prereqs.md
Labels: size/XS

#779 Change to v7.9.0 of babel
  static/admin/index.html
Labels: size/XS

#782 Update system_requirements.md
  content/en/docs/apim_installation/apigtw_install/system_requirements.md
Labels: needs push to prod, size/XS

#773 Update page in APIP install section “install_dependencies”
  content/en/docs/apim_installation/apiportal_install/install_dependencies.md
Labels: size/XS

#783 Edit PS/CS release notes
  content/en/docs/apim_relnotes/20200530_apimgr_relnotes.md
Labels: needs push to prod, size/XS

#781 Fix formatting on list of steps
  content/en/docs/apim_administration/apiportal_admin/customize_getting_started.md
  content/en/docs/apim_installation/apiportal_install/install_software_configure_database.md
Labels: size/S

#787 Update page in Connect API Manager “security-concerns”
  content/en/docs/central/connect-api-manager/security-concerns.md
Labels: netlify-cms/pending_review, size/S

#792 Update page in APIM release note section “20200530_apimgr_relnotes”
  content/en/docs/apim_relnotes/20200530_apimgr_relnotes.md
Labels: needs push to prod, size/XS

#786 Update page in APIM release note section “20200530_apip_relnotes”
  content/en/docs/apim_relnotes/20200530_apip_relnotes.md
Labels: size/M

#796 Update Edit on GH link to use branch based on URL
  layouts/partials/page-meta-links.html
Labels: size/S

#785 Update page in APIM release note section “20200530_apip_relnotes”
  content/en/docs/apim_relnotes/20200530_apip_relnotes.md
Labels: size/S

#800 Setbranchforgithub
  layouts/partials/page-meta-links.html
Labels: size/XS

#795 Update page in APIP install section “install_dependencies”
  content/en/docs/apim_installation/apiportal_install/install_dependencies.md
Labels: size/XS

#801 Set branch based on URL for GitHub (take 3)
  layouts/partials/page-meta-links.html
Labels: size/XS

#804 Update page in APIM release note section “20200530_apimgr_relnotes”
  content/en/docs/apim_relnotes/20200530_apimgr_relnotes.md
Labels: needs push to prod, size/XS

#805 Update page in pol filter ref section “routing_common”
  content/en/docs/apim_policydev/apigw_polref/routing_common.md
Labels: size/XS

#788 Create page in APIP admin section “connect-api-portal-to-api-central”
  content/en/docs/apim_administration/apiportal_admin/expose_APIs_published_from_catalog.md
  content/en/docs/apim_relnotes/20200530_apip_relnotes.md
Labels: size/S

#806 Update page in APIM release note section “20200530_apip_relnotes”
  content/en/docs/apim_relnotes/20200530_apip_relnotes.md
Labels: size/XS
