Repository Axway/axway-open-docs, pull requests merged in 2020-07, with the labels that each got.

#918 Fixing dead link
  content/en/docs/central/fundamental_concepts.md
Labels: needs push to prod, size/XS

#903 Update cli_environments.md
  content/en/docs/central/cli_central/cli_environments.md
Labels: needs push to prod, size/S

#916 APIGOV15234 Security and Network topics
  content/en/docs/central/connect-api-manager/Agent-security-api-manager.md
  content/en/docs/central/connect-api-manager/network-traffic-apimanager.md
  content/en/docs/central/connect-aws-gateway/agent-security-aws.md
  content/en/docs/central/connect-aws-gateway/network-traffic-aws.md
Labels: netlify-cms/pending_review, size/M

#919 Update page in Connect API Manager “deploy-your-agents”
  content/en/docs/central/connect-api-manager/deploy-your-agents.md
Labels: netlify-cms/pending_review

#917 Clarifications about remoteHost and remotePort when using proxies
  .gitignore
  content/en/docs/apim_reference/open_logging_schema.md
Labels: needs push to prod, size/XS

#920 Docker Best-Practices - Technical tweaks + Backlinks into the How-To section
  content/en/docs/apim_howto_guides/apigw_in_containers.md
  content/en/docs/apim_installation/apigw_containers/docker_script_anmimage.md
  content/en/docs/apim_installation/apigw_containers/docker_script_baseimage.md
  content/en/docs/apim_installation/apigw_containers/docker_script_gwimage.md
Labels: needs push to prod, size/XS

#921 Added new NPE exception SSO touble-shooting section
  content/en/docs/apim_administration/apimgr_sso/c_saml_trouble.md
Labels: needs push to prod, size/XS

#926 Update page in Mesh management “add_env”
  content/en/docs/central/mesh_management/add_env.md
Labels: needs push to prod, size/XS

#927 APIGOV15237 - Cloud admin/operation
  content/en/docs/central/connect-aws-gateway/agent-security-aws.md
  content/en/docs/central/connect-aws-gateway/cloud-administration-operation.md
  content/en/docs/central/connect-aws-gateway/prepare-amplify-central-1.md
Labels: netlify-cms/pending_review, size/M

#892 Connect dataplanes minor changes
  content/en/docs/central/cli_central/cli_install.md
  content/en/docs/central/connect-api-manager/_index.md
  content/en/docs/central/connect-api-manager/deploy-your-agents.md
  content/en/docs/central/connect-api-manager/discovery-agent-variables.md
  content/en/docs/central/connect-api-manager/prepare-amplify-central.md
  content/en/docs/central/connect-aws-gateway/_index.md
  content/en/docs/central/connect-aws-gateway/prepare-amplify-central-1.md
  content/en/docs/central/mesh_management/add_env.md
Labels: needs push to prod, netlify-cms/pending_review, size/XS

#932 IAP-3396: Update 'Database password encryption' section on May2020 relnotes
  content/en/docs/apim_relnotes/20200530_apip_relnotes.md
Labels: needs push to prod, size/XS

#936 Update page in Connect AWS Gateway “prepare-aws-api-gateway”
  content/en/docs/central/connect-aws-gateway/prepare-aws-api-gateway.md
Labels: netlify-cms/pending_review, size/S

#925 Update page in APIM admin section “api_mgmt_virtualize_web”
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_admin.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_alerts.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_config.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_config_external.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_config_ps.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_connect_mobile_backend_services.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_connector.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_consume.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_custom.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_custom_policies.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_method_authz.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_monitor.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_promote.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_register_web.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_version_routing.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_virtualize_web.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_workflow.md
  content/en/docs/apim_administration/apimgr_admin/example_oauth_external.md
  static/Images/docbook/images/api_mgmt/api_mgmt_oauth_ext_jsonpathfilter.png
  static/Images/docbook/images/api_mgmt/api_mgmt_oauth_ext_jwtverifyfilter.png
  static/Images/docbook/images/api_mgmt/api_mgmt_oauth_ext_setattributefilter.png
  static/Images/docbook/images/api_mgmt/api_mgmt_oauth_ext_setmessagefilter.png
  static/Images/docbook/images/api_mgmt/api_mgmt_oauth_ext_stringreplacefilter.png
  static/Images/docbook/images/api_mgmt/api_mgmt_oauth_ext_tokeninformationpolicy.png
  static/Images/docbook/images/api_mgmt/api_mgmt_oauth_ext_validatetimestampfilter.png
Labels: needs push to prod, size/S

#937 Update page in APIP install section “install_software_configure_database”
  content/en/docs/apim_installation/apiportal_install/install_software_configure_database.md
Labels: needs push to prod, size/XS

#935 Updating upgrade steps
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_system_props.md
Labels: needs push to prod, size/S

#934 Gateway Admin (APIGOV-15234)
  content/en/docs/central/connect-api-manager/gateway-administation.md
Labels: size/M

#943 Update page in Connect API Manager “discovery-agent-variables”
  content/en/docs/central/connect-api-manager/discovery-agent-variables.md
Labels: netlify-cms/pending_review, size/XS

#942 Update page in Connect API Manager “deploy-your-agents”
  content/en/docs/central/connect-api-manager/deploy-your-agents.md
Labels: netlify-cms/pending_review, size/XS

#941 Update page in Connect API Manager “prepare-amplify-central”
  content/en/docs/central/connect-api-manager/prepare-amplify-central.md
Labels: netlify-cms/pending_publish, size/XS

#947 Update page in APIP install section “upgrade_automatic”
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
Labels: size/XS

#946 Update page in APIP install section “install_software”
  content/en/docs/apim_installation/apiportal_install/install_software.md
Labels: size/XS

#949 added back section that was previously added with #919
  content/en/docs/central/connect-api-manager/deploy-your-agents.md
Labels: netlify-cms/pending_review, size/S

#945 Update page in Connect API Manager “subscription-for-the-consumer”
  content/en/docs/central/connect-api-manager/subscription-for-the-consumer.md
Labels: netlify-cms/pending_review, size/S

#944 Update page in Connect API Manager “traceability-agent-variables”
  content/en/docs/central/connect-api-manager/traceability-agent-variables.md
Labels: netlify-cms/pending_review, size/XS

#950 security change per Dave
  content/en/docs/central/connect-api-manager/Agent-security-api-manager.md
  content/en/docs/central/connect-aws-gateway/agent-security-aws.md
Labels: netlify-cms/pending_review, size/XS

#952 Update 'Install Apache HTTP server and PHP'
  content/en/docs/apim_installation/apiportal_install/install_dependencies.md
Labels: size/XS

#958 removed Alpha note from all topics
  content/en/docs/central/connect-api-manager/Agent-security-api-manager.md
  content/en/docs/central/connect-api-manager/deploy-your-agents.md
  content/en/docs/central/connect-api-manager/discovery-agent-flags.md
  content/en/docs/central/connect-api-manager/discovery-agent-variables.md
  content/en/docs/central/connect-api-manager/filtering-apis-to-be-discovered.md
  content/en/docs/central/connect-api-manager/network-traffic-apimanager.md
  content/en/docs/central/connect-api-manager/prepare-amplify-central.md
  content/en/docs/central/connect-api-manager/subscription-for-the-consumer.md
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
  content/en/docs/central/connect-aws-gateway/_index.md
  content/en/docs/central/connect-aws-gateway/agent-security-aws.md
  content/en/docs/central/connect-aws-gateway/cloud-administration-operation.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-1.md
  content/en/docs/central/connect-aws-gateway/filtering-apis-to-be-discovered-1.md
  content/en/docs/central/connect-aws-gateway/network-traffic-aws.md
  content/en/docs/central/connect-aws-gateway/prepare-amplify-central-1.md
  content/en/docs/central/connect-aws-gateway/tips-and-troubleshooting.md
Labels: netlify-cms/pending_review, size/S

#957 Update page in Cassandra admin section “cassandra_bestpractices”
  content/en/docs/cass_admin/cassandra_bestpractices.md
Labels: needs push to prod, size/XS

#961 Update page in APIP admin section “customize_getting_started”
  content/en/docs/apim_administration/apiportal_admin/customize_getting_started.md
Labels: needs push to prod, size/XS

#962 Update page in APIM release note section “20200130_apip_relnotes”
  content/en/docs/apim_relnotes/20200130_apip_relnotes.md
Labels: needs push to prod, size/XS

#959 Update cli_install.md
  content/en/docs/central/cli_central/cli_install.md
Labels: needs push to prod, size/S

#965 broken links
  content/en/docs/central/connect-api-manager/Agent-security-api-manager.md
  content/en/docs/central/connect-api-manager/gateway-administation.md
  content/en/docs/central/connect-api-manager/network-traffic-apimanager.md
  content/en/docs/central/connect-api-manager/prepare-amplify-central.md
  content/en/docs/central/connect-api-manager/security-concerns.md
  content/en/docs/central/connect-api-manager/subscription-for-the-consumer.md
  content/en/docs/central/connect-aws-gateway/prepare-amplify-central-1.md
Labels: netlify-cms/pending_review, size/S

#967 AWS broken links
  content/en/docs/central/connect-aws-gateway/_index.md
  content/en/docs/central/connect-aws-gateway/cloud-administration-operation.md
  content/en/docs/central/connect-aws-gateway/subscription-for-the-consumer.md
Labels: size/S

#969 Change AWS icons #2
  content/en/docs/central/connect-aws-gateway/cloud-administration-operation.md
  static/Images/central/connect-aws-gateway/aws-discovery-agent_v2.png
  static/Images/central/connect-aws-gateway/aws-traceability-agent_v2.png
Labels: netlify-cms/draft, size/M

#954 RDAPI-20970 Created new file for customer configurations
  content/en/docs/apim_installation/apigw_upgrade/_index.md
  content/en/docs/apim_reference/api_mgmt_config_web.md
  content/en/docs/apim_reference/api_mgmt_responses.md
  content/en/docs/apim_reference/api_mgmt_rest_api.md
  content/en/docs/apim_reference/cassandra_settings.md
  content/en/docs/apim_reference/config_files_reference.md
  content/en/docs/apim_reference/devopstools_ref.md
  content/en/docs/apim_reference/general_activemq_settings.md
  content/en/docs/apim_reference/general_settings.md
  content/en/docs/apim_reference/log_global_settings.md
  content/en/docs/apim_reference/managedomain_ref.md
  content/en/docs/apim_reference/monitor_traffic_events_metrics.md
  content/en/docs/apim_reference/open_logging_schema.md
Labels: needs push to prod, size/S

#953 Fixing broken links
  content/en/_index.html
  content/en/docs/_index.md
  content/en/docs/apigtw_auth_auth/ca_siteminder_overview.md
  content/en/docs/apigtw_devguide/selectors.md
  content/en/docs/apigtw_devguide/unit_test_traffic_monitor.md
  content/en/docs/apim_administration/apigtw_admin/general_rbac.md
  content/en/docs/apim_administration/apigtw_admin/makegateway.md
  content/en/docs/apim_administration/apiportal_admin/expose_APIs_published_from_catalog.md
  content/en/docs/apim_administration/apiportal_admin/localize_language.md
  content/en/docs/apim_policydev/apigw_poldev/general_selector.md
  content/en/docs/apim_reference/log_global_settings.md
  content/en/docs/central/cft_profile.md
  content/en/docs/central/connect-api-manager/Agent-security-api-manager.md
  content/en/docs/central/connect-api-manager/_index.md
  content/en/docs/central/connect-api-manager/traceability-agent-variables.md
  content/en/docs/central/mesh_management/_index.md
Labels: needs push to prod, size/S

#971 Add a note on the limit on API Traffic page
  content/en/docs/central/quickstart.md
Labels: needs push to prod, size/XS

#970 RDAPI-19071 Update page in APIM admin section “api_mgmt_custom_policies”
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_custom_policies.md
Labels: needs push to prod, size/XS

#972 Update page in APIP install section “install_software_configure_database”
  content/en/docs/apim_installation/apiportal_install/install_software_configure_database.md
Labels: needs push to prod, size/XS

#973 Update page in APIP admin section “customize_page_content”
  content/en/docs/apim_administration/apiportal_admin/customize_page_content.md
Labels: needs push to prod, size/XS

#974 Update page in APIP install section “upgrade_automatic”
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
Labels: needs push to prod, size/XS

#979 Update page in APIP install section “install_software_configure_database”
  content/en/docs/apim_installation/apiportal_install/install_software_configure_database.md
Labels: needs push to prod, size/XS

#975 APIGOV-15414 - Add AWS cost
  content/en/docs/central/connect-aws-gateway/cloud-administration-operation.md
Labels: size/S

#983 Remove base64 option when generating keys - prepare-amplify-central-1”
  content/en/docs/central/connect-aws-gateway/prepare-amplify-central-1.md
Labels: size/XS

#984 Remove base64 option when generating keys - prepare-amplify-central
  content/en/docs/central/connect-api-manager/prepare-amplify-central.md
Labels: netlify-cms/pending_review, size/XS

#985 APIGOV-15313 - securing credentials
  content/en/docs/central/connect-api-manager/Agent-security-api-manager.md
  content/en/docs/central/connect-aws-gateway/agent-security-aws.md
Labels: size/S

#993 Upgrade API Gateway - minor restructuring and changes to improve readability
  content/en/docs/apim_installation/apigw_upgrade/_index.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_analytics.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_cassandra.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_errors.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_faq.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_log_analysis_ps.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_metrics.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_overview.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_script.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_troubleshoot.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_zdu_overview.md
Labels: needs push to prod, size/S

#994 fix broken link
  content/en/docs/apim_installation/apigw_upgrade/_index.md
Labels: size/XS

#990 APIGOV-15501 - align AWS & v7 docs
  content/en/docs/central/connect-api-manager/prepare-amplify-central.md
  content/en/docs/central/connect-aws-gateway/prepare-amplify-central-1.md
Labels: size/M

#995 Edit topic description in Connect AWS Gateway “prepare-amplify-central-1”
  content/en/docs/central/connect-aws-gateway/prepare-amplify-central-1.md
Labels: netlify-cms/pending_review, size/XS

#980 Update page in APIM release note section “20200730_apip_relnotes”
  content/en/docs/apim_relnotes/20200730_apip_relnotes.md
Labels: needs push to prod, size/XS

#992 Update page in APIM release note section “20200530_apip_relnotes”
  content/en/docs/apim_relnotes/20200530_apip_relnotes.md
Labels: needs push to prod, size/XS

#999 Fix Run failed merge to develop - master
  content/en/_index.html
  content/en/docs/_index.md
  content/en/docs/apigtw_auth_auth/ca_siteminder_overview.md
  content/en/docs/apigtw_devguide/selectors.md
  content/en/docs/apigtw_devguide/unit_test_traffic_monitor.md
  content/en/docs/apim_administration/apigtw_admin/general_rbac.md
  content/en/docs/apim_administration/apigtw_admin/makegateway.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_custom_policies.md
  content/en/docs/apim_administration/apiportal_admin/customize_page_content.md
  content/en/docs/apim_administration/apiportal_admin/expose_APIs_published_from_catalog.md
  content/en/docs/apim_administration/apiportal_admin/localize_language.md
  content/en/docs/apim_installation/apigw_upgrade/_index.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_analytics.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_cassandra.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_errors.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_faq.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_log_analysis_ps.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_metrics.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_overview.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_script.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_troubleshoot.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_zdu_overview.md
  content/en/docs/apim_installation/apiportal_install/install_software_configure_database.md
  content/en/docs/apim_policydev/apigw_poldev/general_selector.md
  content/en/docs/apim_reference/api_mgmt_config_web.md
  content/en/docs/apim_reference/api_mgmt_responses.md
  content/en/docs/apim_reference/api_mgmt_rest_api.md
  content/en/docs/apim_reference/cassandra_settings.md
  content/en/docs/apim_reference/config_files_reference.md
  content/en/docs/apim_reference/devopstools_ref.md
  content/en/docs/apim_reference/general_activemq_settings.md
  content/en/docs/apim_reference/general_settings.md
  content/en/docs/apim_reference/log_global_settings.md
  content/en/docs/apim_reference/managedomain_ref.md
  content/en/docs/apim_reference/monitor_traffic_events_metrics.md
  content/en/docs/apim_reference/open_logging_schema.md
  content/en/docs/apim_reference/scripts_changelog_SP.md
  content/en/docs/apim_relnotes/20200530_apip_relnotes.md
  content/en/docs/central/cft_profile.md
  content/en/docs/central/connect-api-manager/Agent-security-api-manager.md
  content/en/docs/central/connect-api-manager/_index.md
  content/en/docs/central/connect-api-manager/deploy-your-agents.md
  content/en/docs/central/connect-api-manager/prepare-amplify-central.md
  content/en/docs/central/connect-api-manager/subscription-for-the-consumer.md
  content/en/docs/central/connect-api-manager/traceability-agent-variables.md
  content/en/docs/central/connect-aws-gateway/agent-security-aws.md
  content/en/docs/central/connect-aws-gateway/cloud-administration-operation.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-1.md
  content/en/docs/central/connect-aws-gateway/prepare-amplify-central-1.md
  content/en/docs/central/connect-aws-gateway/subscription-for-the-consumer.md
  content/en/docs/central/mesh_management/_index.md
  content/en/docs/central/quickstart.md
Labels: size/XL

#997 [RDAPI-20252] SP13 Installation questions with respect to Client App Registry only install
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
Labels: needs push to prod, size/XS

#1015 APIGOV-15683 Improve structure
  content/en/docs/central/connect-aws-gateway/_index.md
  content/en/docs/central/connect-aws-gateway/agent-security-aws.md
  content/en/docs/central/connect-aws-gateway/cloud-administration-operation.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-1.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-quickstart.md
  content/en/docs/central/connect-aws-gateway/filtering-apis-to-be-discovered-1.md
  content/en/docs/central/connect-aws-gateway/impact-of-deleting-an-api-stage.md
  content/en/docs/central/connect-aws-gateway/network-traffic-aws.md
  content/en/docs/central/connect-aws-gateway/ssl-tls-advanced-1.md
  content/en/docs/central/connect-aws-gateway/subscription-for-the-consumer.md
  content/en/docs/central/connect-aws-gateway/tips-and-troubleshooting.md
Labels: size/M

#1018 Update page in APIG admin section “admin_non_root”
  content/en/docs/apim_administration/apigtw_admin/admin_non_root.md
Labels: needs push to prod, size/XS

#1021 Merge develop into master for July 20
  content/en/docs/apim_administration/apiportal_admin/customize_page_content.md
  content/en/docs/apim_installation/apiportal_install/install_dependencies.md
  content/en/docs/apim_installation/apiportal_install/install_software.md
  content/en/docs/apim_installation/apiportal_install/mutual-tls-authentication-with-api-manager.md
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
  content/en/docs/apim_policydev/apigw_gw_instances/general_remote_hosts.md
  content/en/docs/apim_policydev/apigw_gw_instances/general_services.md
  content/en/docs/apim_reference/general_settings.md
  content/en/docs/apim_relnotes/20200730_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20200730_apip_relnotes.md
Labels: size/XL

#1026 Update page in Connect API Manager “network-traffic-apimanager”
  content/en/docs/central/connect-api-manager/network-traffic-apimanager.md
Labels: netlify-cms/pending_review, size/XS
