Repository Axway/axway-open-docs, pull requests merged in 2020-08, with the labels that each got.

#1028 (APIGOV-15487) Improve v7 structure
  content/en/docs/central/connect-api-manager/Agent-security-api-manager.md
  content/en/docs/central/connect-api-manager/agent-variables.md
  content/en/docs/central/connect-api-manager/deploy-your-agents-quickstart.md
  content/en/docs/central/connect-api-manager/deploy-your-agents.md
  content/en/docs/central/connect-api-manager/discovery-agent-flags.md
  content/en/docs/central/connect-api-manager/filtering-apis-to-be-discovered.md
  content/en/docs/central/connect-api-manager/gateway-administation.md
  content/en/docs/central/connect-api-manager/impact-of-unpublishing-an-api.md
  content/en/docs/central/connect-api-manager/network-traffic-apimanager.md
  content/en/docs/central/connect-api-manager/subscription-for-the-consumer.md
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
  content/en/docs/central/connect-api-manager/traceability-agent-flags.md
  content/en/docs/central/connect-aws-gateway/agent-security-aws.md
Labels: size/M

#1027 Update tips-troubleshooting-and-limitations.md
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
Labels: size/S

#1030 APIGOV-15637 - public_key becomes public_key.pem
  content/en/docs/central/connect-api-manager/deploy-your-agents.md
  content/en/docs/central/connect-api-manager/discovery-agent-flags.md
  content/en/docs/central/connect-api-manager/gateway-administation.md
  content/en/docs/central/connect-api-manager/prepare-amplify-central.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-1.md
  content/en/docs/central/connect-aws-gateway/prepare-amplify-central-1.md
Labels: size/S

#1031 (APIGOV-15690) delete publishToCatalog
  content/en/docs/central/connect-api-manager/agent-variables.md
  content/en/docs/central/connect-api-manager/deploy-your-agents.md
  content/en/docs/central/connect-api-manager/discovery-agent-flags.md
  content/en/docs/central/connect-api-manager/gateway-administation.md
  content/en/docs/central/connect-api-manager/impact-of-unpublishing-an-api.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-1.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-quickstart.md
  content/en/docs/central/connect-aws-gateway/impact-of-deleting-an-api-stage.md
Labels: size/S

#1025 Update 20200730_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20200730_apimgr_relnotes.md
Labels: needs push to prod, size/XS

#1035 Add redirect to Streams microsite
  netlify.toml
Labels: size/XS

#1017 RMF-8 Update page in APIM admin section “api_mgmt_admin”
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_admin.md
Labels: needs push to prod, size/S

#1040 Revert "Add redirect to Streams microsite"
  netlify.toml
Labels: size/XS

#1041 Update page in APIM release note section “20200730_apimgr_relnotes”
  content/en/docs/apim_relnotes/20200730_apimgr_relnotes.md
Labels: needs push to prod, size/XS

#1033 Update page in APIP install section “upgrade_automatic”
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
Labels: size/XS

#1034 Correct footer customizations path in "Upgrade API Portal"
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
Labels: needs push to prod, size/XS

#1046 Update system_requirements.md
  content/en/docs/apim_installation/apigtw_install/system_requirements.md
Labels: size/XS

#1045 Update AWS cost
  content/en/docs/central/connect-aws-gateway/cloud-administration-operation.md
Labels: size/S

#1043 Update page in APIP admin section “localize_language”
  content/en/docs/apim_administration/apiportal_admin/localize_language.md
Labels: size/XS

#1042 RMF-2 Streams microsite - remove content from APIM repo
  content/en/_index.html
  content/en/docs/_index.md
  content/en/docs/streams/_index.md
  content/en/docs/streams/concepts.md
  content/en/docs/streams/management-api.md
  content/en/docs/streams/publishers/_index.md
  content/en/docs/streams/publishers/publisher-http-poller.md
  content/en/docs/streams/publishers/publisher-http-post.md
  content/en/docs/streams/publishers/publisher-kafka.md
  content/en/docs/streams/publishers/publisher-sfdc.md
  content/en/docs/streams/quickstart.md
  content/en/docs/streams/subscribers/_index.md
  content/en/docs/streams/subscribers/subscriber-kafka.md
  content/en/docs/streams/subscribers/subscriber-sse.md
  content/en/docs/streams/subscribers/subscriber-webhook.md
  content/en/docs/streams/subscribers/subscribers-errors.md
  netlify.toml
  static/Images/streams/streams-architecture-concepts.png
  static/admin/config.js
Labels: size/XL

#1039 Updated helm install command for ALS deployment
  content/en/docs/central/mesh_management/add_env.md
Labels: needs push to prod, size/XS

#1053 Update page in APIM release note section “20200530_apip_relnotes”
  content/en/docs/apim_relnotes/20200530_apip_relnotes.md
Labels: needs push to prod, size/XS

#1061 RDAPI-21366 incorrect update-apimanager option documented
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
Labels: needs push to prod, size/XS

#1054 Update page in APIM release note section “20200730_apimgr_relnotes”
  content/en/docs/apim_relnotes/20200730_apimgr_relnotes.md
Labels: needs push to prod, size/XS

#1062 Revert "Update page in APIM release note section “20200730_apimgr_relnotes”"
  content/en/docs/apim_relnotes/20200730_apimgr_relnotes.md
Labels: size/M

#1047 RMF-4: Turn goldmark on and fix index page
  config.toml
  content/en/_index.html
  content/en/docs/contribution_guidelines/writing_markdown.md
Labels: size/S

#1065 Update page in APIM release note section “20200730_apimgr_relnotes”
  content/en/docs/apim_relnotes/20200730_apimgr_relnotes.md
Labels: needs push to prod, size/XS

#1070 APIGOV-15487 Change titles
  content/en/docs/central/connect-api-manager/agent-variables.md
  content/en/docs/central/connect-api-manager/discovery-agent-flags.md
Labels: size/XS

#1071 Update page in APIP admin section “role_mapping”
  content/en/docs/apim_administration/apiportal_admin/role_mapping.md
Labels: size/XS

#1037 Added inventory of Java level properties and settings
  content/en/docs/apim_reference/config_files_reference.md
Labels: needs push to prod, size/S, user feedback

#1101 Remove Alex from codeowners
  .github/CODEOWNERS
Labels: size/S

#1099 Fix the link to Embedded ActiveMQ settings page
  content/en/docs/apim_policydev/apigw_poldev/general_messaging.md
Labels: needs push to prod, size/XS

#1088 Update page in pol filter ref section “attributes_manipulate”
  content/en/docs/apim_policydev/apigw_polref/attributes_manipulate.md
Labels: needs push to prod, size/XS

#1105 Create Sep20 Release note pages into develop branch
  content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20200930_apip_relnotes.md
Labels: size/L

#1072 IAP-3188 Create page in APIP admin section “gdpr-compliance”
  content/en/docs/apim_administration/apiportal_admin/apip_overview.md
  content/en/docs/apim_administration/apiportal_admin/customize_APICatalog_overview.md
  content/en/docs/apim_administration/apiportal_admin/customize_css_styles.md
  content/en/docs/apim_administration/apiportal_admin/customize_getting_started.md
  content/en/docs/apim_administration/apiportal_admin/customize_page_content.md
  content/en/docs/apim_administration/apiportal_admin/expose_APIs_published_from_catalog.md
  content/en/docs/apim_administration/apiportal_admin/localize_language.md
  content/en/docs/apim_administration/apiportal_admin/manage_privacy_personal_data.md
  content/en/docs/apim_administration/apiportal_admin/public_api_configure.md
  content/en/docs/apim_administration/apiportal_admin/role_mapping.md
  content/en/docs/apim_administration/apiportal_admin/troubleshooting.md
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
  static/Images/APIPortal/system_users_actions_logs_plugin.png
  static/Images/APIPortal/user_actions_logs_options.png
  static/Images/APIPortal/user_actions_logs_table.png
Labels: needs push to prod, size/M

#1104 Update image in Connect API Manager “_index”
  content/en/docs/central/connect-api-manager/_index.md
  static/Images/central/connect-api-manager/servicediscoveryapim.png
Labels: netlify-cms/pending_review, size/XS

#1096 Update page in AMPLIFY Central CLI “cli_environments”
  content/en/docs/central/cli_central/cli_environments.md
Labels: needs push to prod, size/XS

#1092 Update install_unattended.md
  content/en/docs/apim_installation/apiportal_install/install_unattended.md
Labels: needs push to prod, size/XS

#1109 Update apiconsumerinstance.json file
  static/samples/central/apiconsumerinstance.json
Labels: size/S

#1111 Update Central CLI files
  static/samples/central/apisecret.json
  static/samples/central/apisubscription.json
  static/samples/central/apiwebhook.json
  static/samples/central/sdkconsumerinstance.json
Labels: size/M

#1102 Update add_env.md
  content/en/docs/central/mesh_management/add_env.md
  package-lock.json
  package.json
Labels: needs push to prod, size/XS

#1103 Update build_hybrid_env.md
  content/en/docs/central/mesh_management/build_hybrid_env.md
Labels: needs push to prod, size/XS
