Repository Axway/axway-open-docs, pull requests merged in 2020-06, with the labels that each got.

#808 [RDAPI-20250] Implement a development branch
  .github/workflows/ciworkflow.yml
  layouts/partials/page-meta-links.html
  netlify.toml
  static/admin/config.js
Labels: sized_in_jira

#818 Create workflow to merge master branch into develop branch
  .github/workflows/merge_to_develop.yml
Labels: size/S

#819 Correction to the case Ids in the fixed lists
  content/en/docs/apim_relnotes/20200530_apimgr_relnotes.md
Labels: needs push to prod, size/XS

#815 Update page in Connect API Manager “security-concerns”
  content/en/docs/central/connect-api-manager/security-concerns.md
Labels: netlify-cms/pending_review, size/S

#820 Update page in Connect API Manager “security-concerns”
  content/en/docs/central/connect-api-manager/security-concerns.md
  static/Images/central/connect-api-manager/agents-proxy2.png
Labels: netlify-cms/pending_review, size/S

#817 Update page in APIP admin section “customize_getting_started”
  content/en/docs/apim_administration/apiportal_admin/customize_getting_started.md
Labels: needs push to prod, size/XS

#822 Revert "Change to v7.9.0 of babel"
  static/admin/index.html
Labels: size/XS

#813 Fix #812
  content/en/docs/apim_policydev/apigw_external_connections/common_db_conf.md
  content/en/docs/apim_policydev/apigw_polref/attributes_retrieve.md
Labels: blocked, needs push to prod, size/S

#827 Update page in APIP install section “install_dependencies”
  content/en/docs/apim_installation/apiportal_install/install_dependencies.md
Labels: needs push to prod, size/XS

#741 Update page in Cassandra admin section “cassandra_bur”
  content/en/docs/cass_admin/cassandra_bur.md
Labels: needs push to prod, size/XS

#837 Update scripts should be mentioned in the new features section
  content/en/docs/apim_relnotes/20200530_apimgr_relnotes.md
Labels: needs push to prod, size/XS

#825 Update page in AMPLIFY Unified Catalog “_index”
  content/en/docs/catalog/_index.md
  static/Images/catalog/automate-the-population-of-the-unified-catalog-from-multiple-sources.png
Labels: needs push to prod, size/S

#835 Support for Redhat 8 / Centos 8 available starting with the 7.7 May Update
  content/en/docs/apim_installation/apigtw_install/system_requirements.md
Labels: needs push to prod, size/XS

#841 Add explanation that Stoplight is ONE option
  content/en/docs/api_mgmt_overview/api_mgmt_components/stoplight.md
  content/en/docs/api_mgmt_overview/api_mgmt_lifecycle.md
Labels: needs push to prod, size/XS

#834 Update page in APIP install section “secure_harden_portal”
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
Labels: needs push to prod, size/XS

#845 Update page in APIM release note section “20200530_apimgr_relnotes”
  content/en/docs/apim_relnotes/20200530_apimgr_relnotes.md
Labels: needs push to prod, size/XS

#833 Update page in Cassandra admin section “cassandra_bestpractices”
  content/en/docs/cass_admin/cassandra_bestpractices.md
Labels: needs push to prod, size/XS

#836 IAP-3189 Add 'General Data Protection' section to “secure_harden_portal”
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
Labels: size/XS

#849 RDAPI-20501 Add video links to documentation
  content/en/docs/apim_installation/apiportal_install/connect_to_apimgr.md
  content/en/docs/apim_installation/apiportal_install/install_software.md
  content/en/docs/apim_installation/apiportal_install/install_unattended.md
Labels: size/M

#830 Update page in Connect API Manager “_index”
  content/en/docs/central/connect-api-manager/_index.md
Labels: blocked, netlify-cms/pending_review, size/S

#832 Remove deflists, add guidance
  .github/workflows/ciworkflow.yml
  content/en/docs/apigtw_devguide/jython_scripting.md
  content/en/docs/apim_administration/apigtw_admin/admin_messaging.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_config_external.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_virtualize_web.md
  content/en/docs/apim_installation/apigw_containers/docker_script_anmimage.md
  content/en/docs/apim_installation/apiportal_docker/docker_config.md
  content/en/docs/apim_reference/cassandra_settings.md
  content/en/docs/apim_reference/log_global_settings.md
  content/en/docs/apimgmt_security/compliance_appendix.md
  content/en/docs/contribution_guidelines/writing_markdown.md
Labels: blocked, needs push to prod, size/L

#838 Validate access token response correction
  content/en/docs/apim_policydev/apigw_oauth/resource_server_filters.md
Labels: blocked, needs push to prod, size/XS

#840 Update page in Cassandra admin section “cassandra_bur”
  content/en/docs/cass_admin/cassandra_bur.md
Labels: needs push to prod, size/XS

#846 Update page in APIM release note section “20200530_apimgr_relnotes”
  content/en/docs/apim_relnotes/20200530_apimgr_relnotes.md
Labels: blocked, needs push to prod, size/XS

#847 RDAPI-20553 - Update page in APIG admin section “admin_non_root”
  content/en/docs/apim_administration/apigtw_admin/admin_non_root.md
Labels: size/S

#853 RDAPI-20501 merge develop branch into the master branch
  content/en/docs/apim_installation/apiportal_install/connect_to_apimgr.md
  content/en/docs/apim_installation/apiportal_install/install_software.md
  content/en/docs/apim_installation/apiportal_install/install_unattended.md
Labels: size/M

#839 APIGOV-15076 - First PR from Git (Filtering / SSL)
  content/en/docs/central/connect-api-manager/filtering-apis-to-be-discovered.md
  content/en/docs/central/connect-api-manager/ssl-tls-advanced.md
Labels: blocked, needs push to prod

#851 Update page in Connect API Manager “deploy-your-agents”
  content/en/docs/central/connect-api-manager/deploy-your-agents.md
Labels: blocked, needs push to prod, size/L

#842 Template for July RNs, improve consistency
  content/en/docs/apim_relnotes/20200730_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20200730_apip_relnotes.md
Labels: size/L

#858 Update link to docs.axway.com
  content/en/docs/apigtw_devguide/rest_api.md
Labels: size/XS

#860 Update page in APIP install section “install_dependencies”
  content/en/docs/apim_installation/apiportal_install/install_dependencies.md
Labels: size/XS

#862 [SPHERE-1046] Fix broken links in SphereAPI(Support API) docs
  content/en/docs/shared_services/supportapi/formats/add_note_res.md
  content/en/docs/shared_services/supportapi/formats/close_case_res.md
  content/en/docs/shared_services/supportapi/formats/create_case_req.md
  content/en/docs/shared_services/supportapi/formats/create_case_res.md
  content/en/docs/shared_services/supportapi/formats/error_response.md
  content/en/docs/shared_services/supportapi/formats/get_case_res.md
  content/en/docs/shared_services/supportapi/formats/list_cases_req.md
  content/en/docs/shared_services/supportapi/formats/list_cases_res.md
  content/en/docs/shared_services/supportapi/methods/add_note.md
  content/en/docs/shared_services/supportapi/methods/close_case.md
  content/en/docs/shared_services/supportapi/methods/create_case.md
  content/en/docs/shared_services/supportapi/methods/download_attachment.md
  content/en/docs/shared_services/supportapi/methods/get_accounts.md
  content/en/docs/shared_services/supportapi/methods/get_case.md
  content/en/docs/shared_services/supportapi/methods/get_products.md
  content/en/docs/shared_services/supportapi/methods/list_cases.md
Labels: needs push to prod, size/S

#868 Update page in APIM SSO section “sso_mapping”
  content/en/docs/apim_administration/apimgr_sso/sso_mapping.md
Labels: needs push to prod, size/XS

#859 New section Get started with AMPLIFY Central CLI
  content/en/docs/central/backend_TLS.md
  content/en/docs/central/cli_central/_index.md
  content/en/docs/central/cli_central/cli_apiservices.md
  content/en/docs/central/cli_central/cli_environments.md
  content/en/docs/central/cli_central/cli_install.md
  content/en/docs/central/cli_central/cli_proxy_flow.md
  content/en/docs/central/cli_central/cli_publish.md
  content/en/docs/central/cli_environments.md
  content/en/docs/central/overview.md
  content/en/docs/central/proxy_rate_limit.md
  static/admin/config.js
Labels: needs push to prod, size/L

#876 Central CLI - create folder Samples and update links
  content/en/docs/central/cli_central/cli_apiservices.md
  content/en/docs/central/cli_central/cli_environments.md
  content/en/docs/central/cli_central/cli_publish.md
  static/samples/central/apiconsumerinstance.json
  static/samples/central/apiendpoint.json
  static/samples/central/apirevisions1.json
  static/samples/central/apirevisions1_decode.json
  static/samples/central/apisecret.json
  static/samples/central/apiservice.json
  static/samples/central/apiservice.yaml
  static/samples/central/apisubscription.json
  static/samples/central/apiwebhook.json
  static/samples/central/create_environments.json
  static/samples/central/publishAPI.json
  static/samples/central/sdkconsumerinstance.json
Labels: size/L

#869 Fix Caniuse issue when running hugo
  package-lock.json
Labels: size/L

#882 Central CLI - update path of sample files
  content/en/docs/central/cli_central/cli_apiservices.md
  content/en/docs/central/cli_central/cli_environments.md
  content/en/docs/central/cli_central/cli_publish.md
  static/samples/create_environments.yaml
Labels: size/S

#878 Update docker scripts download for 7.7.x
  content/en/docs/apim_installation/apigw_containers/docker_scripts_prereqs.md
Labels: needs push to prod, size/XS

#880 Case 01140855 Update page in APIG admin section “admin_open_logging”
  content/en/docs/apim_administration/apigtw_admin/admin_open_logging.md
Labels: needs push to prod, size/XS

#866 Update page in APIP install section “upgrade_automatic”
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
Labels: size/XS

#867 Update page in APIP install section “install_dependencies”
  content/en/docs/apim_installation/apiportal_install/install_dependencies.md
Labels: needs push to prod, size/XS

#861 Update page in APIM release note section “20200330_apip_relnotes”
  content/en/docs/apim_relnotes/20200330_apip_relnotes.md
Labels: needs push to prod, size/XS

#879 Update page in APIP admin section “customize_page_content”
  content/en/docs/apim_administration/apiportal_admin/customize_page_content.md
Labels: needs push to prod, size/XS

#883 Swagger promote now apim cli
  content/en/docs/api_mgmt_overview/api_mgmt_components/pipeline.md
  content/en/docs/api_mgmt_overview/api_mgmt_components/stoplight.md
  content/en/docs/api_mgmt_overview/api_mgmt_components/tools.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_promote.md
Labels: needs push to prod, size/XS

#884 Update page in APIP install section “install_software_redis”
  content/en/docs/apim_installation/apiportal_install/install_software_redis.md
Labels: needs push to prod, size/XS

#888 RDAPI-19457 - Update page in instances and listeners section “general_services”
  content/en/docs/apim_policydev/apigw_gw_instances/general_services.md
Labels: size/XS

#889 RDAPI-19457 - Update page in instances and listeners section “general_remote_hosts”
  content/en/docs/apim_policydev/apigw_gw_instances/general_remote_hosts.md
Labels: size/XS

#886 RDAPI-19457 - Update page in APIM ref section “general_settings”
  content/en/docs/apim_reference/general_settings.md
  static/samples/create_environments.yaml
Labels: size/XS

#893 Move create_environments.yaml file to Central folder
  static/samples/central/create_environments.yaml
Labels: size/XS

#871 Adding existing Container Ref Arch. documents for AWS & Azure
  content/en/docs/apim-reference-architectures/_index.md
  content/en/docs/apim-reference-architectures/container-aws/_index.md
  content/en/docs/apim-reference-architectures/container-azure/_index.md
  static/Images/apim-reference-architectures/container-aws/image1.png
  static/Images/apim-reference-architectures/container-aws/image10.png
  static/Images/apim-reference-architectures/container-aws/image11.png
  static/Images/apim-reference-architectures/container-aws/image2.jpg
  static/Images/apim-reference-architectures/container-aws/image3.png
  static/Images/apim-reference-architectures/container-aws/image4.png
  static/Images/apim-reference-architectures/container-aws/image5.JPG
  static/Images/apim-reference-architectures/container-aws/image6.png
  static/Images/apim-reference-architectures/container-aws/image7.png
  static/Images/apim-reference-architectures/container-aws/image8.png
  static/Images/apim-reference-architectures/container-aws/image9.tmp
  static/Images/apim-reference-architectures/container-azure/image1.png
  static/Images/apim-reference-architectures/container-azure/image10.JPG
  static/Images/apim-reference-architectures/container-azure/image11.JPG
  static/Images/apim-reference-architectures/container-azure/image13.png
  static/Images/apim-reference-architectures/container-azure/image14.png
  static/Images/apim-reference-architectures/container-azure/image15.tmp
  static/Images/apim-reference-architectures/container-azure/image16.png
  static/Images/apim-reference-architectures/container-azure/image17.png
  static/Images/apim-reference-architectures/container-azure/image2.jpg
  static/Images/apim-reference-architectures/container-azure/image3.jpg
  static/Images/apim-reference-architectures/container-azure/image4.png
  static/Images/apim-reference-architectures/container-azure/image5.JPG
  static/Images/apim-reference-architectures/container-azure/image6.png
  static/Images/apim-reference-architectures/container-azure/image8.png
  static/admin/config.js
Labels: needs push to prod, size/XL

#897 Manually update develop branch
  content/en/docs/apim-reference-architectures/_index.md
  content/en/docs/apim-reference-architectures/container-aws/_index.md
  content/en/docs/apim-reference-architectures/container-azure/_index.md
  static/Images/apim-reference-architectures/container-aws/image1.png
  static/Images/apim-reference-architectures/container-aws/image10.png
  static/Images/apim-reference-architectures/container-aws/image11.png
  static/Images/apim-reference-architectures/container-aws/image2.jpg
  static/Images/apim-reference-architectures/container-aws/image3.png
  static/Images/apim-reference-architectures/container-aws/image4.png
  static/Images/apim-reference-architectures/container-aws/image5.JPG
  static/Images/apim-reference-architectures/container-aws/image6.png
  static/Images/apim-reference-architectures/container-aws/image7.png
  static/Images/apim-reference-architectures/container-aws/image8.png
  static/Images/apim-reference-architectures/container-aws/image9.tmp
  static/Images/apim-reference-architectures/container-azure/image1.png
  static/Images/apim-reference-architectures/container-azure/image10.JPG
  static/Images/apim-reference-architectures/container-azure/image11.JPG
  static/Images/apim-reference-architectures/container-azure/image13.png
  static/Images/apim-reference-architectures/container-azure/image14.png
  static/Images/apim-reference-architectures/container-azure/image15.tmp
  static/Images/apim-reference-architectures/container-azure/image16.png
  static/Images/apim-reference-architectures/container-azure/image17.png
  static/Images/apim-reference-architectures/container-azure/image2.jpg
  static/Images/apim-reference-architectures/container-azure/image3.jpg
  static/Images/apim-reference-architectures/container-azure/image4.png
  static/Images/apim-reference-architectures/container-azure/image5.JPG
  static/Images/apim-reference-architectures/container-azure/image6.png
  static/Images/apim-reference-architectures/container-azure/image8.png
  static/admin/config.js
  static/samples/central/create_environments.yaml
Labels: size/L

#898 Remove extra line to fix how doc appears in CMS
  content/en/docs/apim-reference-architectures/container-aws/_index.md
Labels: needs push to prod, size/XS

#856 Update page in Connect API Manager “tips-troubleshooting-and-limitations”
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
Labels: needs push to prod, netlify-cms/pending_review, size/S

#899 Mergemanuallyagain
  content/en/docs/apim-reference-architectures/container-aws/_index.md
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
Labels: size/S

#900 Make same linter fix on master
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
Labels: needs push to prod, size/XS

#895 Changed wording of admin_non_root.md
  content/en/docs/apim_administration/apigtw_admin/admin_non_root.md
Labels: needs push to prod, size/XS

#902 Update cli_apiservices.md
  content/en/docs/central/cli_central/_index.md
  content/en/docs/central/cli_central/cli_apiservices.md
  content/en/docs/central/cli_central/cli_install.md
Labels: needs push to prod, size/S

#904 How to install Policy- & Config-Studio on Windows without Admin-Privs
  content/en/docs/apim_installation/apigtw_install/install_config_studio.md
  content/en/docs/apim_installation/apigtw_install/install_policy_studio.md
Labels: needs push to prod, size/XS

#894 Add estimated reading time ERT to the pages
  config.toml
  content/en/docs/api_mgmt_overview/_index.md
  content/en/docs/api_mgmt_overview/api_mgmt_components/tools.md
  content/en/docs/api_mgmt_overview/key_concepts/_index.md
  content/en/docs/apigtw_auth_auth/_index.md
  content/en/docs/apigtw_devguide/_index.md
  content/en/docs/apigtw_devops/_index.md
  content/en/docs/apigtw_kerberos/_index.md
  content/en/docs/apim_administration/_index.md
  content/en/docs/apim_administration/apigtw_admin/_index.md
  content/en/docs/apim_administration/apimgr_admin/_index.md
  content/en/docs/apim_administration/apiportal_admin/_index.md
  content/en/docs/apim_howto_guides/_index.md
  content/en/docs/apim_installation/_index.md
  content/en/docs/apim_installation/apigtw_install/_index.md
  content/en/docs/apim_installation/apigw_containers/_index.md
  content/en/docs/apim_installation/apigw_upgrade/_index.md
  content/en/docs/apim_installation/apiportal_install/_index.md
  content/en/docs/apim_policydev/_index.md
  content/en/docs/apim_reference/_index.md
  content/en/docs/apim_relnotes/_index.md
  content/en/docs/apimanager_analytics/_index.md
  content/en/docs/apimanager_capacityguide/_index.md
  content/en/docs/apimgmt_security/_index.md
  content/en/docs/cass_admin/_index.md
  content/en/docs/catalog/discover-and-consume-catalog-assets.md
  content/en/docs/catalog/manage_subscriptions.md
  content/en/docs/central/_index.md
  content/en/docs/central/backend_TLS.md
  content/en/docs/central/backend_authn.md
  content/en/docs/central/cft_profile.md
  content/en/docs/central/cli_central/_index.md
  content/en/docs/central/cli_central/cli_apiservices.md
  content/en/docs/central/cli_central/cli_environments.md
  content/en/docs/central/cli_central/cli_install.md
  content/en/docs/central/cli_central/cli_proxy_flow.md
  content/en/docs/central/cli_central/cli_publish.md
  content/en/docs/central/feauth_oauth.md
  content/en/docs/central/fundamental_concepts.md
  content/en/docs/central/mesh_management/_index.md
  content/en/docs/central/mesh_management/add_env.md
  content/en/docs/central/mesh_management/build_hybrid_env.md
  content/en/docs/central/overview.md
  content/en/docs/central/proxy_rate_limit.md
  content/en/docs/central/quickstart.md
  content/en/docs/central/secure_api_jwt.md
  content/en/docs/glossary/_index.md
  content/en/docs/shared_services/_index.md
  content/en/docs/shared_services/supportapi/_index.md
  content/en/docs/shared_services/supportapi/formats/_index.md
  content/en/docs/shared_services/supportapi/methods/_index.md
  content/en/docs/streams/_index.md
  content/en/docs/streams/quickstart.md
  layouts/_default/content.html
  layouts/docs/list.html
  layouts/partials/reading-time.html
Labels: size/M

#912 Add code owners for APIM ref arch
  .github/CODEOWNERS
Labels: size/XS

#914 Update page in APIM release note section “20200530_apimgr_relnotes”
  content/en/docs/apim_relnotes/20200530_apimgr_relnotes.md
Labels: needs push to prod, size/XS

#905 Update page in APIP install section “secure_harden_portal”
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
Labels: needs push to prod, size/XS

#908 Central CLI - Update 'Create and publish other resource types' page
  content/en/docs/central/cli_central/cli_publish.md
  static/samples/central/publishAPI.json
  static/samples/central/sdkconsumerinstance.json
Labels: needs push to prod

#913 Initial version of Tips and Tricks for Containerland
  content/en/docs/apim_howto_guides/apigw_in_containers.md
  static/samples/apimanagement/howto/docker/anm-dockerfile
  static/samples/apimanagement/howto/docker/gw-dockerfile
  static/samples/apimanagement/howto/docker/runInstall.sh
Labels: needs push to prod, size/S
