Repository Axway/axway-open-docs, pull requests merged in 2020-04, with the labels that each got.

#566 Update page in APIG/APIM 7.7 Mar20 release note section “_index”
  content/en/docs/apim_relnotes/20200330_apimgr_relnotes/_index.md
Labels: needs push to prod, size/XS

#548 RDAPI-19335 migrate 77 Apr2019 Release notes
  content/en/docs/apim_relnotes/201904_apimgr_relnotes/APIGatewayApr19_ReleaseNotes.md
  content/en/docs/apim_relnotes/201904_apimgr_relnotes/APIGatewayApr19_fixed_issues.md
  content/en/docs/apim_relnotes/201904_apimgr_relnotes/APIManagerApr19_ReleaseNotes.md
  content/en/docs/apim_relnotes/201904_apimgr_relnotes/APIManagerApr19_fixed_issues.md
  content/en/docs/apim_relnotes/201904_apimgr_relnotes/_index.md
  content/en/docs/apim_relnotes/201904_apip_relnotes/_index.md
  static/admin/config.js
Labels: size/XL

#569 change the order of 2019 RN to last
  content/en/docs/apim_relnotes/201904_apip_relnotes/_index.md
Labels: needs push to prod, size/XS

#560 MariaDB is only supported by the MySQL-Driver.
  content/en/docs/apim_installation/apigtw_install/metrics_db_install.md
  content/en/docs/apim_installation/apigtw_install/system_requirements.md
Labels: needs push to prod, size/XS

#570 Disable MD047 markdown rule
  .markdownlint.json
Labels: size/XS

#572 Fix formatting of routing_getstarted
  content/en/docs/apim_policydev/apigw_polref/routing_getstarted.md
Labels: size/XS

#573 Fix formatting of routing_common
  content/en/docs/apim_policydev/apigw_polref/routing_common.md
Labels: size/XS

#577 Fix formatting of routing_jms
  content/en/docs/apim_policydev/apigw_polref/routing_jms.md
Labels: size/XS

#578 Fix formatting of routing_additional
  content/en/docs/apim_policydev/apigw_polref/routing_additional.md
Labels: size/XS

#580 Fix formatting of attributes_manipulate
  content/en/docs/apim_policydev/apigw_polref/attributes_manipulate.md
Labels: size/XS

#581 Fix formatting of attributes_retrieve
  content/en/docs/apim_policydev/apigw_polref/attributes_retrieve.md
Labels: size/XS

#582 Fix formatting of authn_common
  content/en/docs/apim_policydev/apigw_polref/authn_common.md
Labels: size/XS

#583 Fix formatting of authn_additional
  content/en/docs/apim_policydev/apigw_polref/authn_additional.md
Labels: size/XS

#576 Added information how to login
  content/en/docs/apim_installation/apiportal_install/connect_to_apimgr.md
Labels: size/XS

#584 Fix formatting of authz_common
  content/en/docs/apim_policydev/apigw_polref/authz_common.md
Labels: size/XS

#586 Fix formatting of conversion_common
  content/en/docs/apim_policydev/apigw_polref/conversion_common.md
Labels: size/XS

#585 Fix formatting of authz_other
  content/en/docs/apim_policydev/apigw_polref/authz_other.md
Labels: size/XS

#587 Fix formatting of conversion_additional
  content/en/docs/apim_policydev/apigw_polref/conversion_additional.md
Labels: size/XS

#575 Update Hugo version to avail of new Blackfriday options
  config.toml
  content/en/docs/contribution_guidelines/maintain_customize.md
  content/en/docs/contribution_guidelines/setup_work_locally.md
  netlify.toml
Labels: size/M

#592 Fix formatting of content_common
  content/en/docs/apim_policydev/apigw_polref/content_common.md
Labels: size/XS

#593 Fix formatting of content_additional
  content/en/docs/apim_policydev/apigw_polref/content_additional.md
Labels: size/XS

#588 Fix formatting of content_max_messages
  content/en/docs/apim_policydev/apigw_polref/content_max_messages.md
Labels: size/XS

#594 Fix formatting of virus_scanning
  content/en/docs/apim_policydev/apigw_polref/virus_scanning.md
Labels: size/XS

#595 Update API Portal 7.7 March 2020 release Known Issues section
  content/en/docs/apim_relnotes/20200330_apip_relnotes/_index.md
Labels: needs push to prod, size/XS

#596 Fix formatting of cert_validation
  content/en/docs/apim_policydev/apigw_polref/cert_validation.md
Labels: size/XS

#597 Fix formatting of caching
  content/en/docs/apim_policydev/apigw_polref/caching.md
Labels: size/XS

#591 Add note on how users first land on a page
  content/en/docs/contribution_guidelines/bestpracticedevdoc.md
Labels: size/XS

#599 Revert "Add size-label to the tickets"
  .github/workflows/size-label.yml
Labels: size/XS

#601 Fix formatting of aws_filters
  content/en/docs/apim_policydev/apigw_polref/aws_filters.md
Labels: size/XS

#602 Fix formatting of monitoring_logging
  content/en/docs/apim_policydev/apigw_polref/monitoring_logging.md
Labels: size/XS

#600 Fix formatting of fault_filters
  content/en/docs/apim_policydev/apigw_polref/fault_filters.md
Labels: size/XS

#605 Fix formatting of encryption_xml
  content/en/docs/apim_policydev/apigw_polref/encryption_xml.md
Labels: size/XS

#603 Create labeler.yml
  .github/workflows/labeler.yml
Labels: size/S

#609 Fix formatting of wstrust_filters
  content/en/docs/apim_policydev/apigw_polref/wstrust_filters.md
Labels: size/XS

#607 Fix formatting of resolver_filters
  content/en/docs/apim_policydev/apigw_polref/resolver_filters.md
Labels: size/XS

#590 Update page in APIG containers section “container_patch_sp”
  content/en/docs/apim_installation/apigw_containers/container_patch_sp.md
Labels: needs push to prod, netlify-cms/pending_publish, size/S

#615 Fix formatting of connector_oes11g10g
  content/en/docs/apim_policydev/apigw_polref/connector_oes11g10g.md
Labels: size/XS

#614 Fix formatting of connector_oam
  content/en/docs/apim_policydev/apigw_polref/connector_oam.md
Labels: size/XS

#616 Fix formatting of api_mgr_ps_filters
  content/en/docs/apim_policydev/apigw_polref/api_mgr_ps_filters.md
Labels: size/XS

#571 Update property as its new value is now pvalue.
  content/en/docs/apim_administration/apigtw_admin/general_passphrase.md
Labels: needs push to prod, size/S

#618 Add AMPLIFY Unified Catalog to CMS
  static/admin/config.js
Labels: size/XS

#637 Add Unified Catalog to CMS
  static/admin/config.js
Labels: size/XS

#619 Create page in AMPLIFY Central section “connect-api-manager-overview”
  content/en/docs/central/connect-api-manager-overview.md
Labels: netlify-cms/pending_review, size/S

#620 Create page in AMPLIFY Central section “prepare-amplify-central”
  content/en/docs/central/prepare-amplify-central.md
Labels: netlify-cms/pending_review, size/M

#621 Create page in AMPLIFY Central section “deploy-your-agents”
  content/en/docs/central/deploy-your-agents.md
Labels: netlify-cms/pending_review, size/M

#622 Create page in AMPLIFY Central section “discovery-agent-variables”
  content/en/docs/central/discovery-agent-variables.md
Labels: netlify-cms/pending_review, size/S

#623 Create page in AMPLIFY Central section “discovery-agent-flags”
  content/en/docs/central/discovery-agent-flags.md
Labels: netlify-cms/draft, size/S

#624 Create page in AMPLIFY Central section “traceability-agent-variables”
  content/en/docs/central/traceability-agent-variables.md
Labels: netlify-cms/pending_review, size/S

#625 Create page in AMPLIFY Central section “traceability-agent-flags”
  content/en/docs/central/traceability-agent-flags.md
Labels: netlify-cms/pending_review, size/S

#626 Create page in AMPLIFY Central section “filtering-apis-to-be-discovered”
  content/en/docs/central/filtering-apis-to-be-discovered.md
Labels: netlify-cms/pending_review, size/S

#627 Create page in AMPLIFY Central section “ssl-tls-advanced”
  content/en/docs/central/ssl-tls-advanced.md
Labels: netlify-cms/pending_review, size/S

#628 Create page in AMPLIFY Central section “subscription-for-the-consumer”
  content/en/docs/central/subscription-for-the-consumer.md
Labels: netlify-cms/pending_review, size/S

#629 Create page in AMPLIFY Central section “tips-troubleshooting-and-limitations”
  content/en/docs/central/tips-troubleshooting-and-limitations.md
Labels: netlify-cms/pending_review, size/S

#630 Create page in AMPLIFY Central section “connect-aws-gateway”
  content/en/docs/central/add_env.md
  content/en/docs/central/build_hybrid_env.md
  content/en/docs/central/cft_profile.md
  content/en/docs/central/connect-aws-gateway/_index.md
  content/en/docs/central/hybrid_overview.md
Labels: netlify-cms/pending_review, size/S

#631 Create page in AMPLIFY Central section “prepare-amplify-central-1”
  content/en/docs/central/connect-aws-gateway/_index.md
  content/en/docs/central/connect-aws-gateway/prepare-amplify-central-1.md
Labels: netlify-cms/pending_review, size/S

#632 Create page in AMPLIFY Central section “prepare-aws-api-gateway”
  content/en/docs/central/connect-aws-gateway/prepare-amplify-central-1.md
  content/en/docs/central/connect-aws-gateway/prepare-aws-api-gateway.md
Labels: netlify-cms/pending_review, size/S

#633 Create page in AMPLIFY Central section “deploy-your-agents-1”
  content/en/docs/central/connect-api-manager/_index.md
  content/en/docs/central/connect-api-manager/deploy-your-agents.md
  content/en/docs/central/connect-api-manager/discovery-agent-flags.md
  content/en/docs/central/connect-api-manager/discovery-agent-variables.md
  content/en/docs/central/connect-api-manager/filtering-apis-to-be-discovered.md
  content/en/docs/central/connect-api-manager/prepare-amplify-central.md
  content/en/docs/central/connect-api-manager/ssl-tls-advanced.md
  content/en/docs/central/connect-api-manager/subscription-for-the-consumer.md
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
  content/en/docs/central/connect-api-manager/traceability-agent-flags.md
  content/en/docs/central/connect-api-manager/traceability-agent-variables.md
  content/en/docs/central/connect-aws-gateway/_index.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-1.md
Labels: netlify-cms/pending_review, size/M

#634 Create page in AMPLIFY Central section “filtering-apis-to-be-discovered-1”
  content/en/docs/central/connect-aws-gateway/filtering-apis-to-be-discovered-1.md
Labels: netlify-cms/draft, size/S

#635 Create page in AMPLIFY Central section “ssl-tls-advanced-1”
  content/en/docs/central/connect-aws-gateway/ssl-tls-advanced-1.md
Labels: netlify-cms/pending_review, size/S

#636 Create page in AMPLIFY Central section “tips-and-troubleshooting”
  content/en/docs/central/add_env.md
  content/en/docs/central/backend_TLS.md
  content/en/docs/central/backend_authn.md
  content/en/docs/central/build_hybrid_env.md
  content/en/docs/central/catalog/_index.md
  content/en/docs/central/cft_profile.md
  content/en/docs/central/cli_environments.md
  content/en/docs/central/cli_getstarted.md
  content/en/docs/central/cli_proxy_flow.md
  content/en/docs/central/connect-api-manager/_index.md
  content/en/docs/central/connect-api-manager/deploy-your-agents.md
  content/en/docs/central/connect-api-manager/filtering-apis-to-be-discovered.md
  content/en/docs/central/connect-api-manager/prepare-amplify-central.md
  content/en/docs/central/connect-api-manager/subscription-for-the-consumer.md
  content/en/docs/central/connect-aws-gateway/_index.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-1.md
  content/en/docs/central/connect-aws-gateway/tips-and-troubleshooting.md
  content/en/docs/central/feauth_oauth.md
  content/en/docs/central/fundamental_concepts.md
  content/en/docs/central/hybrid_overview.md
  content/en/docs/central/overview.md
  content/en/docs/central/proxy_rate_limit.md
  content/en/docs/central/quickstart.md
  content/en/docs/central/secure_api_jwt.md
  static/Images/central/ServiceDiscovery.png
  static/Images/central/ServiceDiscoveryAPIM.png
  static/Images/central/Traceabilityagent.png
Labels: netlify-cms/pending_review, size/M

#641 Update api_mgmt_register_web.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_register_web.md
Labels: needs push to prod, size/XS

#638 What is an Organization
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_admin.md
Labels: needs push to prod, size/XS

#617 Initial commit of Streams v2 documentation
  content/en/docs/_index.md
  content/en/docs/streams/_index.md
  content/en/docs/streams/concepts.md
  content/en/docs/streams/management-api.md
  content/en/docs/streams/publishers/_index.md
  content/en/docs/streams/publishers/publisher-http-poller.md
  content/en/docs/streams/publishers/publisher-http-post.md
  content/en/docs/streams/quickstart.md
  content/en/docs/streams/subscribers/_index.md
  content/en/docs/streams/subscribers/subscriber-sse.md
  content/en/docs/streams/subscribers/subscriber-webhook.md
  content/en/docs/streams/subscribers/subscribers-errors.md
  package-lock.json
  package.json
  static/Images/streams/streams-architecture-concepts.png
  static/admin/config.js
Labels: needs push to prod, size/S

#644 cleanup links
  content/en/docs/central/connect-api-manager/_index.md
  content/en/docs/central/connect-api-manager/deploy-your-agents.md
  content/en/docs/central/connect-api-manager/discovery-agent-flags.md
  content/en/docs/central/connect-api-manager/discovery-agent-variables.md
  content/en/docs/central/connect-api-manager/filtering-apis-to-be-discovered.md
  content/en/docs/central/connect-api-manager/prepare-amplify-central.md
  content/en/docs/central/connect-api-manager/ssl-tls-advanced.md
  content/en/docs/central/connect-api-manager/subscription-for-the-consumer.md
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
  content/en/docs/central/connect-api-manager/traceability-agent-flags.md
  content/en/docs/central/connect-api-manager/traceability-agent-variables.md
  content/en/docs/central/connect-aws-gateway/_index.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-1.md
  content/en/docs/central/connect-aws-gateway/filtering-apis-to-be-discovered-1.md
  content/en/docs/central/connect-aws-gateway/prepare-amplify-central-1.md
  content/en/docs/central/connect-aws-gateway/prepare-aws-api-gateway.md
  content/en/docs/central/connect-aws-gateway/ssl-tls-advanced-1.md
  content/en/docs/central/connect-aws-gateway/tips-and-troubleshooting.md
Labels: size/M

#598 Added the AMPLIFY Central roles
  content/en/docs/central/fundamental_concepts.md
Labels: size/XS

#645 Add Connect API Manager and AWS Gateway collections
  static/admin/config.js
Labels: size/S

#648 cleanup external links
  content/en/docs/central/connect-aws-gateway/_index.md
Labels: size/XS

#651 APIGOV-14637 CENTRAL_MODE
  content/en/docs/central/connect-api-manager/_index.md
  content/en/docs/central/connect-api-manager/deploy-your-agents.md
  content/en/docs/central/connect-api-manager/discovery-agent-flags.md
  content/en/docs/central/connect-api-manager/discovery-agent-variables.md
  content/en/docs/central/connect-aws-gateway/_index.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-1.md
Labels: size/S

#660 Create page in AMPLIFY Unified Catalog “overview”
  content/en/docs/central/catalog/_index.md
  content/en/docs/central/catalog/catalog_integrationbuilder.md
Labels: size/XS

#659 Update page in AMPLIFY Unified Catalog “catalog”
  content/en/docs/central/catalog/catalog.md
  content/en/docs/central/catalog/manage_subscriptions.md
Labels: size/S

#662 Rename IBM WebSphere MQ to IBM MQ
  content/en/docs/apim_policydev/apigw_poldev/general_messaging.md
Labels: needs push to prod, size/XS

#665 Update page in APIP install section “secure_harden_portal”
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
Labels: size/XS

#653 Create page in AMPLIFY Streams Publishers section “kafka-publisher”
  content/en/docs/streams/publishers/kafka-publisher.md
Labels: size/S

#669 Update page in AMPLIFY Streams Publishers section “kafka-publisher”
  content/en/docs/streams/publishers/kafka-publisher.md
Labels: size/XS

#668 Added note to make it clear what is used for the host header
  content/en/docs/apim_policydev/apigw_gw_instances/general_remote_hosts.md
Labels: size/XS

#674 Add full path to concepts and components collections
  static/admin/config.js
Labels: size/XS

#667 API-Management Alerts - Fixes and enhancements
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_alerts.md
Labels: needs push to prod, size/XS

#675 Update page in AMPLIFY Streams Subscribers section “subscriber-webhook”
  content/en/docs/streams/subscribers/subscriber-webhook.md
Labels: size/XS

#677 Fix formatting of general_relative_path
  content/en/docs/apim_policydev/apigw_gw_instances/general_relative_path.md
Labels: size/XS

#676 Fix formatting of general_services
  content/en/docs/apim_policydev/apigw_gw_instances/general_services.md
Labels: size/XS

#680 Fix formatting of general_virtual_hosts
  content/en/docs/apim_policydev/apigw_gw_instances/general_virtual_hosts.md
Labels: size/XS

#683 Fix formatting of general_smtp_services
  content/en/docs/apim_policydev/apigw_gw_instances/general_smtp_services.md
Labels: size/XS

#655 RDAPI-19337 API Portal Add Fixed issues to Release Notes page
  content/en/docs/apim_relnotes/201904_apimgr_relnotes/_index.md
  content/en/docs/apim_relnotes/201904_apip_relnotes/_index.md
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
  content/en/docs/apim_relnotes/20200130_apip_relnotes/_index.md
  content/en/docs/apim_relnotes/20200130_apip_relnotes/fixed_issues.md
  content/en/docs/apim_relnotes/20200330_apimgr_relnotes/_index.md
  content/en/docs/apim_relnotes/20200330_apip_relnotes/_index.md
  content/en/docs/apim_relnotes/20200330_apip_relnotes/fixed_issues.md
  content/en/docs/apim_relnotes/20200530_apimgr_relnotes/_index.md
  content/en/docs/apim_relnotes/20200530_apip_relnotes/_index.md
  content/en/docs/apim_relnotes/20200530_apip_relnotes/fixed_issues.md
  content/en/docs/apim_relnotes/_index.md
Labels: size/M

#688 RDAPI-19337 API Gateway Add Fixed issues to Release Notes page
  content/en/docs/apim_relnotes/201904_apip_relnotes/_index.md
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/fixed_issues.md
  content/en/docs/apim_relnotes/20200330_apimgr_relnotes/_index.md
  content/en/docs/apim_relnotes/20200330_apimgr_relnotes/fixed_issues.md
  content/en/docs/apim_relnotes/20200530_apimgr_relnotes/_index.md
  content/en/docs/apim_relnotes/20200530_apimgr_relnotes/fixed_issues.md
Labels: size/M
