Repository Axway/axway-open-docs, pull requests merged in 2020-03, with the labels that each got.

#460 Add more use cases to contrib guidelines
  content/en/docs/contribution_guidelines/_index.md
  static/Images/contributing/netlify_createNewPage.png
  static/Images/contributing/netlify_workflowButton.png
Labels: Size: 1

#461 Configure Two-Way-SSL in API-Manager - Details
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_virtualize_web.md
Labels: Size: 1, needs push to prod

#479 APIG install section “system_requirements” missing for Linux
  content/en/docs/apim_installation/apigtw_install/system_requirements.md
Labels: Size: 1, needs push to prod

#473 Add markdownlint to CI
  .github/workflows/ciworkflow.yml
Labels: Size: 1

#478 Delete .travis.yml
  .travis.yml
Labels: Size: 1

#480 RDAPI-16062 Update page in pol filter ref section “utility_common”
  content/en/docs/apim_policydev/apigw_polref/utility_common.md
Labels: Size: 1, needs push to prod

#475 RDAPI-18697: improve markdown style guide
  content/en/blog/_index.md
  content/en/docs/apigtw_devguide/_index.md
  content/en/docs/apim_administration/apigtw_admin/admin_redactors.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_register_web.md
  content/en/docs/apim_administration/apimgr_sso/c_saml_trouble.md
  content/en/docs/apim_administration/apiportal_admin/customize_getting_started.md
  content/en/docs/apim_installation/apiportal_docker/_index.md
  content/en/docs/apim_installation/apiportal_docker/docker_config.md
  content/en/docs/apim_installation/apiportal_docker/docker_troubleshoot.md
  content/en/docs/apim_installation/apiportal_install/install_software_redis.md
  content/en/docs/apim_policydev/apigw_gw_instances/general_services.md
  content/en/docs/apim_policydev/apigw_gw_instances/general_virtual_hosts.md
  content/en/docs/apim_policydev/apigw_polref/attributes_manipulate.md
  content/en/docs/apim_policydev/apigw_web_services/register_rest_apis.md
  content/en/docs/apim_reference/api_mgmt_responses.md
  content/en/docs/apim_relnotes/20200130_apip_relnotes/_index.md
  content/en/docs/apimanager_capacityguide/performance_test_scenarios_singlenode.md
  content/en/docs/central/catalog/catalog_integrationbuilder.md
  content/en/docs/central/cli_proxy_flow.md
  content/en/docs/central/feauth_oauth.md
  content/en/docs/contribution_guidelines/writing_markdown.md
Labels: needs push to prod

#488 Update "Register an API" video in "Get started with AMPLIFY Central" page
  content/en/docs/central/quickstart.md
Labels: Size: 1

#495 Added an entry to the SSO troubleshooting section from issue encountered
  content/en/docs/apim_administration/apimgr_sso/c_saml_trouble.md
Labels: Size: 1, needs push to prod

#491 Release Note (Jan) - Install command examples use SP2 which is confusing for One Version Update
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
Labels: Size: 1, needs push to prod

#493 Add size-label to the tickets
  .github/workflows/size-label.yml
Labels: size/S

#490 Add PR template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: Size: 1

#492 Release Note (March) - Install command examples use SP2 which is confusing for One Version Update
  content/en/docs/apim_relnotes/20200330_apimgr_relnotes/_index.md
Labels: Size: 1, needs push to prod

#501 Rename .github/PULL_REQUEST_TEMPLATE/pull_request_template.md to .git…
  .github/pull_request_template.md
Labels: size/XS

#503 Update minimist dependency
  package-lock.json
  package.json
Labels: size/S

#502 Add FAQ for Kubernetes with link to Helm charts
  content/en/docs/apim_installation/apigw_containers/container_getstarted.md
Labels: needs push to prod, size/XS

#507 Revert "Add conflict-label to the tickets"
  .github/workflows/conflict-label.yml
Labels: size/S

#504 Update page in APIP admin section “customize_APICatalog_overview”
  content/en/docs/apim_administration/apiportal_admin/customize_APICatalog_overview.md
  static/Images/APIPortal/api-manager-try-it-settings.png
  static/Images/APIPortal/apiportal-jai-customize-api-catalog.png
Labels: Size: 1

#508 Update Release Notes title
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
  content/en/docs/apim_relnotes/20200130_apip_relnotes/_index.md
  content/en/docs/apim_relnotes/20200330_apimgr_relnotes/_index.md
  content/en/docs/apim_relnotes/20200330_apip_relnotes/_index.md
Labels: needs push to prod, size/XS

#506 Update page in API Portal 7.7 Mar20 release note section “_index”
  content/en/docs/apim_relnotes/20200330_apip_relnotes/_index.md
Labels: Size: 1, needs push to prod

#509 Update page in API Portal 7.7 Mar20 release note section “fixed_issues”
  content/en/docs/apim_relnotes/20200330_apip_relnotes/fixed_issues.md
Labels: Size: 1, needs push to prod

#511 API Portal 7.7 Mar20 release note section “fixed_issues” writer review
  content/en/docs/apim_relnotes/20200330_apip_relnotes/fixed_issues.md
Labels: netlify-cms/pending_review, size/S

#515 RDAPI-19133 Remove embedded results and link to results on Support
  content/en/docs/apimanager_capacityguide/performance_test_results.md
Labels: needs push to prod, size/L

#516 Update page in APIP install section “upgrade_automatic”
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
Labels: needs push to prod, size/S

#517 Update Update New features and enhancements in API Portal 7.7 Mar20 release note
  content/en/docs/apim_relnotes/20200330_apip_relnotes/_index.md
Labels: size/XS

#518 Update page in API Portal 7.7 Jan20 release note section “_index”
  content/en/docs/apim_relnotes/20200130_apip_relnotes/_index.md
Labels: size/XS

#519 Update pull_request_template.md
  .github/pull_request_template.md
Labels: size/XS

#514 APIGOV-14293 Update Add Environment Documentation
  content/en/docs/central/add_env.md
  content/en/docs/central/build_hybrid_env.md
  conversion_outputs/userdocs/build_hybrid_env.md
  conversion_outputs/userdocs/hybrid_home.md
  static/Images/central/add_env_animation.gif
  static/Images/central/add_env_page.png
  static/Images/central/add_k8s_success_modal.png
  static/Images/central/add_v7_success_modal.png
  static/Images/central/completed_k8s_form.png
  static/Images/central/completed_v7_form.png
  static/Images/central/environments_list_page.png
Labels: size/S

#520 Update page in APIP install section “install_software_prereqs”
  content/en/docs/apim_installation/apiportal_install/install_software_prereqs.md
Labels: needs push to prod, size/XS

#510 Axway Support Portal API - initial.
  content/en/_index.html
  content/en/docs/_index.md
  content/en/docs/shared_services/_index.md
  content/en/docs/shared_services/supportapi/_index.md
  content/en/docs/shared_services/supportapi/formats/_index.md
  content/en/docs/shared_services/supportapi/formats/add_note_req.md
  content/en/docs/shared_services/supportapi/formats/add_note_res.md
  content/en/docs/shared_services/supportapi/formats/case_type.md
  content/en/docs/shared_services/supportapi/formats/close_case_req.md
  content/en/docs/shared_services/supportapi/formats/close_case_res.md
  content/en/docs/shared_services/supportapi/formats/create_case_req.md
  content/en/docs/shared_services/supportapi/formats/create_case_res.md
  content/en/docs/shared_services/supportapi/formats/environment.md
  content/en/docs/shared_services/supportapi/formats/error_response.md
  content/en/docs/shared_services/supportapi/formats/get_accounts_res.md
  content/en/docs/shared_services/supportapi/formats/get_case_res.md
  content/en/docs/shared_services/supportapi/formats/get_products_res.md
  content/en/docs/shared_services/supportapi/formats/impact.md
  content/en/docs/shared_services/supportapi/formats/list_cases_req.md
  content/en/docs/shared_services/supportapi/formats/list_cases_res.md
  content/en/docs/shared_services/supportapi/formats/miscellaneous.md
  content/en/docs/shared_services/supportapi/formats/severity.md
  content/en/docs/shared_services/supportapi/formats/urgency.md
  content/en/docs/shared_services/supportapi/methods/_index.md
  content/en/docs/shared_services/supportapi/methods/add_note.md
  content/en/docs/shared_services/supportapi/methods/close_case.md
  content/en/docs/shared_services/supportapi/methods/create_case.md
  content/en/docs/shared_services/supportapi/methods/download_attachment.md
  content/en/docs/shared_services/supportapi/methods/get_accounts.md
  content/en/docs/shared_services/supportapi/methods/get_case.md
  content/en/docs/shared_services/supportapi/methods/get_products.md
  content/en/docs/shared_services/supportapi/methods/list_cases.md
  static/admin/config.js
Labels: needs push to prod, size/M

#527 RDAPI-19315 FIPS update
  content/en/docs/apim_administration/apigtw_admin/admin_fips.md
  content/en/docs/apim_relnotes/20200330_apimgr_relnotes/_index.md
  content/en/docs/apim_relnotes/20200330_apip_relnotes/_index.md
Labels: needs push to prod, size/S

#505 Best practices for developer docs
  .github/pull_request_template.md
  content/en/docs/contribution_guidelines/bestpracticedevdoc.md
Labels: size/L

#525 Update page in API Portal 7.7 Mar20 release note section “fixed_issues”
  content/en/docs/apim_relnotes/20200330_apip_relnotes/fixed_issues.md
Labels: needs push to prod, size/XS

#529 [Shared Services] Remove link from linkTitle and add it to the body
  content/en/docs/shared_services/supportapi/_index.md
Labels: size/XS

#528 Improve the start page
  content/en/docs/_index.md
Labels: needs push to prod, size/M

#533 IAP-3099 Update page in API Portal 7.7 Mar20 release note
  content/en/docs/apim_relnotes/20200330_apip_relnotes/_index.md
Labels: size/XS

#538 IAP-3147 Update page in APIP admin section “customize_APICatalog_overview”
  content/en/docs/apim_administration/apiportal_admin/customize_APICatalog_overview.md
  static/Images/APIPortal/apiportal-jai-customize-api-catalog.png
Labels: size/XS

#539 Location of the server key and certificate fixed
  content/en/docs/apim_installation/apiportal_docker/docker_troubleshoot.md
Labels: needs push to prod, size/XS

#541 [RDAPI-18860] XML Sign filter has undocumented "Include Transforms" option
  content/en/docs/apim_policydev/apigw_polref/integrity_xml.md
Labels: needs push to prod, size/XS

#534 Cms/ygeorgiev axway/axway open docs/apiportal admin/public api configure
  content/en/docs/apim_administration/apiportal_admin/public_api_configure.md
Labels: needs push to prod, size/XS

#545 Enable API Gateway with JMX Fix ordered list of steps
  content/en/docs/apigtw_devguide/jmx_enable.md
Labels: size/XS

#537 Add some tips for working on Ubuntu
  content/en/docs/contribution_guidelines/setup_work_locally.md
Labels: size/M

#549 Update page in API Portal 7.7 Mar20 release note section “_index”
  content/en/docs/apim_relnotes/20200330_apip_relnotes/_index.md
Labels: size/XS

#551 Update page in APIG/APIM 7.7 Mar20 release note section “fixed_issues”
  content/en/docs/apim_relnotes/20200330_apimgr_relnotes/fixed_issues.md
Labels: needs push to prod, size/XS

#552 Update page in APIG/APIM 7.7 Mar20 release note section “_index”
  content/en/docs/apim_relnotes/20200330_apimgr_relnotes/_index.md
Labels: needs push to prod, size/S

#555 Update page in APIG/APIM 7.7 Mar20 release note section “_index”
  content/en/docs/apim_relnotes/20200330_apimgr_relnotes/_index.md
Labels: needs push to prod, size/XS

#553 Update page in APIP install section “upgrade_automatic”
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
Labels: size/XS

#554 Update page in API Portal 7.7 Mar20 release note section “_index”
  content/en/docs/apim_relnotes/20200330_apip_relnotes/_index.md
Labels: size/S

#561 Update page in APIG/APIM 7.7 Mar20 release note section “_index”
  .markdownlint.json
  content/en/docs/apim_relnotes/20200330_apimgr_relnotes/_index.md
Labels: needs push to prod, size/XS

#562 Update page in APIG/APIM 7.7 Jan20 release note section “_index”
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
Labels: needs push to prod, size/XS

#563 Update page in API Portal 7.7 Jan20 release note section “_index”
  content/en/docs/apim_relnotes/20200130_apip_relnotes/_index.md
Labels: needs push to prod, size/XS

#559 Update page in API Portal 7.7 Mar20 release note section “_index”
  content/en/docs/apim_relnotes/20200330_apip_relnotes/_index.md
Labels: needs push to prod, size/XS
