Repository Axway/axway-open-docs, pull requests merged in 2020-11, with the labels that each got.

#1368 Update page in Connect API Manager “deploy-your-agents-with-amplify-cli”
  content/en/docs/central/connect-api-manager/deploy-your-agents-with-amplify-cli.md
Labels: netlify-cms/pending_review, size/S

#1373 RMF-30 bad link in Update page in Connect AWS Gateway “subscription-for-the-consumer”
  content/en/docs/central/connect-aws-gateway/subscription-for-the-consumer.md
Labels: netlify-cms/pending_review, size/XS

#1371 RMF-30 bad link in Update page in Connect API Manager “deploy-your-agents”
  content/en/docs/central/connect-api-manager/deploy-your-agents.md
Labels: netlify-cms/pending_review, size/XS

#1370 RMF-30 bad link in Update page in Connect API Manager “deploy-your-agents-with-amplify-cli”
  content/en/docs/central/connect-api-manager/deploy-your-agents-with-amplify-cli.md
Labels: netlify-cms/pending_review, size/XS

#1372 RMF-30 bad link in Connect API Manager “gateway-administation”
  content/en/docs/central/connect-api-manager/gateway-administation.md
Labels: netlify-cms/pending_review, size/XS

#1376 APIGOV-16528 - Add EU support to “deploy-your-agents-with-amplify-cli”
  content/en/docs/central/connect-api-manager/deploy-your-agents-with-amplify-cli.md
Labels: netlify-cms/draft, size/S

#1377 APIGOV-16528 - add EU support in Connect AWS Gateway “deploy-your-agents-with-amplify-cli”
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-with-amplify-cli.md
Labels: netlify-cms/draft, size/XS

#1289 RDAPI-20971 Created new system props doc
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
  content/en/docs/apim_reference/system_props.md
Labels: more info needed, needs push to prod

#1379 Manually merge master into develop to fix conflict created by PR#1289
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
  content/en/docs/apim_reference/system_props.md
Labels: size/M

#1381 RDAPI-21807 Fix broken link on API Gateway upgrade page
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
Labels: size/XS

#1382 Manually merge master into develop to fix conflict
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
Labels: size/XS

#1349 Update page in APIM admin section “api_mgmt_consume”
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_consume.md
Labels: needs push to prod, size/XS

#1384 Broken image on Zoomin site. Remove space from image name
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
  static/Images/UpgradeGuide/APIgw_single_node_upgrade_topology.png
Labels: size/XS

#1385 Remove space from image name - complements #1384
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
  static/Images/UpgradeGuide/APIgw_upgrade_topology.png
Labels: size/XS

#1386 Fix conflic t20201105
  static/Images/UpgradeGuide/APIgw_upgrade_topology.png
Labels: size/XS

#1388 Create Nov 20 Release note pages into develop branch
  content/en/docs/apim_relnotes/20201130_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20201130_apip_relnotes.md
Labels: size/L

#1394 Update page System property changes page via CMS to get rid of CMS diffs at once
  content/en/docs/apim_reference/system_props.md
Labels: size/XS

#1395 Manually merge master into develop
  content/en/docs/apim_reference/system_props.md
Labels: size/XS

#1391 Update page in APIG admin section “general_certificates”
  content/en/docs/apim_administration/apigtw_admin/general_certificates.md
Labels: needs push to prod, size/XS

#1396 Merge by andrea
  content/en/docs/apim_administration/apigtw_admin/general_certificates.md
Labels: size/S

#1390 APIGOV-16783 - Update subscription documentation
  content/en/docs/central/connect-api-manager/subscription-for-the-consumer.md
Labels: netlify-cms/draft, size/S

#1392 APIGOV - 16783 - Update AWS subscription documentation
  content/en/docs/central/connect-aws-gateway/subscription-for-the-consumer.md
Labels: netlify-cms/draft, size/M

#1358 [RDAPI-21834] docs for supporting converting an XML config fragment to YAML
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_conversion_errors.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
  content/en/docs/apim_yamles/yamles_cli.md
  content/en/docs/apim_yamles/yamles_structure.md
Labels: size/S

#1351 RDAPI-22173 - Added more information on OrgAdmin selfservice capabilities
  content/en/docs/api_mgmt_overview/key_concepts/api_mgmt_orgs_roles.md
Labels: needs push to prod, size/XS

#1357 [IAP-2555] - Update page in APIP install section “secure_harden_portal”
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
Labels: size/XS

#1362 Update page in Mesh management “_index”
  content/en/docs/central/mesh_management/_index.md
Labels: needs push to prod, size/XS

#1363 Update 'open_logging_schema' to fix markdown formatting
  content/en/docs/apim_reference/open_logging_schema.md
Labels: size/XS

#1375 Windows section - Developer tools instead of API-Gateway
  content/en/docs/apim_installation/apigtw_install/system_requirements.md
Labels: needs push to prod, size/XS

#1407 Developer tools, Package and Deployment - small changes to improve readability
  content/en/docs/apigtw_devops/deploy_package_tools.md
  content/en/docs/apim_installation/apigtw_install/install_dev_tools.md
  content/en/docs/apim_installation/apigtw_install/system_requirements.md
Labels: size/S

#1364 IAP-3616 - Remove 'Customize application sharing settings' section
  content/en/docs/apim_administration/apiportal_admin/customize_page_content.md
Labels: size/S

#1410 RDAPI-22318 Update package-lock.json to fix yargs-parser security vulnerability
  package-lock.json
  package.json
Labels: size/XS

#1383 Update Helm version on Build your hybrid environment
  content/en/docs/central/mesh_management/build_hybrid_env.md
Labels: needs push to prod, size/XS

#1399 Update build_hybrid_env.md
  content/en/docs/central/mesh_management/build_hybrid_env.md
Labels: size/XS

#1415 Update page in Connect API Manager “network-traffic-apimanager”
  content/en/docs/central/connect-api-manager/network-traffic-apimanager.md
Labels: netlify-cms/pending_publish, size/XS

#1417 Update release 20200930 Run update-apimanager script to upgrade API Manager
  content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
Labels: needs push to prod, size/XS

#1414 [IAP-3652] - Update page in APIP install section “secure_harden_portal”
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
Labels: size/XS

#1404 IAP-1956 Create page in APIP admin section “logging”
  content/en/docs/apim_administration/apiportal_admin/apip_logging.md
Labels: more info needed

#1406 RDAPI-18238 Add Uninstalling section
  content/en/docs/apim_installation/apigtw_install/installation.md
Labels: more info needed, needs push to prod, size/XS

#1418 Create section “zero-downtime-api-updates”
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_virtualize_web.md
  static/Images/APIGateway/both_published.png
  static/Images/APIGateway/grant_api_access.png
  static/Images/APIGateway/only_v1.0_api.png
Labels: more info needed, size/XS

#1408 [RDAPI-22228] Improvements to API Gateway configuration files document
  content/en/docs/apim_reference/config_files_reference.md
Labels: needs push to prod, size/XS

#1409 Update page in APIM concepts section “api_mgmt_orgs_roles”
  content/en/docs/api_mgmt_overview/key_concepts/api_mgmt_orgs_roles.md
Labels: needs push to prod, size/XS

#1419 RDAPI-20218 Add two new properties to promotion.properties file
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_promote.md
Labels: more info needed, needs push to prod, size/XS

#1425 IAP-3628 Update release note section 20201130
  content/en/docs/apim_relnotes/20201130_apip_relnotes.md
Labels: size/XS

#1416 APIGOV-16487 Create page in Mesh management “discover-apis-and-services”
  content/en/docs/central/mesh_management/discover-apis-and-services.md
Labels: more info needed

#1436 IAP-3707 Update page in APIP install section “upgrade_automatic”
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
Labels: size/XS

#1411 [RDAPI-20544] Update the docs for YAML CLI import and export options and restructure the CLI section a bit.
  content/en/docs/apim_yamles/apim_yamles_cli/_index.md
  content/en/docs/apim_yamles/apim_yamles_cli/yamles_cli_convert.md
  content/en/docs/apim_yamles/apim_yamles_cli/yamles_cli_encryption.md
  content/en/docs/apim_yamles/apim_yamles_cli/yamles_cli_importexport.md
  content/en/docs/apim_yamles/apim_yamles_cli/yamles_cli_validate.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_team_development.md
  content/en/docs/apim_yamles/yamles_cli.md
  content/en/docs/apim_yamles/yamles_edit.md
  content/en/docs/apim_yamles/yamles_quick_start.md
Labels: size/S

#1421 [RDAPI-21986] Update Docs with steps to migrate Analytics data
  content/en/docs/apim_installation/apigw_upgrade/upgrade_analytics.md
Labels: size/XS

#1450 Fix typo in YAML es docs
  content/en/docs/apim_yamles/apim_yamles_cli/yamles_cli_encryption.md
Labels: size/XS

#1441 Update page in APIM release note section “20201130_apip_relnotes”
  content/en/docs/apim_relnotes/20201130_apip_relnotes.md
  static/Images/docbook/images/release_notes/docker-logo.png
  static/Images/docbook/images/release_notes/red-hat-logo.png
  static/Images/docbook/images/release_notes/show-hide-by-status.png
  static/Images/docbook/images/release_notes/sort-by-newest.png
Labels: more info needed, size/XS

#1435 Double-Quotes only once for PASSPHRASE-EXEC-Script
  content/en/docs/apim_administration/apigtw_admin/general_certificates.md
Labels: needs push to prod, size/XS

#1451 Openid verify details
  content/en/docs/apim_policydev/apigw_oauth/oauth_openid_filters.md
Labels: needs push to prod, size/XS

#1431 IAP-3685: temporarily hide pages for the upcoming release
  content/en/docs/apim_installation/apiportal_docker/Upgrade_docker.md
  content/en/docs/apim_installation/apiportal_docker/docker_config.md
  content/en/docs/apim_installation/apiportal_docker/docker_portal_deploy.md
Labels: size/XS

#1454 IAP-3685: more updates to Run API Portal using Docker image
  content/en/docs/apim_installation/apiportal_docker/_index.md
  content/en/docs/apim_installation/apiportal_docker/docker_portal_run_image.md
Labels: size/XS

#1433 RDAPI-21725 update documentation on yamles externalization files
  content/en/docs/apim_yamles/yamles_externalized_files.md
Labels: more info needed

#1448 Adding section Enhanced API Lifecycle Management for Organization Adm…
  content/en/docs/apim_relnotes/20201130_apimgr_relnotes.md
Labels: more info needed, size/XS

#1452 Update page in APIM release note section “20201130_apimgr_relnotes”
  content/en/docs/apim_relnotes/20201130_apimgr_relnotes.md
Labels: size/XS

#1430 RDAPI-21101 Release change log updates
  content/en/docs/apim_reference/allReleasesChangeLog.md
Labels: more info needed, needs push to prod, size/XS

#1423 APIGOV-16745 updating cli docs
  content/en/docs/central/cli_central/cli_install.md
Labels: needs push to prod, size/XS

#1446 Update page in APIM ref section “allReleasesChangeLog”
  content/en/docs/apim_reference/allReleasesChangeLog.md
Labels: size/XS

#1458 Fixing a typo
  content/en/docs/apim_administration/apiportal_admin/apip_logging.md
Labels: size/XS

#1437 Update command placeholder on step 6 To configure the SE Linux
  content/en/docs/apim_installation/apiportal_install/install_software.md
Labels: size/XS

#1453 One version tar command wrong
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
Labels: size/XS

#1456 RDAPI-21436 New system property to configure non-blocking load of API Manager APIs
  content/en/docs/apim_reference/system_props.md
Labels: needs push to prod, size/XS

#1459 RDAPI-22303 Update 20201130_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20201130_apimgr_relnotes.md
Labels: size/XS

#1460 [RDAPI-22303] Update APIM release note 20201130 with fixed issues
  content/en/docs/apim_relnotes/20201130_apimgr_relnotes.md
Labels: size/XS

#1447 RDAPI-22313 Update page in APIM ref section “system_props”
  content/en/docs/apim_reference/system_props.md
Labels: more info needed, size/XS

#1457 RDAPI-22303 Update 20201130 release Enhanced API life cycle mng for Org adms
  content/en/docs/apim_relnotes/20201130_apimgr_relnotes.md
Labels: size/XS

#1445 Create page in AMPLIFY Unified Catalog “unified-catalog-november-2020-release-notes”
  content/en/docs/catalog/unified-catalog-november-2020-release-notes.md
Labels: netlify-cms/pending_review, size/S

#1432 Create page in AMPLIFY Release notes section “amplify-central-november-2020-release-notes”
  content/en/docs/central/amplify_relnotes/amplify-central-november-2020-release-notes.md
Labels: netlify-cms/draft, size/S

#1462 Some final tweaks to YAML doc for nov release - update team dev section
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_team_development.md
  content/en/docs/apim_yamles/yamles_environmentalization.md
Labels: size/XS

#1463 API Manager and Portal Nov 20 Release notes final review
  content/en/docs/apim_relnotes/20201130_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20201130_apip_relnotes.md
Labels: size/XL

#1464 7.7 November 20 Merge Develop branch into master
  content/en/docs/apim_administration/apiportal_admin/apip_logging.md
  content/en/docs/apim_administration/apiportal_admin/customize_APICatalog_overview.md
  content/en/docs/apim_administration/apiportal_admin/customize_page_content.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_analytics.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
  content/en/docs/apim_installation/apiportal_docker/Upgrade_docker.md
  content/en/docs/apim_installation/apiportal_docker/_index.md
  content/en/docs/apim_installation/apiportal_docker/docker_config.md
  content/en/docs/apim_installation/apiportal_docker/docker_portal_deploy.md
  content/en/docs/apim_installation/apiportal_docker/docker_portal_run_image.md
  content/en/docs/apim_installation/apiportal_docker/docker_troubleshoot.md
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
  content/en/docs/apim_relnotes/20201130_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20201130_apip_relnotes.md
  content/en/docs/apim_yamles/apim_yamles_cli/_index.md
  content/en/docs/apim_yamles/apim_yamles_cli/yamles_cli_convert.md
  content/en/docs/apim_yamles/apim_yamles_cli/yamles_cli_encryption.md
  content/en/docs/apim_yamles/apim_yamles_cli/yamles_cli_importexport.md
  content/en/docs/apim_yamles/apim_yamles_cli/yamles_cli_validate.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_conversion_errors.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_team_development.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
  content/en/docs/apim_yamles/yamles_cli.md
  content/en/docs/apim_yamles/yamles_edit.md
  content/en/docs/apim_yamles/yamles_environmentalization.md
  content/en/docs/apim_yamles/yamles_externalized_files.md
  content/en/docs/apim_yamles/yamles_quick_start.md
  content/en/docs/apim_yamles/yamles_structure.md
  static/Images/APIPortal/api-catalog.png
  static/Images/UpgradeGuide/APIgw_upgrade_multinode_topology.png
  static/Images/docbook/images/release_notes/docker-logo.png
  static/Images/docbook/images/release_notes/red-hat-logo.png
  static/Images/docbook/images/release_notes/show-hide-by-status.png
  static/Images/docbook/images/release_notes/sort-by-newest.png
Labels: size/XL

#1466 APIGOV-16798 - traceability agent configuration for bulking event
  content/en/docs/central/connect-api-manager/gateway-administation.md
Labels: netlify-cms/draft, size/S
