Repository Axway/axway-open-docs, pull requests merged in 2020-12, with the labels that each got.

#1467 Fix typo to fix zoomin FTP
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
Labels: size/XS

#1473 Update page in Connect AWS Gateway “deploy-your-agents-with-amplify-cli”
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-with-amplify-cli.md
Labels: netlify-cms/pending_review, size/M

#1475 RMF-72 Configure Jan21 develop branch for API Management release
  .github/workflows/ciworkflow.yml
  .github/workflows/merge_to_develop.yml
  layouts/partials/page-meta-links.html
  netlify.toml
  static/admin/config.js
Labels: size/S

#1477 Update context tag
  netlify.toml
Labels: size/XS

#1483 RMF-72 Configure Jan21 develop branch - continue
  .github/workflows/ciworkflow.yml
  .github/workflows/merge_to_develop.yml
  layouts/partials/page-meta-links.html
  netlify.toml
  static/admin/config.js
Labels: size/S

#1485 APIGOV15487 - Improve Connect API Manager / deploy your agent using AMPLIFY CLI
  content/en/docs/central/connect-api-manager/deploy-your-agents-with-amplify-cli.md
Labels: netlify-cms/pending_review, size/M

#1438 APIGOV-16129: Update Environment docs
  content/en/docs/central/env_gw_mgmt.md
  static/Images/central/env_and_gateway_mgmt/EnvironmentDetailsPage.png
  static/Images/central/env_and_gateway_mgmt/ServiceDetailsPage.png
Labels: more info needed, needs push to prod, size/S

#1487 RMF-74 Update pull request template
  .github/pull_request_template.md
Labels: size/S

#1491 [RDAPI-22397] update ext file table
  content/en/docs/apim_yamles/yamles_externalized_files.md
Labels: size/S

#1486 Update KPS table structure section
  content/en/docs/apim_policydev/apigw_kps/kps_configuration.md
Labels: more info needed, needs push to prod, size/S

#1444 APIGOV-16488 Create page in Mesh management “deploy-your-agents-with-the-amplify-cli”
  content/en/docs/central/mesh_management/deploy-your-agents-with-the-amplify-cli.md
  content/en/docs/central/mesh_management/discover-apis-and-services.md
Labels: more info needed, needs push to prod, size/M

#1499 RMF-30 Fix broken links in APIM
  content/en/docs/apim_howto_guides/apigw_mqclient_tlssetup.md
  content/en/docs/apim_installation/apigtw_install/installation.md
  content/en/docs/apim_installation/apigw_upgrade/_index.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_overview.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_zdu_overview.md
  content/en/docs/apim_installation/apiportal_install/connect_to_apimgr.md
  content/en/docs/apim_reference/scripts_changelog_sp.md
  content/en/docs/apim_relnotes/20200730_apip_relnotes.md
  content/en/docs/apim_yamles/yamles_environmentalization.md
  content/en/docs/apim_yamles/yamles_quick_start.md
  content/en/docs/apimgmt_security/c_secgd_config_secarch.md
  content/en/docs/central/cli_central/cli_apiservices.md
  content/en/docs/central/cli_central/cli_environments.md
  static/Images/UpgradeGuide/APIgw_upgrade_overview.png
Labels: size/S

#1492 Update Metrics Database information for the Test Connection button
  content/en/docs/apimanager_analytics/metrics_gw_config.md
Labels: size/S

#1493 Update page in external connections section “common_db_conf”
  content/en/docs/apim_policydev/apigw_external_connections/common_db_conf.md
  content/en/docs/apimanager_analytics/metrics_gw_config.md
Labels: size/S

#1498 [RDAPI-21798] Add few words about Policy filter ordering
  content/en/docs/apim_yamles/yamles_structure.md
Labels: size/S

#1500 Remove Cumulative script announcement for July release , since new one was released and this one was removed from webliv
  content/en/docs/apim_relnotes/20200730_apip_relnotes.md
Labels: more info needed, needs push to prod, size/S

#1513 Fix links in Update page in Connect API Manager “tips-troubleshooting-and-limitations”
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
Labels: netlify-cms/pending_review, size/M

#1514 RMF-78 Fix broken links to samples in the CLI docs
  content/en/docs/central/cli_central/cli_environments.md
  content/en/docs/central/integrate_with_webhooks.md
Labels: size/XS

#1502 IAP-3771 Remove documentation related to logs and move it to Supported log files
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
Labels: needs push to prod, size/S

#1506 Add details about `log_bin_trust_function_creators` in DB server
  content/en/docs/apim_installation/apiportal_install/install_software_configure_database.md
Labels: size/S

#1503 IAP-3771 Added reference to Supported log files
  content/en/docs/apim_administration/apiportal_admin/troubleshooting.md
Labels: size/XS

#1504 IAP-3771 Added new sections and references Remove related to logs
  content/en/docs/apim_administration/apiportal_admin/apip_logging.md
Labels: size/XS

#1507 IAP-3173 Update page in APIP install section “secure_harden_portal”
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
Labels: more info needed

#1501 [RDAPI-22335] Update cassandra backup/restore to include new apigw-backup-tool usage
  content/en/docs/cass_admin/cassandra_bur.md
Labels: more info needed, size/S

#1516 APIGOV-17068 Reorg Connect APImanager
  content/en/docs/central/connect-api-manager/Agent-security-api-manager.md
  content/en/docs/central/connect-api-manager/_index.md
  content/en/docs/central/connect-api-manager/agent-variables.md
  content/en/docs/central/connect-api-manager/deploy-your-agents-quickstart.md
  content/en/docs/central/connect-api-manager/deploy-your-agents-with-amplify-cli.md
  content/en/docs/central/connect-api-manager/deploy-your-agents.md
  content/en/docs/central/connect-api-manager/discovery-agent-flags.md
  content/en/docs/central/connect-api-manager/filtering-apis-to-be-discovered.md
  content/en/docs/central/connect-api-manager/gateway-administation.md
  content/en/docs/central/connect-api-manager/impact-of-unpublishing-an-api.md
  content/en/docs/central/connect-api-manager/network-traffic-apimanager.md
  content/en/docs/central/connect-api-manager/prepare-amplify-central.md
  content/en/docs/central/connect-api-manager/subscription-for-the-consumer.md
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
Labels: size/M

#1519 Update page in Connect API Manager “_index”
  content/en/docs/central/connect-api-manager/_index.md
Labels: netlify-cms/pending_review, size/S

#1508 RDAPI-22426 YAMLES has a more strict e18n syntax
  content/en/docs/apim_yamles/apim_yamles_cli/yamles_cli_encryption.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_environmentalization_example.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_validation_errors.md
  content/en/docs/apim_yamles/yamles_environmentalization.md
Labels: more info needed, size/M

#1505 RDAPI-21835 update doc on types structure
  content/en/docs/apim_yamles/apim_yamles_cli/yamles_cli_importexport.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_top_directories.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
  content/en/docs/apim_yamles/yamles_edit.md
  content/en/docs/apim_yamles/yamles_packaging_deployment.md
  content/en/docs/apim_yamles/yamles_quick_start.md
  content/en/docs/apim_yamles/yamles_structure.md
  static/Images/apim_yamles/yamles_new_container_entity.png
  static/Images/apim_yamles/yamles_new_entity.png
  static/Images/apim_yamles/yamles_types_custom_example.png
  static/Images/apim_yamles/yamles_types_example.png
Labels: more info needed, size/M

#1515 APIGOV-17017 - Updating Central Topology Views
  content/en/docs/central/env_gw_mgmt/_index.md
  content/en/docs/central/env_gw_mgmt/view_environments.md
  static/Images/central/EnvironmentDetailsPage.png
  static/Images/central/EnvironmentListPage.png
  static/Images/central/EnvironmentListResult.png
  static/Images/central/ServiceDetailsPage.png
Labels: more info needed, size/M
