Repository Axway/axway-open-docs, pull requests merged in 2020-01, with the labels that each got.

#207 Anartovich patch 1
  content/en/docs/apim_installation/apigw_containers/docker_script_anmimage.md
Labels: Size: 1

#202 APIGOV-11241 Update CLI create environment documentation
  content/en/docs/central/cli_environments.md
Labels: Size: 1

#213 Video demonstraing how to configure SSO using Keycloak
  content/en/docs/apim_administration/apimgr_admin/sso/saml_sso_config.md
Labels: Size: 1

#215 Fixed typo: WEDSITE to WEBSITE
  .github/ISSUE_TEMPLATE/website-issue-template.md
Labels: Size: 1

#216 Update api_mgmt_register_web.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_register_web.md
Labels: Size: 1

#217 Update api_mgmt_register_web.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_register_web.md
Labels: Size: 1

#221 Update Set up API Gateway Docker scripts section
  content/en/docs/apim_installation/apigw_containers/docker_scripts_prereqs.md
Labels: Size: 1

#219 Update api_mgmt_config_web.md
  content/en/docs/apim_reference/api_mgmt_config_web.md
Labels: Size: 1

#227 IAP-2730 - Update documentation to be aligned with the new Swagger.io rendering tool
  content/en/docs/apim_administration/apiportal_admin/apip_overview.md
  content/en/docs/apim_administration/apiportal_admin/customize_APICatalog_overview.md
  static/Images/uploads/apiportal-jai-customize-api-catalog.png
Labels: Size: 1

#211 Update API Gtw and Mng Release Notes
  content/en/docs/apim_relnotes/apimng_releasenotes/_index.md
Labels: Size: 1, Size: 2

#240 TW review of Cassandra param additions
  content/en/docs/cass_admin/cassandra_config.md
Labels: Size: 1

#225 Added some direct links to security-devices ...
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_virtualize_web.md
Labels: Size: 1

#226 Added swagger promote link
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_promote.md
Labels: Size: 1

#244 Create stale.yml to automatically close stale PR and issues
  .github/stale.yml
Labels: Size: 1

#242 Fix the issue with links on page going to master instead of preview branch
  config.toml
  netlify.toml
Labels: Size: 2

#224 Making a difference in the description between ...
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_virtualize_web.md
Labels: Size: 1

#257 Update page in APIM admin section “api_mgmt_custom”
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_custom.md
Labels: Size: 1

#241 Updated the order of the Swagger UI rendering tools
  content/en/docs/apim_administration/apiportal_admin/apip_overview.md
Labels: Size: 1

#252 Update page in AMPLIFY Central section “feauth_oauth”
  content/en/docs/central/feauth_oauth.md
Labels: Size: 1

#264 Add a simple codeowners file
  .github/CODEOWNERS
Labels: Size: 1

#278 Update _index.md
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
Labels: Size: 1

#284 Update _index.md
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
Labels: Size: 1

#286 Update page in API Gateway/Manager RN section “_index”
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
Labels: Size: 2

#285 Update page in API Portal RN section “_index”
  content/en/docs/apim_relnotes/20200130_apip_relnotes/_index.md
Labels: Size: 1

#283 Update page in APIP admin section “customize_getting_started”
  content/en/docs/apim_administration/apiportal_admin/customize_getting_started.md
  static/Images/APIPortal/layout.png
  static/Images/APIPortal/tiles-homepage.png
Labels: Size: 2

#290 APIGOV-12818 authentication video
  content/en/docs/central/catalog/catalog_integrationbuilder.md
Labels: Size: 1

#281 Add validity to keytool example in APIM SSO config section
  content/en/docs/apim_administration/apimgr_admin/sso/saml_sso_config.md
Labels: Size: 1

#291 Update _index.md
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
Labels: Size: 1

#296 Update page in APIP install section “upgrade_automatic”
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
  static/Images/uploads/banner-config.png
  static/Images/uploads/banner-homepage.png
  static/Images/uploads/layout.png
  static/Images/uploads/tiles-homepage.png
Labels: Size: 1

#310 Add more instructions to Delete an outdated fork
  content/en/docs/contribution_guidelines/deleting_a_repository.md
Labels: Size: 1

#275 Update codeowners with POs
  .github/CODEOWNERS
Labels: Size: 1

#312 Update page in API Portal RN section “fixed_issues”
  content/en/docs/apim_relnotes/20200130_apip_relnotes/fixed_issues.md
Labels: Size: 1

#313 Update page in API Portal RN section “_index”
  content/en/docs/apim_relnotes/20200130_apip_relnotes/_index.md
Labels: Size: 1

#317 APIGOV-12430: Update docs for applying rate-limiting via UI
  content/en/docs/central/proxy_rate_limit.md
  static/Images/central/app_rate_limit_modal.png
  static/Images/central/delete_rate_limit_modal.png
  static/Images/central/proxy_rate_limit_modal.png
  static/Images/central/rate_limit_balloon.png
Labels: Size: 2

#324 Update _index.md
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
Labels: Size: 1

#319 Review APIG/APIM RN:
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/fixed_issues.md
Labels: Size: 2

#320 Update page in APIP admin section “customize_page_content”
  content/en/docs/apim_administration/apiportal_admin/customize_page_content.md
Labels: Size: 1

#325 Update page in APIP containers section “docker_portal_deploy”
  content/en/docs/apim_installation/apiportal_docker/docker_portal_deploy.md
Labels: Size: 2

#323 Update page in APIP install section “upgrade_automatic”
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
Labels: Size: 1

#321 Update page in APIP admin section “customize_APICatalog_overview”
  content/en/docs/apim_administration/apiportal_admin/customize_APICatalog_overview.md
Labels: Size: 1

#326 Update page in APIP install section “install_software_redis”
  content/en/docs/apim_installation/apiportal_install/install_software_redis.md
Labels: Size: 1

#329 Added documentation how to create a Custom-SAML-Assertion
  content/en/docs/apim_policydev/apigw_polref/attributes_manipulate.md
Labels: Size: 1

#333 Included an example how to create a custom JWT
  content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
Labels: Size: 1

#330 Propose changes according to RDAPI-16664
  content/en/docs/cass_admin/cassandra_config.md
Labels: Size: 1

#332 Disable logging to StdOut as recommended by the TLP
  content/en/docs/cass_admin/cassandra_bestpractices.md
Labels: Size: 1

#328 Update release notes
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/fixed_issues.md
Labels: Size: 2

#335 Update page in API Portal RN section “_index”
  content/en/docs/apim_relnotes/20200130_apip_relnotes/_index.md
Labels: Size: 1
