Repository Axway/axway-open-docs, pull requests merged in 2020-09, with the labels that each got.

#1107 [RDAPI-21045] Correct information about leg duration and time in gateway
  content/en/docs/apim_reference/log_global_settings.md
Labels: needs push to prod, size/XS

#1125 Update page in APIP install section “install_unattended”
  content/en/docs/apim_installation/apiportal_install/install_unattended.md
Labels: needs push to prod, size/XS

#1124 Update page in APIP admin section “customize_page_content”
  content/en/docs/apim_administration/apiportal_admin/customize_page_content.md
Labels: size/XS

#1121 APIGOV-15487 - Update pre-requisites and correct dead links
  content/en/docs/central/connect-api-manager/_index.md
  content/en/docs/central/connect-api-manager/deploy-your-agents.md
  content/en/docs/central/connect-aws-gateway/_index.md
Labels: size/S

#1118 Create topic - Deploy your agents with AMPLIFY CLI
  content/en/docs/central/connect-api-manager/Deploy your agents with AMPLIFY CLI
  static/Images/central/connect-api-manager/ServiceDiscoveryAPIM.png
Labels: size/S

#1142 Update PR checklists to add that you must verify that all checks have passed
  .github/pull_request_template.md
Labels: size/XS

#1126 Update page in APIP install section “install_unattended”
  content/en/docs/apim_installation/apiportal_install/install_unattended.md
Labels: needs push to prod, size/XS

#1135 Update page in APIP admin section “manage_privacy_personal_data”
  content/en/docs/apim_administration/apiportal_admin/manage_privacy_personal_data.md
Labels: size/XS

#1129 [RDAPI-21490] Provide multi-org to API Manager External LDAP Identity Provider integration
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_config_external.md
Labels: size/XS

#1123 [RDAPI-19528] Remove or update references to update-apimanager
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
  content/en/docs/apim_reference/scripts_changelog_SP.md
  content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
Labels: size/S

#1153 Create page in Connect API Manager “deploy-your-agents-with-amplify-cli”
  content/en/docs/central/connect-api-manager/deploy-your-agents-with-amplify-cli.md
Labels: size/S

#1154 RMF-11 Update redirects to Streams
  netlify.toml
Labels: size/S

#1131 RDAPI-21491 Use API 1.4 version to be able to add user as member of multiple organizations.
  content/en/docs/apim_administration/apimgr_sso/_index.md
Labels: needs push to prod, size/XS

#1132 RDAPI-21491 - Add instructions to use API and servet v1.4 to enable multiple organizations
  content/en/docs/apim_administration/apimgr_sso/saml_sso_config.md
Labels: needs push to prod, size/XS

#1133 RDAPI-21491 New section 'orgs2Role' attribute to enable multiple organizations
  content/en/docs/apim_administration/apimgr_sso/sso_mapping.md
Labels: needs push to prod, size/XS

#1134 RDAPI-21234 Added information about Date interval behaviour for API Manager metrics
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_monitor.md
Labels: needs push to prod, size/XS

#1167 RDAPI-21702 Update Remove old JRE versions from API Gateway Analytics section
  content/en/docs/apim_relnotes/20200730_apimgr_relnotes.md
Labels: needs push to prod, size/XS

#1146 RDAPI-20951 Add Important changes: update Openjdk to to v8u265
  content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
Labels: size/XS

#1147 RDAPI-21623 Update Sep20 release New Changes section
  content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
Labels: size/XS

#1141 Update page in APIP install section “install_software”
  content/en/docs/apim_installation/apiportal_install/install_software.md
Labels: needs push to prod, size/S

#1174 Update page in Connect API Manager “deploy-your-agents-with-amplify-cli”
  content/en/docs/central/connect-api-manager/deploy-your-agents-with-amplify-cli.md
Labels: netlify-cms/draft, size/M

#1149 Update New features and enhancements section on July20 Release Note
  content/en/docs/apim_relnotes/20200730_apimgr_relnotes.md
Labels: needs push to prod, size/XS

#1151 Update New features and enhancements on May 20 Release Notes
  content/en/docs/apim_relnotes/20200530_apimgr_relnotes.md
Labels: needs push to prod, size/XS

#1155 RDAPI-18049 Add Multi Organization capabilities for a single user
  content/en/docs/api_mgmt_overview/key_concepts/api_mgmt_orgs_roles.md
Labels: needs push to prod, size/XS

#1168 Update page in APIP install section “secure_harden_portal”
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
Labels: size/S

#1161 Create page in AMPLIFY Central section “registering-webhooks-to-listen-on-events”
  content/en/docs/central/cft_profile.md
  content/en/docs/central/integrate_with_webhooks.md
  static/Images/central/custom_subscription_definition.png
  static/Images/central/webhook_flow.png
  static/samples/central/subscriptionEventPayload.json
  static/samples/central/subscriptionEventSchema.json
Labels: needs push to prod, size/M

#1172 RDAPI-20896 Update 20200930_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
Labels: size/XS

#1169 Update page in APIM release note section “20200930_apip_relnotes”
  content/en/docs/apim_relnotes/20200930_apip_relnotes.md
Labels: size/XS

#1175 API Portal - Update Mapping syntax section, mail attribute
  content/en/docs/apim_administration/apiportal_sso/sso_mapping.md
Labels: needs push to prod, size/S

#1176 Update page in APIM SSO section “sso_mapping”
  content/en/docs/apim_administration/apimgr_sso/sso_mapping.md
Labels: needs push to prod, size/XS

#1173 Update Organization administrator role for multi organizations
  content/en/docs/api_mgmt_overview/key_concepts/api_mgmt_orgs_roles.md
Labels: needs push to prod, size/XS

#1177 Update Run API Portal with HTTPS section.
  content/en/docs/apim_installation/apiportal_install/install_software.md
Labels: size/XS

#1180 Update page in Mesh management “add_env”
  content/en/docs/central/mesh_management/add_env.md
Labels: needs push to prod, size/XS

#1181 Update command on Create an environment section.
  content/en/docs/central/cli_central/cli_environments.md
Labels: needs push to prod, size/XS

#1182 [RDAPI-19528] configuration update changes
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
  content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
Labels: size/XS

#1186 RDAPI-21683 Configure orgs2Role header using a policy to assign user to multi organizations
  content/en/docs/apim_administration/apimgr_sso/saml_sso_config.md
Labels: needs push to prod, size/XS

#1187 Update page in APIM release note section “20200930_apip_relnotes”
  content/en/docs/apim_relnotes/20200930_apip_relnotes.md
Labels: size/XS

#1189 [RDAPI-21604] ActiveMQ update to version 5.15.9
  content/en/docs/apim_policydev/apigw_poldev/general_messaging.md
Labels: needs push to prod, size/XS

#1190 Update page in AMPLIFY Central section “integrate_with_webhooks”
  content/en/docs/central/integrate_with_webhooks.md
Labels: needs push to prod

#1192 Fix typo: changed even to event
  content/en/docs/apim-reference-architectures/container-aws/_index.md
Labels: needs push to prod, size/XS

#1193 IAP-3435 Add Known issue related to Connect to URL filter
  content/en/docs/apim_relnotes/20200930_apip_relnotes.md
Labels: size/XS

#1196 RDAPI-15950 Update steps to create user with multi organizations
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_admin.md
Labels: size/XS

#1198 Update page in APIM release note section “20200930_apimgr_relnotes”
  content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
Labels: size/S

#1197 Update page in APIM release note section “20200930_apimgr_relnotes”
  content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
Labels: size/S

#1199 Update New features and enhancements section
  content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
Labels: size/S

#1211 Release Notes Sep20 - Update path to old JRE versions directories
  content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
Labels: size/XS

#1204 Update page in Mesh management “build_hybrid_env”
  content/en/docs/central/mesh_management/build_hybrid_env.md
Labels: needs push to prod, size/XS

#1214 [RDAPI-21825] - Small updates to sept 2020 release notes for multiorg
  content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
Labels: size/XS

#1213 Update Sep20 Release - Important changes
  content/en/docs/apim_relnotes/20200930_apip_relnotes.md
Labels: size/XS

#1215 Update Sep20 release notes - OpenJDK JRE update to v8u265 section
  content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
Labels: size/XS

#1217 7.7 September 20 Merge develop branch into master branch
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_admin.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_config_external.md
  content/en/docs/apim_administration/apiportal_admin/apip_overview.md
  content/en/docs/apim_administration/apiportal_admin/customize_APICatalog_overview.md
  content/en/docs/apim_administration/apiportal_admin/customize_css_styles.md
  content/en/docs/apim_administration/apiportal_admin/customize_getting_started.md
  content/en/docs/apim_administration/apiportal_admin/customize_page_content.md
  content/en/docs/apim_administration/apiportal_admin/expose_APIs_published_from_catalog.md
  content/en/docs/apim_administration/apiportal_admin/localize_language.md
  content/en/docs/apim_administration/apiportal_admin/manage_privacy_personal_data.md
  content/en/docs/apim_administration/apiportal_admin/public_api_configure.md
  content/en/docs/apim_administration/apiportal_admin/role_mapping.md
  content/en/docs/apim_administration/apiportal_admin/troubleshooting.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
  content/en/docs/apim_installation/apiportal_install/install_software.md
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
  content/en/docs/apim_reference/scripts_changelog_SP.md
  content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20200930_apip_relnotes.md
  content/en/docs/apim_yamles/_index.md
  content/en/docs/apim_yamles/apim_yamles_references/_index.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_cicd_example.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_environmentalization_example.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_conversion_errors.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_validation_errors.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_loading.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_syntax_considerations.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_team_development.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_top_directories.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
  content/en/docs/apim_yamles/yamles_cli.md
  content/en/docs/apim_yamles/yamles_edit.md
  content/en/docs/apim_yamles/yamles_environmentalization.md
  content/en/docs/apim_yamles/yamles_externalized_files.md
  content/en/docs/apim_yamles/yamles_packaging_deployment.md
  content/en/docs/apim_yamles/yamles_quick_start.md
  content/en/docs/apim_yamles/yamles_structure.md
  static/Images/APIPortal/system_users_actions_logs_plugin.png
  static/Images/APIPortal/user_actions_logs_options.png
  static/Images/APIPortal/user_actions_logs_table.png
  static/Images/apim_yamles/yamles_conversion_error_case1_1.png
  static/Images/apim_yamles/yamles_conversion_error_case1_2.png
  static/Images/apim_yamles/yamles_conversion_error_case1_3.png
  static/Images/apim_yamles/yamles_package.png
  static/Images/apim_yamles/yamles_parent_file_example.png
  static/Images/apim_yamles/yamles_structure_ps_vs_yaml.png
  static/Images/apim_yamles/yamles_team_dev.png
  static/Images/apim_yamles/yamles_team_dev_2.png
  static/Images/apim_yamles/yamles_team_dev_3.png
  static/admin/config.js
Labels: size/XL

#1194 Update page in APIM ref section “api_mgmt_config_web”
  content/en/docs/apim_reference/api_mgmt_config_web.md
  static/Images/APIGatewayDeveloperGuide/debug-1.png
  static/Images/APIGatewayDeveloperGuide/debug-2.png
Labels: needs push to prod, size/S
