Repository Axway/axway-open-docs, pull requests merged in 2020-02, with the labels that each got.

#337 Update page in APIG upgrade section “upgrade_steps_extcass”
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
Labels: Size: 1

#340 Deprecate back-end API export
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
Labels: Size: 1

#349 Revise update terminology
  content/en/docs/apim_administration/apigtw_admin/admin_non_root.md
  content/en/docs/apim_administration/apigtw_admin/manage_operations.md
  content/en/docs/apim_administration/apigtw_admin/managetopology.md
  content/en/docs/apim_administration/apigtw_admin/trblshoot_get_help.md
  content/en/docs/apim_installation/apigtw_install/install_service_packs.md
  content/en/docs/apim_installation/apigw_containers/container_patch_sp.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_overview.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
  content/en/docs/apim_installation/apiportal_docker/Upgrade_docker.md
  content/en/docs/apim_installation/apiportal_install/install_service_pack.md
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/fixed_issues.md
  content/en/docs/apim_relnotes/20200130_apip_relnotes/_index.md
  content/en/docs/apimgmt_security/c_secgd_bp_intro.md
Labels: Size: 2

#351 RDAPI-18849 remove RAML references
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_workflow.md
Labels: Size: 1

#348 Update page in AMPLIFY Central section “fundamental_concepts”
  content/en/docs/central/fundamental_concepts.md
Labels: Size: 1

#352 IS315 Add notes and known issues
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
Labels: Size: 1

#353 Update page in API Gateway/Manager RN section “fixed_issues”
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/fixed_issues.md
Labels: Size: 1

#356 Update release notes:
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
Labels: Size: 1

#357 Update page in API Gateway/Manager RN section “_index”
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
Labels: Size: 2

#358 Cms/kvedenskii/axway open docs/apiportal docker/docker portal deploy
  content/en/docs/apim_installation/apiportal_docker/docker_portal_deploy.md
Labels: Size: 1

#359 Update page in APIG upgrade section “upgrade_steps_extcass”
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
Labels: Size: 1

#362 Update page in APIG install section “general_acknowledgements”
  content/en/docs/apim_installation/apigtw_install/general_acknowledgements.md
Labels: Size: 1, needs push to prod

#363 Update page in API Portal RN section “_index”
  content/en/docs/apim_relnotes/20200130_apip_relnotes/_index.md
Labels: Size: 1

#364 Update _index.md
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
Labels: Size: 1, needs push to prod

#360 Update page in API Gateway/Manager RN section “_index”
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
Labels: Size: 1

#355 Readability improvements
  content/en/docs/apim_installation/apigtw_install/cassandra_install.md
  content/en/docs/apim_installation/apigtw_install/install_dev_tools.md
  content/en/docs/apim_installation/apigtw_install/installation_unattended.md
  content/en/docs/apim_installation/apigtw_install/system_requirements.md
  content/en/docs/apim_installation/apigw_containers/container_patch_sp.md
Labels: Size: 1

#387 Fix comment delimiters as causing zoomin build failure
  content/en/docs/apim_installation/apigw_containers/configure_edge_agent.md
Labels: Size: 1

#395 Fix broken links on Administer Apache Cassandra
  content/en/docs/cass_admin/cassandra_architecture.md
  content/en/docs/cass_admin/cassandra_config.md
  content/en/docs/cass_admin/cassandra_manage.md
  content/en/docs/cass_admin/cassandra_ops.md
Labels: Size: 1

#203 Improve Netlify CMS integration
  assets/scss/cms.scss
  layouts/partials/hooks/head-end.html
  layouts/partials/page-meta-links.html
  netlify.toml
  static/admin/config.js
  static/admin/config.yml
  static/admin/editor-components.js
  static/admin/index.html
  static/admin/previews.js
Labels: Size: 2

#420 Add hotjar code
  layouts/partials/hooks/head-end.html
Labels: Size: 1

#421 Post for usability improvs and contrib doc updates:
  content/en/blog/news/usability-improvements.md
  content/en/docs/contribution_guidelines/_index.md
  content/en/docs/contribution_guidelines/deleting_a_repository.md
  static/Images/other/alert_example.png
Labels: Size: 2

#422 Update _index.md
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes/_index.md
Labels: Size: 1, needs push to prod

#425 RDAPI-18696: Add warning about shared directories
  content/en/docs/apim_administration/apigtw_admin/apigw_ha.md
  content/en/docs/apim_reference/general_activemq_settings.md
Labels: needs push to prod

#428 Update page in APIG containers section “configure_edge_agent”
  content/en/docs/apim_installation/apigw_containers/configure_edge_agent.md
  content/en/docs/apim_installation/apigw_containers/docker_script_anmimage.md
  content/en/docs/apim_installation/apigw_containers/docker_script_gwimage.md
Labels: Size: 2, needs push to prod

#429 Update page in APIG extend section “selectors”
  content/en/docs/apigtw_devguide/selectors.md
Labels: Size: 1

#431 Improving ModSecurity documentation
  content/en/docs/apim_administration/apigtw_admin/admin_waf.md
Labels: Size: 1, needs push to prod

#432 Update page in Cassandra admin section “cassandra_bur”
  content/en/docs/cass_admin/cassandra_bur.md
Labels: Size: 1, needs push to prod

#433 Mod security change action
  content/en/docs/apim_administration/apigtw_admin/admin_waf.md
Labels: Size: 1, needs push to prod
