Repository Axway/axway-open-docs, pull requests merged in 2021-11, with the labels that each got.

#2141 Cassandra - Change order of the sections, move single-node to the end and multi-node up
  content/en/docs/apim_installation/apigw_upgrade/upgrade_cassandra.md
Labels: size/S

#2138 RDAPI-25680 - Documentation changes for OAuth Client Credentials
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_virtualize_web.md
Labels: size/S, November21

#2140 IAP-4571 - update wildcards in emails
  content/en/docs/apim_administration/apiportal_admin/role_mapping.md
Labels: size/XS

#2143 RMF-218 Update naming from Axway Open Docs to Amplify API Management
  content/en/docs/_index.md
Labels: size/S

#2146 RMF-159 Remove APIM Security guide from APIM documentation
  content/en/docs/apimgmt_security/_index.md
  content/en/docs/apimgmt_security/c_secgd_bp_intro.md
  content/en/docs/apimgmt_security/c_secgd_cert_intro.md
  content/en/docs/apimgmt_security/c_secgd_config_certs.md
  content/en/docs/apimgmt_security/c_secgd_config_secarch.md
  content/en/docs/apimgmt_security/c_secgd_config_secbydefault.md
  content/en/docs/apimgmt_security/c_secgd_config_secconfig.md
  content/en/docs/apimgmt_security/c_secgd_features_intro.md
  content/en/docs/apimgmt_security/c_secgd_iam_intro.md
  content/en/docs/apimgmt_security/c_secgd_sdl.md
  content/en/docs/apimgmt_security/compliance_appendix.md
  static/Images/security/2_securelifecycle.png
  static/Images/security/apigw_sec_arch_a5.png
  static/Images/security/gw_rbac_model.png
  static/Images/security/gw_sec_arch.png
  static/Images/security/rbac_model.png
  static/Images/security/sec_arch.png
Labels: size/XL

#2149 RMF-257 Remove APIM capacity and performance from APIM documentation
  content/en/docs/apimanager_capacityguide/_index.md
  content/en/docs/apimanager_capacityguide/performance_test_configuration.md
  content/en/docs/apimanager_capacityguide/performance_test_results.md
  content/en/docs/apimanager_capacityguide/performance_test_scenarios_multinode.md
  content/en/docs/apimanager_capacityguide/performance_test_scenarios_singlenode.md
  content/en/docs/apimanager_capacityguide/performance_test_settings.md
  static/Images/CapacityPlanningGuide/API Management Performance.png
  static/Images/CapacityPlanningGuide/CPG_HAL.png
  static/Images/CapacityPlanningGuide/CPG_HAL_3.png
  static/Images/CapacityPlanningGuide/CPG_HAR.png
  static/Images/CapacityPlanningGuide/CPG_container_Topology-K8S-AWS.jpg
  static/Images/CapacityPlanningGuide/CPG_single_node.png
Labels: size/M

#2145 [RDAPI-25719] Added Connection Timeout to API Manager reference section General Settings.
  content/en/docs/apim_reference/general_settings.md
Labels: November21

#2152 RMF-220 Test relative links for Zoomin
  content/en/docs/cass_admin/cassandra_manage.md
Labels: zoomin_bug

#2150 IAP-4888: document JAI admin credentials change in installer
  content/en/docs/apim_installation/apiportal_install/install_software.md
  content/en/docs/apim_installation/apiportal_install/install_unattended.md
Labels: size/S, November21

#2151 [RDAPI-25701] Adding details about the format of files 'app.config'
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_custom.md
  content/en/docs/apim_reference/config_files_reference.md
Labels: more info needed, size/S, size/XS

#2153 Revert "RMF-220 Test relative links for Zoomin"
  content/en/docs/cass_admin/cassandra_manage.md
Labels: size/XS

#2154 RMF-220 New draft page for Zoomin
  content/en/docs/glossary/test_redirect_links.md
Labels: size/S

#2155 RMF-220 update link
  content/en/docs/cass_admin/cassandra_manage.md
Labels: size/XS

#2159 RMF-159 Update redirect links to the Security Guide
  .github/CODEOWNERS
  content/en/docs/api_mgmt_overview/key_concepts/policies.md
  content/en/docs/apim_administration/apigtw_admin/general_passphrase.md
  content/en/docs/apim_administration/apigtw_admin/manage_user_access.md
  content/en/docs/apim_installation/apigtw_install/post_overview.md
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
  content/en/docs/apim_policydev/apigw_poldev/general_validation_tools.md
  static/admin/config.js
Labels: size/S

#2158 IAP-4599: cumulative docker docs update ...
  content/en/docs/apim_installation/apiportal_docker/docker_portal_run_image.md
Labels: size/S, November21

#2157 [RDAPI-25554] Adding customized properties for Amplify Connected Menu
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_custom.md
Labels: more info needed, size/S, November21

#2162 [RDAPI-25554] Customize Amplify menu
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_custom.md
Labels: size/XS, November21

#2161 [RDAPI-25893] - Nov 21 release Update features and enhancements
  content/en/docs/apim_relnotes/20211130_apimgr_relnotes.md
Labels: size/XS, November21

#2160 [RDAPI-25182] - upgraded required python version
  content/en/docs/apim_installation/apigw_containers/docker_scripts_prereqs.md
Labels: size/XS, November21

#2163 Correct formatting of jvm.xml snippet
  content/en/docs/apim_installation/apigtw_install/system_requirements.md
Labels: size/XS

#2156 RDAPI-25665 Docs around Disable ability to environmentalise fields in YAML projects as env is not supported yet
  content/en/docs/apim_relnotes/20211130_apimgr_relnotes.md
Labels: size/XS, November21

#2164 IAP-4896: document secret key volume
  content/en/docs/apim_installation/apiportal_docker/docker_portal_run_image.md
Labels: size/XS, November21

#2167 RDAPI-25883 - Update on text for Client Credentials
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_virtualize_web.md
Labels: size/XS, November21

#2168 [RDAPI-25958] Added Output Encodings warning to “common_compress_encoding” page in instances and listeners section
  content/en/docs/apim_policydev/apigw_gw_instances/common_compress_encoding.md
Labels: November21

#2166 Cassandra Upgrade - Restructuring the steps
  content/en/docs/apim_installation/apigw_upgrade/upgrade_cassandra.md
Labels: size/M
