Repository Axway/axway-open-docs, pull requests merged in 2021-05, with the labels that each got.

#1845 Fix typo
  content/en/docs/central/connected_agent_common_reference/upgrade_agent.md
Labels: size/XS

#1832 [IAP-4288] - Update Additional customizations page
  content/en/docs/apim_administration/apiportal_admin/customize_page_content.md
Labels: May21, netlify-cms/pending_review, size/S

#1847 APIGOV-18060 - add new variables and network traffic doc
  content/en/docs/central/connect-api-manager/agent-variables.md
  content/en/docs/central/connect-api-manager/network-traffic-apimanager.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-1.md
  content/en/docs/central/connect-aws-gateway/network-traffic-aws.md
  content/en/docs/central/connect-azure-gateway/agent-variables.md
  content/en/docs/central/connect-azure-gateway/network-traffic-azure.md
Labels: size/S

#1836 RDAPI-21214 - Insecure Transport Update
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_config.md
  content/en/docs/apim_reference/system_props.md
Labels: size/S

#1848 APIGOV-18666 - update trace redaction documentation with better examples
  content/en/docs/central/connected_agent_common_reference/trace_redaction.md
Labels: size/M

#1830 RDAPI-23816 Add Information on how to achieve a zero downtime update, cassandra perspective.
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
  static/Images/UpgradeGuide/upgrade_environmentalized_keyspace.png
Labels: May21, more info needed, size/M

#1849 APIGOV-18060 - documentation for usage data
  content/en/docs/central/connected_agent_common_reference/traceability_usage.md
  static/Images/central/connected_agent_common_reference/step2_select_organization.png
  static/Images/central/connected_agent_common_reference/step3_select_environment.png
  static/Images/central/connected_agent_common_reference/step4_name_environment.png
  static/Images/central/connected_agent_common_reference/usage_data_menu.png
  static/Images/central/connected_agent_common_reference/usage_report_screen.png
Labels: size/S

#1856 APIGOV-18698 - cleanup refs to only tracking events on discovered apis
  content/en/docs/central/connect-api-manager/_index.md
  content/en/docs/central/connect-api-manager/agent-variables.md
  content/en/docs/central/connect-api-manager/gateway-administation.md
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
Labels: size/S

#1834 [RDAPI-17488] setup-cassandra script doc improvements
  content/en/docs/cass_admin/cassandra_setup_script.md
Labels: May21, more info needed

#1840 RDAPI-14603 Add Security response headers section
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
  content/en/docs/apim_policydev/apigw_gw_instances/configure_http_strict_transport_security.md
  content/en/docs/apimgmt_security/c_secgd_config_secconfig.md
Labels: May21, size/S

#1858 APIGOV-18438 - add new error codes
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
  content/en/docs/central/connect-aws-gateway/tips-and-troubleshooting.md
  content/en/docs/central/connect-azure-gateway/tips-and-troubleshooting.md
Labels: size/XS

#1859 Error codes table contains an extra line
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
Labels: size/XS

#1860 Revert "RDAPI-23816 Add Information on how to achieve a zero downtime update, cassandra perspective."
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
  static/Images/UpgradeGuide/upgrade_environmentalized_keyspace.png
Labels: size/M

#1850 RDAPI-21747 Include ActiveMQ changes in release notes
  content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
Labels: May21, size/S

#1855 [RDAPI-23947] Adding com.vordel.oathAuthorizationRecordsThreshold system property
  content/en/docs/apim_reference/system_props.md
Labels: May21, size/XS

#1857 [RDAPI-21211] Adding new JVM flag information to the System property changes document
  content/en/docs/apim_reference/system_props.md
Labels: May21, size/XS

#1861 Add Dependency View in APIM May 21 release notes
  content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
Labels: May21, size/XS

#1862 RMF-105 Change AMPLIFY to Amplify -- text only
  content/en/docs/catalog/_index.md
  content/en/docs/catalog/authenticate-an-external-gateway-api.md
  content/en/docs/catalog/discover-and-consume-catalog-assets.md
  content/en/docs/catalog/manage-catalog-assets.md
  content/en/docs/catalog/manage_subscriptions.md
  content/en/docs/catalog/testing-an-api-from-the-browser.md
  content/en/docs/central/_index.md
  content/en/docs/central/backend_TLS.md
  content/en/docs/central/backend_authn.md
  content/en/docs/central/cft_profile.md
  content/en/docs/central/env_gw_mgmt/_index.md
  content/en/docs/central/env_gw_mgmt/environment_agent_resources.md
  content/en/docs/central/feauth_oauth.md
  content/en/docs/central/fundamental_concepts.md
  content/en/docs/central/integrate_with_webhooks.md
  content/en/docs/central/mesh_management/_index.md
  content/en/docs/central/mesh_management/add_env.md
  content/en/docs/central/mesh_management/build_hybrid_env.md
  content/en/docs/central/overview.md
  content/en/docs/central/proxy_rate_limit.md
  content/en/docs/central/quickstart.md
  content/en/docs/central/secure_api_jwt.md
Labels: size/M

#1864 APIGOV-17556 - add traceability agent sampling documentation
  content/en/docs/central/connect-api-manager/agent-variables.md
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-1.md
  content/en/docs/central/connect-aws-gateway/tips-and-troubleshooting.md
  content/en/docs/central/connect-azure-gateway/agent-variables.md
  content/en/docs/central/connect-azure-gateway/tips-and-troubleshooting.md
  content/en/docs/central/connected_agent_common_reference/trace_sampling.md
Labels: size/S

#1818 Add April AMPC relnotes
  content/en/docs/central/amplify_relnotes/20210430_ampc_relnotes.md
Labels: size/M

#1863 Update page in pol filter ref section “routing_common”
  content/en/docs/apim_policydev/apigw_polref/routing_common.md
Labels: size/S

#1867 IAP-4062 Update Install Unattended with mysql-keep option
  content/en/docs/apim_installation/apiportal_install/install_unattended.md
Labels: May21

#1853 RDAPI-24144 uprelease notes and pre may21 upgrade instructions
  content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
  content/en/docs/apim_yamles/_index.md
  content/en/docs/apim_yamles/apim_yamles_cli/yamles_cli_upgrade.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
Labels: May21, more info needed, size/S

#1868 APIGOV-18074 - add service update sub command
  content/en/docs/central/connect-api-manager/deploy-your-agents-with-amplify-cli.md
  content/en/docs/central/connect-api-manager/gateway-administation.md
Labels: size/M

#1869 RDAPI-24139 Update as Jan21 is not supported for YAML ES Upgrade
  content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
  content/en/docs/apim_yamles/apim_yamles_cli/yamles_cli_upgrade.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
Labels: May21, size/S

#1871 APIGOV-18178 - Update variable name
  content/en/docs/central/connect-api-manager/agent-variables.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-1.md
  content/en/docs/central/connect-azure-gateway/agent-variables.md
Labels: size/XS

#1874 Add missing periods in descriptions
  static/admin/config.js
Labels: size/XS

#1873 APIGOV-18618 - update sampling for per api
  content/en/docs/central/connect-api-manager/agent-variables.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-1.md
  content/en/docs/central/connect-azure-gateway/agent-variables.md
  content/en/docs/central/connected_agent_common_reference/trace_sampling.md
Labels: size/S

#1876 RMF-177 Update postcss to a non-vulnerable version
  package-lock.json
Labels: dependencies

#1877 RMF-177 Update postcss to a non-vulnerable version
  package-lock.json
Labels: dependencies, size/XS

#1878 RDAPI-24200 Add fixed bug some customers wanted to see fixed in release note
  content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
Labels: May21, size/S

#1879 [RDAPI-23695] Updating docs with JWT Verify changes
  content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
  content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
Labels: May21, more info needed, size/S

#1881 [RDAPI-24242] New SHA-256 hash algorithm option on SFTP server fingerprint check
  content/en/docs/apim_policydev/apigw_gw_instances/general_ftp_scanner.md
  content/en/docs/apim_policydev/apigw_polref/routing_additional.md
  content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
Labels: May21, size/S

#1886 RDAPI-23695 Adding tip to JWT Verify docs
  content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
Labels: May21, size/XS

#1882 Update page in APIM release note section “20210530_apimgr_relnotes”
  content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
Labels: May21

#1893 RMF-177 Update sha512 string
  package-lock.json
Labels: size/XS

#1888 Update page in APIM release note section “20210530_apip_relnotes”
  content/en/docs/apim_relnotes/20210530_apip_relnotes.md
Labels: May21, netlify-cms/draft, size/S

#1895 APIGOV-18499 - new error codes
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
  content/en/docs/central/connect-aws-gateway/tips-and-troubleshooting.md
  content/en/docs/central/connect-azure-gateway/tips-and-troubleshooting.md
Labels: size/S
