Repository Axway/axway-open-docs, pull requests merged in 2021-01, with the labels that each got.

#1523 [RDAPI-22709] Update system_props.md
  content/en/docs/apim_reference/system_props.md
Labels: size/XS

#1524 [RDAPI-22652] Updating admin_waf.md
  content/en/docs/apim_administration/apigtw_admin/admin_waf.md
Labels: size/XS

#1526 Update supported k8s version for hybrid
  content/en/docs/central/mesh_management/build_hybrid_env.md
Labels: size/XS

#1520 [RDAPI-21508][RDAPI-22590] Minor modifications to export.
  content/en/docs/apim_yamles/apim_yamles_cli/yamles_cli_importexport.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_conversion_errors.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_validation_errors.md
Labels: size/XS

#1525 APIGOV-17163 Reorg Connect AWS Gateway
  content/en/docs/central/connect-aws-gateway/_index.md
  content/en/docs/central/connect-aws-gateway/agent-security-aws.md
  content/en/docs/central/connect-aws-gateway/cloud-administration-operation.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-1.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-quickstart.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-with-amplify-cli.md
  content/en/docs/central/connect-aws-gateway/filtering-apis-to-be-discovered-1.md
  content/en/docs/central/connect-aws-gateway/impact-of-deleting-an-api-stage.md
  content/en/docs/central/connect-aws-gateway/network-traffic-aws.md
  content/en/docs/central/connect-aws-gateway/prepare-amplify-central-1.md
  content/en/docs/central/connect-aws-gateway/prepare-aws-api-gateway.md
  content/en/docs/central/connect-aws-gateway/subscription-for-the-consumer.md
  content/en/docs/central/connect-aws-gateway/tips-and-troubleshooting.md
Labels: size/M

#1530 IAP-3174 & IAP-3889: Update Headers in Configure Apache section; Update PHP configurations;
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
Labels: size/XS

#1531 Create Jan 21 Release note pages into developjan21 branch
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20200130_apip_relnotes.md
  content/en/docs/apim_relnotes/20200330_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20200330_apip_relnotes.md
  content/en/docs/apim_relnotes/20200530_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20200530_apip_relnotes.md
  content/en/docs/apim_relnotes/20200730_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20200730_apip_relnotes.md
  content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20200930_apip_relnotes.md
  content/en/docs/apim_relnotes/20201130_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20201130_apip_relnotes.md
  content/en/docs/apim_relnotes/20210130_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20210130_apip_relnotes.md
Labels: size/M

#1535 RDAPI-20442 Disable SSL renegotiation on TLS 1.2 Listeners and lower
  content/en/docs/apim_policydev/apigw_gw_instances/general_services.md
Labels: size/XS

#1534 RDAPI-20442 Disable SSL renegotiation on TLS 1.2 Listeners and lower: Update page in APIM release note section “20210130_apimgr_relnotes”
  content/en/docs/apim_relnotes/20210130_apimgr_relnotes.md
Labels: size/XS

#1538 Update page in pol filter ref section “routing_common”
  content/en/docs/apim_policydev/apigw_polref/routing_common.md
Labels: size/XS

#1536 APIGOV-17236 Create Azure structure
  content/en/docs/central/connect-azure-gateway/_index.md
  content/en/docs/central/connect-azure-gateway/agent-variables.md
  content/en/docs/central/connect-azure-gateway/manage-subscriptions.md
  content/en/docs/central/connect-azure-gateway/tips-and-troubleshooting.md
  static/Images/central/connect-azure-gateway/discoveryagent.png
  static/Images/central/connect-azure-gateway/traceabilityagent.png
Labels: size/L

#1539 Update page in instances and listeners section “general_services”
  content/en/docs/apim_policydev/apigw_gw_instances/general_services.md
Labels: size/XS

#1537 RDAPI-22701 Update page in KPS section “how_to_use_kpsadmin_command”
  content/en/docs/apim_policydev/apigw_kps/how_to_use_kpsadmin_command.md
  static/Images/APIGatewayKPSUserGuide/03000019.png
  static/Images/APIGatewayKPSUserGuide/0300001A.png
  static/Images/APIGatewayKPSUserGuide/0300001D.png
  static/Images/APIGatewayKPSUserGuide/backupcollection.png
  static/Images/APIGatewayKPSUserGuide/restorecollection.png
Labels: size/S

#1545 [RDAPI-22701] Update image on Create a New Data Source section
  content/en/docs/apim_policydev/apigw_kps/how_to_use_kpsadmin_command.md
  static/Images/APIGatewayKPSUserGuide/kpscollections.png
Labels: size/XS

#1542 [RDAPI-22362] Update page in APIG admin section “general_certificates”
  content/en/docs/apim_administration/apigtw_admin/general_certificates.md
Labels: size/XS

#1540 [IAP-3788] - Update information about Try-it button visibility
  content/en/docs/apim_administration/apiportal_admin/customize_APICatalog_overview.md
Labels: more info needed, size/XS

#1529 IAP-3857: API Portal docker related docs ...
  content/en/docs/apim_installation/apiportal_docker/_index.md
  content/en/docs/apim_installation/apiportal_docker/docker_portal_compose.md
  content/en/docs/apim_installation/apiportal_docker/docker_portal_deploy.md
  content/en/docs/apim_installation/apiportal_docker/docker_portal_run_image.md
  content/en/docs/apim_installation/apiportal_docker/docker_portal_upgrade.md
  content/en/docs/apim_installation/apiportal_docker/docker_troubleshoot.md
Labels: more info needed, size/S

#1541 RDAPI-22743 Update Organization Administrator section
  content/en/docs/api_mgmt_overview/key_concepts/api_mgmt_orgs_roles.md
Labels: more info needed, size/S

#1552 Add section Deploy Preview Link to pull request template
  .github/pull_request_template.md
Labels: size/S

#1544 [RDAPI-22653] Changes for common criteria encryption for YAMLES
  content/en/docs/apim_yamles/apim_yamles_cli/yamles_cli_encryption.md
  content/en/docs/apim_yamles/yamles_edit.md
Labels: size/S

#1543 IAP-3174 - edit Apache configuration section due to SSO problem;
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
Labels: more info needed, size/XS

#1553 IAP-3839 Update Jan21 Release Notes for APIP
  content/en/docs/apim_relnotes/20210130_apip_relnotes.md
Labels: size/XS

#1556 Make characters code-compatible
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
Labels: size/XS

#1547 RDAPI-22861 yamles ref as selector warning
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_validation_errors.md
Labels: size/XS

#1548 RDAPI-22757 rewrite YAML type chapter
  content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
Labels: size/XS

#1558 Add new Azure documentation to Netlify CMS
  static/admin/config.js
Labels: size/XS

#1559 CaseID 01225846: Update Create REST API methods section
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_register_web.md
Labels: more info needed, size/XS

#1560 Update APIP Release Notes Jan21
  content/en/docs/apim_relnotes/20210130_apip_relnotes.md
Labels: size/XS

#1565 RMF-94 Add codeowners for connect-azure-gateway
  .github/CODEOWNERS
Labels: size/XS

#1569 APIGOV-16518 Fix typos
  content/en/docs/central/connect-api-manager/deploy-your-agents-with-amplify-cli.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-with-amplify-cli.md
  content/en/docs/central/connect-azure-gateway/manage-subscriptions.md
Labels: size/S

#1568 Create Azure topic deploy-your-agents-with-amplify-cli
  content/en/docs/central/connect-azure-gateway/deploy-your-agents-with-amplify-cli.md
Labels: size/S

#1554 RDAPI-21716 add pem support for cert and private key and new syntax in files externalization
  content/en/docs/apim_yamles/apim_yamles_cli/yamles_cli_encryption.md
  content/en/docs/apim_yamles/yamles_edit.md
  content/en/docs/apim_yamles/yamles_externalized_files.md
Labels: size/S

#1574 APIGOV-16919 - Update page in Connect Azure Gateway “_index”
  content/en/docs/central/connect-azure-gateway/_index.md
Labels: netlify-cms/pending_review, size/M

#1562 [RDAPI-22658] Add JOSE Header setting to JWT Sign Filter
  content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
Labels: size/XS

#1566 APIP Jan21 Update New features and Enhancements
  content/en/docs/apim_relnotes/20210130_apip_relnotes.md
  static/Images/docbook/images/release_notes/dual-pane-layout-config-jan21.png
  static/Images/docbook/images/release_notes/dual-pane-layout-jan21.png
  static/Images/docbook/images/release_notes/hide-try-it-for-specific-tags.png
Labels: size/S

#1567 Make it clear hsmpin.sh should have execute permission
  content/en/docs/apim_administration/apigtw_admin/general_certificates.md
Labels: size/XS

#1578 Fix broken link in Connect API Manager “network-traffic-apimanager”
  content/en/docs/central/connect-api-manager/network-traffic-apimanager.md
Labels: netlify-cms/pending_publish, size/S

#1555 Create January APICentral Release Notes
  content/en/docs/central/amplify_relnotes/20210131_ampc_relnotes.md
Labels: size/M

#1575 IAP-3867: Add information about new SwaggerUI layout
  content/en/docs/apim_administration/apiportal_admin/customize_APICatalog_overview.md
  static/Images/APIPortal/api-catalog.png
Labels: size/XS

#1584 Update page in AMPLIFY Release notes section “20210131_ampc_relnotes”
  content/en/docs/central/amplify_relnotes/20210131_ampc_relnotes.md
Labels: netlify-cms/pending_review, size/XS

#1582 RDAPI-22573 Update Jan21 Known issues
  content/en/docs/apim_relnotes/20210130_apimgr_relnotes.md
Labels: size/XS

#1576 IAP-3867: Add information about new SwaggerUI layout
  content/en/docs/apim_administration/apiportal_admin/apip_overview.md
Labels: more info needed, size/XS

#1583 [RDAPI-23050] Add release notes for YAML for Nov and Jan21.
  content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20201130_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20210130_apimgr_relnotes.md
Labels: size/XS

#1585 Update API Gateway Jan21 Deprecated features
  content/en/docs/apim_relnotes/20210130_apimgr_relnotes.md
Labels: size/XS

#1587 [RDAPI-22776] [RDAPI-22183] Update API Gateway Jan21 New Features for Security Policy header
  content/en/docs/apim_relnotes/20210130_apimgr_relnotes.md
Labels: size/XS

#1586 Update API Gateway Jan 21 List of Fixed issues and Known issues
  content/en/docs/apim_relnotes/20210130_apimgr_relnotes.md
Labels: size/XS

#1588 7.7 January 21 Merge developjan21 branch into master
  content/en/docs/api_mgmt_overview/key_concepts/api_mgmt_orgs_roles.md
  content/en/docs/apim_administration/apiportal_admin/apip_overview.md
  content/en/docs/apim_administration/apiportal_admin/customize_APICatalog_overview.md
  content/en/docs/apim_administration/apiportal_admin/localize_language.md
  content/en/docs/apim_installation/apiportal_docker/_index.md
  content/en/docs/apim_installation/apiportal_docker/docker_portal_compose.md
  content/en/docs/apim_installation/apiportal_docker/docker_portal_deploy.md
  content/en/docs/apim_installation/apiportal_docker/docker_portal_run_image.md
  content/en/docs/apim_installation/apiportal_docker/docker_portal_upgrade.md
  content/en/docs/apim_installation/apiportal_docker/docker_troubleshoot.md
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
  content/en/docs/apim_policydev/apigw_gw_instances/general_services.md
  content/en/docs/apim_policydev/apigw_kps/how_to_use_kpsadmin_command.md
  content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
  content/en/docs/apim_relnotes/20200130_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20200130_apip_relnotes.md
  content/en/docs/apim_relnotes/20200330_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20200330_apip_relnotes.md
  content/en/docs/apim_relnotes/20200530_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20200530_apip_relnotes.md
  content/en/docs/apim_relnotes/20200730_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20200730_apip_relnotes.md
  content/en/docs/apim_relnotes/20200930_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20200930_apip_relnotes.md
  content/en/docs/apim_relnotes/20201130_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20201130_apip_relnotes.md
  content/en/docs/apim_relnotes/20210130_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20210130_apip_relnotes.md
  content/en/docs/apim_yamles/apim_yamles_cli/yamles_cli_encryption.md
  content/en/docs/apim_yamles/apim_yamles_cli/yamles_cli_importexport.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_environmentalization_example.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_conversion_errors.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_validation_errors.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_top_directories.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
  content/en/docs/apim_yamles/yamles_edit.md
  content/en/docs/apim_yamles/yamles_environmentalization.md
  content/en/docs/apim_yamles/yamles_externalized_files.md
  content/en/docs/apim_yamles/yamles_packaging_deployment.md
  content/en/docs/apim_yamles/yamles_quick_start.md
  content/en/docs/apim_yamles/yamles_structure.md
  static/Images/APIGatewayKPSUserGuide/03000019.png
  static/Images/APIGatewayKPSUserGuide/0300001D.png
  static/Images/APIGatewayKPSUserGuide/backupcollection.png
  static/Images/APIGatewayKPSUserGuide/kpscollections.png
  static/Images/APIGatewayKPSUserGuide/restorecollection.png
  static/Images/APIPortal/api-catalog.png
  static/Images/apim_yamles/yamles_new_container_entity.png
  static/Images/apim_yamles/yamles_new_entity.png
  static/Images/apim_yamles/yamles_types_custom_example.png
  static/Images/apim_yamles/yamles_types_example.png
  static/Images/docbook/images/release_notes/dual-pane-layout-config-jan21.png
  static/Images/docbook/images/release_notes/dual-pane-layout-jan21.png
  static/Images/docbook/images/release_notes/hide-try-it-for-specific-tags.png
Labels: size/XL

#1589 API Gtw Jan 21 - Reinstate change that was lost during fixing conflict with PR#1587
  content/en/docs/apim_relnotes/20210130_apimgr_relnotes.md
Labels: size/S

#1591 RMF-99 Temporarily disable auto merge from master to developjan21
  .github/workflows/merge_to_develop.yml
Labels: size/S

#1581 API-Portal - Troubleshooting - Random session logout
  content/en/docs/apim_administration/apiportal_admin/troubleshooting.md
Labels: more info needed, size/S

#1592 RMF-99 Delete file for auto merge
  .github/workflows/merge_to_develop.yml
Labels: size/S

#1593 RMF-98 API Gateway Jan 21 Update Deprecated features
  content/en/docs/apim_relnotes/20210130_apimgr_relnotes.md
Labels: size/XS
