Repository Axway/axway-open-docs, pull requests merged in 2021-07, with the labels that each got.

#1973 [RDAPI-23220] Adding use of regular expression section to redaction
  content/en/docs/apim_administration/apigtw_admin/admin_redactors.md
Labels: August21, size/S

#1979 RMF-198 Fix formating on Configure caching page
  content/en/docs/apim_policydev/apigw_poldev/general_cache.md
Labels: size/S

#1978 [RDAPI-22331] Ratelimit for unauthenticated requests.
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_config.md
Labels: August21, size/S

#1984 RMF-163 Update setup-cassandra script reference page's name
  content/en/docs/cass_admin/cassandra_architecture.md
  content/en/docs/cass_admin/cassandra_setup_script.md
Labels: size/S

#1985 Update page in Manage your environments and gateways “_index”
  content/en/docs/central/env_gw_mgmt/_index.md
Labels: netlify-cms/pending_review, size/S

#1982 Add note to ensure customers add "redaction.xml" correctly
  content/en/docs/apim_administration/apigtw_admin/admin_redactors.md
Labels: size/XS

#1987 APIGOV-19257 - add KMS info to docs
  content/en/docs/central/connect-aws-gateway/cloud-administration-operation.md
Labels: size/S

#1988 APIGOV-18093 - note about catalog subscription mode
  content/en/docs/central/connect-api-manager/subscription-for-the-consumer.md
  content/en/docs/central/connect-aws-gateway/subscription-for-the-consumer.md
  content/en/docs/central/connect-azure-gateway/manage-subscriptions.md
Labels: netlify-cms/pending_review, size/XS

#1995 APIGOV-18415 - update for JMS property redaction in agents
  content/en/docs/central/connect-api-manager/agent-variables.md
  content/en/docs/central/connect-azure-gateway/agent-variables.md
  content/en/docs/central/connected_agent_common_reference/trace_redaction.md
  content/en/docs/central/connected_agent_common_reference/upgrade_agent.md
Labels: size/M

#2001 Removed Amplify Central API from April, May, June RelNotes
  content/en/docs/central/amplify_relnotes/20210430_ampc_relnotes.md
  content/en/docs/central/amplify_relnotes/20210531_ampc_relnotes.md
  content/en/docs/central/amplify_relnotes/20210630_ampc_relnotes.md
Labels: size/S

#1986 RDAPI-23981 System Properties update
  content/en/docs/apim_reference/system_props.md
Labels: August21, size/XS

#2003 Update page in Connected agent - Common reference “traceability_usage”
  content/en/docs/central/connected_agent_common_reference/traceability_usage.md
Labels: netlify-cms/draft, size/S

#2005 Update jfrog links
  content/en/docs/central/connect-aws-gateway/_index.md
  content/en/docs/central/connect-aws-gateway/cloud-administration-operation.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-quickstart.md
Labels: size/XS

#2009 Connected agent - clarification on disabling the transaction report
  content/en/docs/central/connected_agent_common_reference/traceability_usage.md
Labels: netlify-cms/draft, size/XS
