Repository Axway/axway-open-docs, pull requests merged in 2021-10, with the labels that each got.

#2122 Make more clear when to use which ICAP-Mode
  content/en/docs/apim_policydev/apigw_external_connections/common_icap_conf.md
Labels: size/S

#2121 RDAPI-25075 Updates to service-provider.xml section
  content/en/docs/apim_administration/apimgr_sso/sso_mapping.md
Labels: size/XS

#2126 [RDAPI-25331] Import YAML fragments
  content/en/docs/apim_policydev/apigw_poldev/general_import.md
  content/en/docs/apim_policydev/apigw_poldev/general_project.md
Labels: size/S, November21

#2128 [RDAPI-25480] Update definitions of 'duration' in transactions
  content/en/docs/apim_reference/log_global_settings.md
Labels: size/S
