Repository Axway/axway-open-docs, pull requests merged in 2021-03, with the labels that each got.

#1639 RDAPI-22806 Documentation for Passphrase Password Policy
  content/en/docs/apim_administration/apigtw_admin/manage_user_access.md
  content/en/docs/apim_reference/config_files_reference.md
  content/en/docs/apimgmt_security/c_secgd_bp_intro.md
  content/en/docs/apimgmt_security/c_secgd_config_secconfig.md
Labels: more info needed, size/M

#1655 [IAP-3855] - Update page in APIP admin section “customize_page_content”
  content/en/docs/apim_administration/apiportal_admin/customize_page_content.md
Labels: more info needed, size/XS

#1656 RDAPI-22981 Adding section for accepted algorithms
  content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
Labels: size/XS

#1657 Update page in APIP install section “install_software_prereqs”
  content/en/docs/apim_installation/apiportal_install/install_software_prereqs.md
Labels: size/XS

#1664 RDAPI-22983 Add HEADER claims validation in the JWT filter
  content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
Labels: more info needed, size/XS

#1690 RDAPI-22983 Add HEADER claims validation in the JWT filter - complement
  content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
Labels: size/XS

#1665 IAP-2010: Adding Intercom support in API Portal;
  content/en/docs/apim_administration/apiportal_admin/customize_page_content.md
Labels: March21, more info needed

#1677 [RDAPI-19415] Add PGP Verification page
  content/en/docs/apim_installation/apigtw_install/verify_downloads.md
Labels: March21, size/S

#1674 RDAPI-16778 Add recommendations for Cassandra storage
  content/en/docs/apim_installation/apigtw_install/cassandra_install.md
Labels: size/S

#1673 [RDAPI-22975] Define and enforce detached signatures
  content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
Labels: size/S

#1687 [RDAPI-23002] Adding section for typ and cty - JWT Verify
  content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
Labels: March21, size/XS

#1675 Expanded section on system property changes with advice on how to use those properties safely
  content/en/docs/apim_reference/system_props.md
Labels: size/XS

#1672 RDAPI-22425 Clarify that MIME types apply to Static Content + fix reference links
  content/en/docs/apim_reference/general_settings.md
Labels: size/XS

#1691 [IAP-3855] - Update page in APIP admin section “customize_page_content”
  content/en/docs/apim_administration/apiportal_admin/customize_page_content.md
Labels: March21, size/XS

#1682 IAP-4039 - Update link to download API Portal Docker image from Support
  content/en/docs/apim_installation/apiportal_docker/docker_portal_upgrade.md
Labels: size/XS

#1681 IAP-4039 - Update instructions on Run API Portal using ready-made Docker image page
  content/en/docs/apim_installation/apiportal_docker/docker_portal_run_image.md
Labels: size/XS

#1683 IAP-4039- docker_portal_deploy page - Update link to download Docker sample package
  content/en/docs/apim_installation/apiportal_docker/docker_portal_deploy.md
Labels: size/XS

#1693 [RDAPI-22982] Update JWT Verify filter with Key Discovery info
  content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
Labels: March21, size/S

#1684 IAP- 3049 - “docker_portal_compose” page - Update links to download Docker image and Docker sample package
  content/en/docs/apim_installation/apiportal_docker/docker_portal_compose.md
Labels: size/XS

#1676 Expanded the list of things you have to upgrade manually
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
Labels: size/XS

#1678 Update 'API Gateway One Version' to add instruction on privileged ports
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
Labels: size/XS

#1688 RDAPI-19851 jython security vulnerabilities update to January 21 Release note
  content/en/docs/apim_relnotes/20210130_apimgr_relnotes.md
Labels: size/XS

#1679 Add steps to run sysupgrade apply with increased timeouts
  content/en/docs/apim_installation/apigw_upgrade/upgrade_faq.md
Labels: more info needed, size/S

#1680 Add error from a sysupgrade apply timeout
  content/en/docs/apim_installation/apigw_upgrade/upgrade_errors.md
Labels: more info needed, size/XS

#1689 RDAPI-23307 Add JWT Verify Filter payload claim validate policy
  content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
Labels: March21

#1695 IAP-4034 Update 'Add a translated UI string file' with how to translate labels or values of custom properties
  content/en/docs/apim_administration/apiportal_admin/localize_language.md
Labels: March21, size/XS

#1710 RMF-119 Update APIP release notes retrospectively for Docker image
  content/en/docs/apim_relnotes/201904_release/apip_relnotes.md
  content/en/docs/apim_relnotes/20200130_apip_relnotes.md
  content/en/docs/apim_relnotes/20200330_apip_relnotes.md
  content/en/docs/apim_relnotes/20200530_apip_relnotes.md
  content/en/docs/apim_relnotes/20200730_apip_relnotes.md
  content/en/docs/apim_relnotes/20200930_apip_relnotes.md
  content/en/docs/apim_relnotes/20201130_apip_relnotes.md
  content/en/docs/apim_relnotes/20210130_apip_relnotes.md
Labels: size/M

#1697 RDAPI-22585 Enable – Disable automatic email with registration token after a new Org is created
  content/en/docs/apim_reference/api_mgmt_config_web.md
Labels: March21, size/XS

#1698 IAP-4070 Update APIP Installation Prerequisites section for MySQL and MariaDB versions
  content/en/docs/apim_installation/apiportal_install/install_software_prereqs.md
Labels: size/XS

#1694 RDAPI-23550 - Update Configure API Manager request rate limiter
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_config.md
Labels: March21, size/XS

#1715 APIGOV-16518 Fix typos
  content/en/docs/central/connect-api-manager/agent-variables.md
  content/en/docs/central/connect-api-manager/deploy-your-agents.md
  content/en/docs/central/connect-api-manager/filtering-apis-to-be-discovered.md
  content/en/docs/central/connect-api-manager/gateway-administation.md
  content/en/docs/central/connect-api-manager/network-traffic-apimanager.md
  content/en/docs/central/connect-api-manager/subscription-for-the-consumer.md
  content/en/docs/central/connect-aws-gateway/cloud-administration-operation.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-1.md
  content/en/docs/central/connect-aws-gateway/filtering-apis-to-be-discovered-1.md
  content/en/docs/central/connect-aws-gateway/prepare-aws-api-gateway.md
  content/en/docs/central/connect-aws-gateway/subscription-for-the-consumer.md
  content/en/docs/central/connect-azure-gateway/agent-variables.md
  content/en/docs/central/connect-azure-gateway/deploy-your-agents-with-amplify-cli.md
  content/en/docs/central/connect-azure-gateway/network-traffic-azure.md
Labels: size/S

#1728 [RDAPI-22708] API Manager session timeout added to API Manager configuration
  content/en/docs/apim_reference/api_mgmt_config_web.md
Labels: size/XS

#1700 Update New features and enhancements
  content/en/docs/apim_relnotes/20210330_apip_relnotes.md
Labels: March21, more info needed, size/S

#1701 RDAPI-20494 Creation of new apigateway with yaml factory option
  content/en/docs/apim_reference/managedomain_ref.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
  content/en/docs/apim_yamles/yamles_packaging_deployment.md
Labels: March21, size/S

#1708 RDAPI-23337 - Update March Release Note with details of upgrade to libthrift
  content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
Labels: March21, size/XS

#1727 Added central/env_gw_mgmt folder collection
  static/admin/config.js
Labels: size/XS

#1717 [RDAPI-22268] [CWE-378] Insecure Temporary Directory used by Jetty in Policy Studio
  content/en/docs/apim_installation/apigtw_install/install_policy_studio.md
Labels: more info needed, size/XS

#1720 Update page in APIP install section “install_software_prereqs”
  content/en/docs/apim_installation/apiportal_install/install_software_prereqs.md
  content/en/docs/apim_relnotes/20200130_apip_relnotes.md
Labels: size/XS

#1739 Fix links and typos
  content/en/docs/central/mesh_management/add_env.md
  content/en/docs/central/mesh_management/build_hybrid_env.md
  content/en/docs/central/mesh_management/deploy-your-agents-with-the-amplify-cli.md
  content/en/docs/central/mesh_management/discover-apis-and-services.md
  content/en/docs/central/mesh_management/traceability_agent_configuration.md
  content/en/docs/central/mesh_management/using_redhat_openshift.md
Labels: size/S

#1744 IAP-3988 Replaces PR1742 Updates to APIP Mar21 release
  content/en/docs/apim_relnotes/20210330_apip_relnotes.md
Labels: March21, size/S

#1709 RDAPI-23251 - Update the user documentation with information about the new encryption
  content/en/docs/apim_administration/apigtw_admin/general_passphrase.md
  content/en/docs/apimgmt_security/c_secgd_features_intro.md
Labels: March21, more info needed, size/S

#1723 RDAPI-23536 - Change label to Enable registration token email notifications
  content/en/docs/apim_reference/api_mgmt_config_web.md
Labels: March21, size/XS

#1721 [RDAPI-21485] Adding section for automatic PS project upgrade
  content/en/docs/apim_policydev/apigw_poldev/gs_project.md
  content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
Labels: March21, size/S

#1722 RDAPI-23024 fix yaml pk flaw revisit doc for obsolete notions
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_conversion_errors.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_validation_errors.md
  content/en/docs/apim_yamles/yamles_structure.md
Labels: March21, size/XS

#1730 [RDAPI-23129] Review Release notes New Features and enhancements
  content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
Labels: March21, size/XS

#1741 [IAP-4055] - Update page in APIP install section “install_dependencies”
  content/en/docs/apim_installation/apiportal_install/install_dependencies.md
Labels: March21, size/XS

#1734 [RDAPI-23542] - Added MySQL 8 driver information
  content/en/docs/apim_installation/apigtw_install/metrics_db_install.md
  content/en/docs/apim_installation/apigtw_install/system_requirements.md
Labels: March21, size/S

#1745 [RDAPI-22182] HSTS Release Note
  content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
Labels: March21, more info needed

#1729 RDAPI-23679 - Updated March release notes with Common Criteria changes
  content/en/docs/apim_administration/apigtw_admin/manage_user_access.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
  content/en/docs/apim_policydev/apigw_kps/how_to_use_kpsadmin_command.md
  content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
Labels: March21, more info needed, size/M

#1755 APIGOV-16518 - Azure command typo
  content/en/docs/central/connect-azure-gateway/deploy-your-agents-with-amplify-cli.md
Labels: netlify-cms/pending_review, size/XS

#1751 APIGOV-17765 Update CLI docs with info regarding new Axway Central CLI Package; change 'AMPLIFY' to 'Amplify'
  content/en/_index.html
  content/en/docs/_index.md
  content/en/docs/catalog/manage_subscriptions.md
  content/en/docs/central/backend_TLS.md
  content/en/docs/central/cli_central/_index.md
  content/en/docs/central/cli_central/cli_apiservices.md
  content/en/docs/central/cli_central/cli_command_reference.md
  content/en/docs/central/cli_central/cli_create_fetch_resources.md
  content/en/docs/central/cli_central/cli_environments.md
  content/en/docs/central/cli_central/cli_install.md
  content/en/docs/central/cli_central/cli_proxy_flow.md
  content/en/docs/central/cli_central/cli_publish.md
  content/en/docs/central/connect-api-manager/_index.md
  content/en/docs/central/connect-api-manager/deploy-your-agents-with-amplify-cli.md
  content/en/docs/central/connect-api-manager/prepare-amplify-central.md
  content/en/docs/central/connect-aws-gateway/_index.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-quickstart.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-with-amplify-cli.md
  content/en/docs/central/connect-aws-gateway/prepare-amplify-central-1.md
  content/en/docs/central/connect-azure-gateway/_index.md
  content/en/docs/central/connect-azure-gateway/deploy-your-agents-with-amplify-cli.md
  content/en/docs/central/env_gw_mgmt/_index.md
  content/en/docs/central/env_gw_mgmt/add_api_service.md
  content/en/docs/central/env_gw_mgmt/add_endpoints.md
  content/en/docs/central/env_gw_mgmt/environment_agent_resources.md
  content/en/docs/central/env_gw_mgmt/publish_endpoint_to_catalog.md
  content/en/docs/central/env_gw_mgmt/view_environments.md
  content/en/docs/central/integrate_with_webhooks.md
  content/en/docs/central/mesh_management/deploy-your-agents-with-the-amplify-cli.md
  content/en/docs/central/mesh_management/discover-apis-and-services.md
  content/en/docs/central/overview.md
  content/en/docs/central/proxy_rate_limit.md
  static/admin/config.js
  static/samples/central/sdkconsumerinstance.json
Labels: size/L

#1747 RDAPI-23130 Initial and final content added to Important Changes in March21 Release Notes
  content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
Labels: March21, size/S

#1712 Create March Amplify Central Release Notes
  content/en/docs/central/amplify_relnotes/20210331_ampc_relnotes.md
Labels: size/S

#1762 Change Release Notes filename
  content/en/docs/catalog/catalog_relnotes/20210331_catalog_relnotes.md
Labels: size/XS

#1749 RDAPI- 23632 - Changes to Cassandra Backup and Restore doc as a result of CC Cipher Scheme change
  content/en/docs/cass_admin/cassandra_bur.md
Labels: March21, size/S

#1754 RDAPI-23733 Update March21 Release Notes Fixed and Known Issues
  content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
Labels: March21, size/M
