Repository Axway/axway-open-docs, pull requests merged in 2021-04, with the labels that each got.

#1756 [RDAPI-23063] Adding to May2020 release note for PS future releases bug
  content/en/docs/apim_relnotes/20200530_apimgr_relnotes.md
Labels: size/XS

#1753 [RDAPI-23614] JWT Verify Filter update
  content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
Labels: March21, size/XS

#1759 Update Deprecated features and Summary for March 21 release note
  content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20210330_apip_relnotes.md
Labels: March21, size/XS

#1766 RMF-55 Add end of support EOS note to session Deprecated in the Nov20 release
  content/en/docs/apim_relnotes/20201130_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20201130_apip_relnotes.md
Labels: size/XS

#1765 Front matter inconsistencies
  content/en/docs/catalog/catalog_relnotes/20210130_catalog_relnotes.md
  content/en/docs/catalog/catalog_relnotes/20210226_catalog_relnotes.md
  content/en/docs/catalog/catalog_relnotes/20210331_catalog_relnotes.md
  content/en/docs/central/amplify_relnotes/20201030_ampc_relnotes.md
  content/en/docs/central/amplify_relnotes/20201130_ampc_relnotes.md
  content/en/docs/central/amplify_relnotes/20210131_ampc_relnotes.md
  content/en/docs/central/amplify_relnotes/20210228_ampc_relnotes.md
  content/en/docs/central/amplify_relnotes/20210331_ampc_relnotes.md
Labels: size/S

#1760 Update Yaml ES in release note
  content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
Labels: March21, size/XS

#1761 [RDAPI-23702] Updated changelog for Jan21 + Mar21 releases
  content/en/docs/apim_reference/allReleasesChangeLog.md
Labels: March21, size/M

#1711 Update String Replace filter documentation to include important usage notes and link to a KB example
  content/en/docs/apim_policydev/apigw_polref/utility_common.md
Labels: size/XS

#1767 [RDAPI-23703] Update system property page March21 release
  content/en/docs/apim_reference/system_props.md
Labels: March21

#1768 Fix wording choice from anti-virus to antivirus
  content/en/docs/apim_policydev/apigw_polref/virus_scanning.md
Labels: size/S

#1772 [RDAPI-23592] - Dropped support for MySQL 5.6
  content/en/docs/apim_installation/apigtw_install/system_requirements.md
Labels: March21, size/XS

#1736 Updates description of max bytes settings & transaction timeout in Remote Hosts
  content/en/docs/apim_policydev/apigw_gw_instances/general_remote_hosts.md
Labels: size/XS

#1737 Updates description of max bytes settings & transaction timeout in General Settings
  content/en/docs/apim_reference/general_settings.md
Labels: size/XS

#1738 Updates description of max bytes settings & transaction timeout in API Manager Settings
  content/en/docs/apim_reference/api_mgmt_config_web.md
Labels: size/XS

#1773 RDAPI-23803 Update GW/MGR March2021 Release Notes sustaining issues
  content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
Labels: March21, size/S

#1775 APIGOV-16518 - v7 agents service creation command update
  content/en/docs/central/connect-api-manager/gateway-administation.md
Labels: netlify-cms/pending_review, size/S

#1776 Update page in Connect API Manager “gateway-administation”
  content/en/docs/central/connect-api-manager/gateway-administation.md
Labels: netlify-cms/draft, size/XS

#1770 [RDAPI-21200] Sign NM certificate with external CA update
  content/en/docs/apim_administration/apigtw_admin/admin_node_mngr.md
Labels: March21, more info needed, size/M

#1778 Add common reference section for connected agents
  content/en/docs/central/connected_agent_common_reference/_index.md
  content/en/docs/central/connected_agent_common_reference/trace_redaction.md
  static/admin/config.js
Labels: size/S

#1777 RDAPI-23549 Update to Known Issues in Release Notes
  content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
Labels: March21, size/S

#1783 Adding known SSO user logout issue to march release notes
  content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
Labels: March21, size/XS

#1779 RDAPI-11932 Adds mail.mime.charset sytem property
  content/en/docs/apim_reference/system_props.md
Labels: size/XS

#1782 RDAPI-20474 Update to Fixed Issues in March21 Release Notes
  content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
Labels: March21, size/XS

#1786 RDAPI-23876 Update Know Issues on March 21 release - PS Can't upgrade NM or Analytics projects or feds
  content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
Labels: March21, size/XS

#1785 RMF-146 Delete section Summary from Release notes Jan and March 2021
  content/en/docs/apim_relnotes/20210130_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20210130_apip_relnotes.md
  content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20210330_apip_relnotes.md
Labels: March21, size/S

#1788 RMF-147 API Management March 21 release final tasks
  content/en/docs/apim_relnotes/20210130_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20210130_apip_relnotes.md
  content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20210330_apip_relnotes.md
  content/en/docs/apim_relnotes/20219999_apimgr_relnotes_template.md
  content/en/docs/apim_relnotes/20219999_apip_relnotes_template.md
Labels: March21, size/M

#1790 Add description to Connected agent - Common reference
  content/en/docs/central/connected_agent_common_reference/_index.md
Labels: size/XS

#1789 APIGOV-18384 - add new error code for API Manager agent
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
Labels: size/S

#1792 7.7 March 21 Merge developmar21 branch into master
  content/en/docs/apim_administration/apigtw_admin/admin_node_mngr.md
  content/en/docs/apim_administration/apigtw_admin/general_passphrase.md
  content/en/docs/apim_administration/apigtw_admin/manage_user_access.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_config.md
  content/en/docs/apim_administration/apiportal_admin/customize_page_content.md
  content/en/docs/apim_administration/apiportal_admin/localize_language.md
  content/en/docs/apim_installation/apigtw_install/metrics_db_install.md
  content/en/docs/apim_installation/apigtw_install/system_requirements.md
  content/en/docs/apim_installation/apigtw_install/verify_downloads.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
  content/en/docs/apim_installation/apiportal_install/install_dependencies.md
  content/en/docs/apim_installation/apiportal_install/install_unattended.md
  content/en/docs/apim_policydev/apigw_gw_instances/configure_http_strict_transport_security.md
  content/en/docs/apim_policydev/apigw_kps/how_to_use_kpsadmin_command.md
  content/en/docs/apim_policydev/apigw_poldev/gs_project.md
  content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
  content/en/docs/apim_reference/allReleasesChangeLog.md
  content/en/docs/apim_reference/api_mgmt_config_web.md
  content/en/docs/apim_reference/config_files_reference.md
  content/en/docs/apim_reference/managedomain_ref.md
  content/en/docs/apim_reference/system_props.md
  content/en/docs/apim_relnotes/20210130_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20210130_apip_relnotes.md
  content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20210330_apip_relnotes.md
  content/en/docs/apim_relnotes/20219999_apimgr_relnotes_template.md
  content/en/docs/apim_relnotes/20219999_apip_relnotes_template.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_conversion_errors.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_validation_errors.md
  content/en/docs/apim_yamles/yamles_packaging_deployment.md
  content/en/docs/apim_yamles/yamles_structure.md
  content/en/docs/apimgmt_security/c_secgd_bp_intro.md
  content/en/docs/apimgmt_security/c_secgd_config_secconfig.md
  content/en/docs/apimgmt_security/c_secgd_features_intro.md
  content/en/docs/cass_admin/cassandra_bur.md
  content/en/docs/contribution_guidelines/bestpracticedevdoc.md
  static/Images/docbook/images/general/hsts1.png
  static/Images/docbook/images/general/hsts2.png
  static/Images/docbook/images/general/hsts3.png
  static/Images/docbook/images/general/hsts4.png
  static/Images/docbook/images/general/hsts5.png
Labels: size/XL

#1796 APIGOV-17971 - add AWS configuration error code
  content/en/docs/central/connect-aws-gateway/tips-and-troubleshooting.md
Labels: size/XS

#1799 APIGOV-18177 - add new config option and error code
  content/en/docs/central/connect-api-manager/agent-variables.md
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
Labels: size/S

#1801 APIGOV-18351 - remove flag for subscriptoinsissuenewcredentials
  content/en/docs/central/connect-api-manager/agent-variables.md
  content/en/docs/central/connect-api-manager/subscription-for-the-consumer.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-1.md
  content/en/docs/central/connect-aws-gateway/subscription-for-the-consumer.md
Labels: size/S

#1800 Change Amplify Central codeowner
  .github/CODEOWNERS
Labels: size/XS

#1781 Updates information on content encoding in “common_compress_encoding”
  content/en/docs/apim_policydev/apigw_gw_instances/common_compress_encoding.md
Labels: size/XS

#1804 RMF-150 Configure files for May 21 develop branch
  .github/workflows/ciworkflow.yml
  .github/workflows/merge_to_develop.yml
  layouts/partials/page-meta-links.html
  static/admin/config.js
Labels: size/S

#1787 [RDAPI-19882] Adding note about maximum URL length
  content/en/docs/apim_policydev/apigw_gw_instances/general_services.md
Labels: size/XS

#1802 APIGOV-16518 - Add traceability agent limitation when APIM is Dockerized
  content/en/docs/central/connect-api-manager/agent-variables.md
  content/en/docs/central/connect-api-manager/gateway-administation.md
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
Labels: size/S

#1793 RDAPI-22355 Dependency view update on API management user roles
  content/en/docs/api_mgmt_overview/key_concepts/api_mgmt_orgs_roles.md
Labels: size/XS

#1794 RDAPI-22355 - Dependency View update on Manage access to APIs
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_admin.md
Labels: size/XS

#1815 APIGOV-18234 - add new APIGATEWAY_HEALTHCHECKURL
  content/en/docs/central/connect-api-manager/agent-variables.md
Labels: size/XS

#1784 Update Connect to a database URL section with Example Setup for TLS with MySQL Server
  content/en/docs/apim_installation/apigtw_install/metrics_db_install.md
Labels: more info needed, size/S

#1797 [RDAPI-23702] Adding important changes column to changelog
  content/en/docs/apim_reference/allReleasesChangeLog.md
Labels: more info needed, size/M

#1817 APIGOV-18517 - add new healthcheck vars
  content/en/docs/central/connect-api-manager/agent-variables.md
Labels: size/XS

#1820 Fix typo
  content/en/docs/central/connected_agent_common_reference/trace_redaction.md
Labels: size/XS

#1795 RDAPI-22355 - Section describing API Access (Grant Access, Dependency, and Revoke Access)
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_virtualize_web.md
  static/Images/docbook/images/api_mgmt/dependency-view-applications-tab.png
  static/Images/docbook/images/api_mgmt/dependency-view-default.png
  static/Images/docbook/images/api_mgmt/grant-api-access-example.png
Labels: more info needed, size/M

#1824 Create release notes pages for May21
  content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20210530_apip_relnotes.md
Labels: size/M

#1791 Updates Jan 2021 release notes to include more information on the Content Security Policy Header
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
  content/en/docs/apim_relnotes/20210130_apimgr_relnotes.md
Labels: more info needed, size/S

#1819 APIGOV-18489 Add Upgrade an agent
  content/en/docs/central/connected_agent_common_reference/upgrade_agent.md
Labels: size/M

#1825 [RDAPI-23544] - Use MariaDB connector for MariaDB instead of the MySQ…
  content/en/docs/apim_installation/apigtw_install/metrics_db_install.md
  content/en/docs/apim_policydev/apigw_external_connections/common_db_conf.md
  content/en/docs/apimanager_analytics/analytics_config.md
Labels: May21, size/S

#1822 RDAPI-22830 Issue with unicode files on centos8
  content/en/docs/apim_installation/apigtw_install/system_requirements.md
Labels: May21, size/XS

#1826 Updates instructions for editing the ANM config for Active Directory
  content/en/docs/apim_administration/apigtw_admin/general_rbac_ad_ldap.md
Labels: size/S

#1827 Updates instructions for editing the ANM config for OpenLDAP
  content/en/docs/apim_administration/apigtw_admin/general_rbac_openldap.md
Labels: size/S

#1828 (RDAPI-22247) Updates entry on static content providers / allow directory listings
  content/en/docs/apim_policydev/apigw_gw_instances/general_relative_path.md
Labels: size/S

#1831 RDAPI-21618 - Add a new option to the kpsadmin command which allows the user set the Cassandra old passphrase at the command line.
  content/en/docs/apim_policydev/apigw_kps/how_to_use_kpsadmin_command.md
Labels: May21, size/XS

#1833 Updates section on trace logging to link to section on redaction
  content/en/docs/apim_administration/apigtw_admin/logging.md
Labels: size/XS

#1829 RDAPI-21747 - Update Embedded ActiveMQ Settings
  content/en/docs/apim_reference/general_activemq_settings.md
Labels: May21, more info needed, size/S

#1835 Update page in APIP install section “secure_harden_portal”
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
Labels: size/XS

#1839 RDAPI-22247 Fix typo
  content/en/docs/apim_policydev/apigw_gw_instances/general_relative_path.md
Labels: size/XS
