Repository Axway/axway-open-docs, pull requests merged in 2021-08, with the labels that each got.

#2004 IAP-4538- Add a note for API portal docker container not suported in HA
  content/en/docs/apim_installation/apiportal_docker/_index.md
  content/en/docs/apiportal_ha/_index.md
Labels: size/XS

#2010 add more description for finalStatus event log field with possible values
  content/en/docs/apim_reference/log_global_settings.md
Labels: size/XS

#2013 Transaction log settings - Update page formatting
  content/en/docs/apim_reference/log_global_settings.md
Labels: size/M

#2011 APIGOV-19825 Add platform service account
  content/en/docs/central/connect-api-manager/_index.md
  content/en/docs/central/connect-api-manager/deploy-your-agents-with-amplify-cli.md
  content/en/docs/central/connect-aws-gateway/_index.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-with-amplify-cli.md
  content/en/docs/central/connect-azure-gateway/_index.md
  content/en/docs/central/connect-azure-gateway/deploy-your-agents-with-amplify-cli.md
Labels: size/S

#2017 RDAPI-25027 - Typo in Cassandra logger settings
  content/en/docs/cass_admin/cassandra_ops.md
Labels: August21, size/XS

#2018 RDAPI-25029 - Update Cassandra install doc to remove apitester from example command
  content/en/docs/apim_installation/apigtw_install/cassandra_install.md
Labels: August21, size/XS

#2019 RDAPI-25026 - Update references in Cassandra documentation from 2.2.x to 3.11.x
  content/en/docs/cass_admin/cassandra_bestpractices.md
Labels: August21, size/XS

#2008 Update Enable traces for SSO - change Level from Erro to Debut
  content/en/docs/apim_administration/apimgr_sso/c_saml_trouble.md
Labels: size/XS

#2020 RDAPI-25026 - Update references in Cassandra documentation from 2.2.x to 3.11.x
  content/en/docs/cass_admin/cassandra_ops.md
Labels: August21, size/XS

#2021 RDAPI-25026 - Update references in Cassandra documentation from 2.2.x to 3.11.x
  content/en/docs/cass_admin/cassandra_manage.md
Labels: August21, size/XS

#2022 RDAPI-25026 - Update references in Cassandra documentation from 2.2.x to 3.11.x
  content/en/docs/apim_reference/cassandra_settings.md
Labels: August21, size/XS

#1996 Fix typo on Mapping syntax section
  content/en/docs/apim_administration/apiportal_sso/sso_mapping.md
Labels: netlify-cms/draft, size/XS

#2002 Create July Central RelNotes
  content/en/docs/central/amplify_relnotes/20210731_ampc_agents_relnotes.md
  content/en/docs/central/amplify_relnotes/20210731_ampc_relnotes.md
  content/en/docs/central/amplify_relnotes/_index.md
Labels: size/M

#2023 APIGOV-16307 CENTRAL_TEAM variable description change
  content/en/docs/central/connect-api-manager/agent-variables.md
  content/en/docs/central/connect-api-manager/deploy-your-agents-with-amplify-cli.md
  content/en/docs/central/connect-api-manager/gateway-administation.md
Labels: size/XS

#2025 APIGOV-19893 Add Data exchanged - Traceability Agent information
  content/en/docs/central/connect-api-manager/network-traffic-apimanager.md
  content/en/docs/central/connect-aws-gateway/network-traffic-aws.md
  content/en/docs/central/connect-azure-gateway/network-traffic-azure.md
Labels: size/M

#2024 APIGOV-11915 - add error messages
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
  content/en/docs/central/connect-aws-gateway/tips-and-troubleshooting.md
  content/en/docs/central/connect-azure-gateway/tips-and-troubleshooting.md
Labels: size/XS

#2026 APIGOV-19786 Offline usage report
  content/en/docs/central/connect-api-manager/agent-variables.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-1.md
  content/en/docs/central/connect-azure-gateway/agent-variables.md
  content/en/docs/central/connected_agent_common_reference/traceability_usage.md
Labels: size/S

#2015 [RDAPI-24836] Adding ELK release note and doc section
  content/en/docs/apim_administration/apigtw_admin/logging.md
  content/en/docs/apim_relnotes/20210830_apimgr_relnotes.md
Labels: more info needed, size/S, August21

#2027 APIGOV-19715 Combine API Manager, AWS Gateway, Azure Gateway Manage subscription …
  content/en/docs/central/connect-api-manager/subscription-for-the-consumer.md
  content/en/docs/central/connect-aws-gateway/subscription-for-the-consumer.md
  content/en/docs/central/connected_agent_common_reference/manage_subscription_workflow.md
  content/en/docs/central/connected_agent_common_reference/secure_config.md
Labels: size/XL

#2033 Central CLI - Use relative path to download scripts
  content/en/docs/central/cli_central/cli_environments.md
Labels: size/XS

#2034 Revert PR-2033 "Central CLI - Use relative path to download scripts"
  content/en/docs/central/cli_central/cli_environments.md
Labels: size/XS

#2029 [RDAPI-24997] LDAP RBAC filter updated.
  content/en/docs/apim_policydev/apigw_polref/authz_common.md
  static/Images/docbook/images/content/ldapattributeauthzfilter.png
Labels: August21

#2028 [RDAPI-24997] Compare Attribute filter updated.
  content/en/docs/apim_policydev/apigw_polref/attributes_manipulate.md
  static/Images/docbook/images/content/compareattributefilter.png
Labels: size/XS, August21

#2035 authTemplate typo for email template
  content/en/docs/central/connect-api-manager/gateway-administation.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-1.md
  content/en/docs/central/connected_agent_common_reference/manage_subscription_workflow.md
Labels: size/S

#2038 Deleted unused agent topics
  content/en/docs/central/connect-api-manager/deploy-your-agents-quickstart.md
  content/en/docs/central/connect-api-manager/deploy-your-agents.md
  content/en/docs/central/connect-api-manager/discovery-agent-flags.md
  content/en/docs/central/connect-api-manager/impact-of-unpublishing-an-api.md
  content/en/docs/central/connect-api-manager/prepare-amplify-central.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-quickstart.md
  content/en/docs/central/connect-aws-gateway/impact-of-deleting-an-api-stage.md
  content/en/docs/central/connect-aws-gateway/prepare-amplify-central-1.md
  content/en/docs/central/connect-aws-gateway/prepare-aws-api-gateway.md
Labels: size/XL

#2039 Typo for starting Traceability agent
  content/en/docs/central/connect-api-manager/deploy-your-agents-with-amplify-cli.md
Labels: size/S, netlify-cms/pending_review

#2040 Update page in Axway Central CLI “cli_environments”
  content/en/docs/central/cli_central/cli_environments.md
Labels: size/XS, netlify-cms/draft

#2045 RMF-220 Create internal page for Zoomin to test relative links to the Samples folder
  content/en/docs/contribution_guidelines/linktosamplefolder.md
Labels: size/S

#2048 RMF-220 Add new structure for tests
  content/en/docs/contribution_guidelines/linktosamplefolder.md
  static/Images/samplestest/Central/create_environments2.json
Labels: size/S

#2049 RMF-220 More updates
  content/en/docs/contribution_guidelines/linktosamplefolder.md
Labels: size/S

#2050 Update page in AMPLIFY Release notes section “20210731_ampc_agents_relnotes”
  content/en/docs/central/amplify_relnotes/20210731_ampc_agents_relnotes.md
Labels: size/XS, netlify-cms/pending_publish

#2054 APIGOV-20072 - update offline usage reporting documentation
  content/en/docs/central/connect-api-manager/agent-variables.md
  content/en/docs/central/connected_agent_common_reference/traceability_usage.md
Labels: size/S

#2031 RDAPI-25025 - Updated Debian Cassandra as a Service script
  content/en/docs/cass_admin/cassandra_manage.md
  static/samples/apimanagement/cassandra/cassandra.centos.service
  static/samples/apimanagement/cassandra/cassandra.debian.service
Labels: size/M, August21

#2036 RDAPI-20509 Add YAML Web UI deployment info
  content/en/docs/apim_administration/apigtw_admin/managetopology.md
  content/en/docs/apim_relnotes/20210830_apimgr_relnotes.md
Labels: size/XS, August21

#2037 [RDAPI-24689] Retire McAfee anti virus filter
  content/en/docs/apim_policydev/apigw_polref/virus_scanning.md
  content/en/docs/apim_relnotes/20210830_apimgr_relnotes.md
Labels: size/XS, August21

#2044 Fix typo for this system property
  content/en/docs/apim_reference/system_props.md
Labels: size/XS

#1990 RDAPI-24811 - Updated Cassandra Upgrade guide for version 3.11.11
  content/en/docs/apim_installation/apigw_upgrade/upgrade_cassandra.md
  content/en/docs/apim_reference/system_props.md
  content/en/docs/cass_admin/cassandra_troubleshooting.md
Labels: more info needed, size/M, August21

#2042 [RDAPI-25030] - Updating Cassandra multi-DC (and any linked docs) for change in Cassandra version (3.11.11)
  content/en/docs/apim_installation/apigtw_install/cassandra_install.md
  content/en/docs/apimgmt_multi_dc/multi_datacenter_config.md
Labels: size/S, August21

#2058 Condor urls update for traceability usage
  content/en/docs/central/connected_agent_common_reference/traceability_usage.md
Labels: size/XS, netlify-cms/draft

#2055 [RDAPI-25137] Add missing requirements for APIGW Analytics
  content/en/docs/apim_installation/apigtw_install/system_requirements.md
Labels: size/S, August21

#2043 Improve the troubleshooting guides
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
  content/en/docs/central/connect-aws-gateway/tips-and-troubleshooting.md
  content/en/docs/central/connect-azure-gateway/tips-and-troubleshooting.md
Labels: size/L

#2047 RDAPI-25028 Rewrote TLS/SSL section to be clearer and more informative for the setup-cassandra script
  content/en/docs/cass_admin/cassandra_setup_script.md
Labels: size/S, August21

#2053 [RDAPI-25149] Removing .dll files is no longer a manual step
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
Labels: size/XS, August21

#2059 Create topic Support Policy for Amplify Agents and Amplify Agent SDK
  content/en/docs/central/amplify_relnotes/agent_agentsdk_support_policy.md
  static/Images/central/community_agents_sdk.png
Labels: size/S

#2060 Update page in AMPLIFY Release notes section “agent_agentsdk_support_policy”
  content/en/docs/central/amplify_relnotes/agent_agentsdk_support_policy.md
  static/Images/central/amplify_relnotes/release_matrix.png
Labels: size/S, netlify-cms/pending_publish

#2051 APIGOV-20141 New SaaS API Gateway Management section
  content/en/docs/central/saas_api_gateway/_index.md
  content/en/docs/central/saas_api_gateway/backend_TLS.md
  content/en/docs/central/saas_api_gateway/backend_authn.md
  content/en/docs/central/saas_api_gateway/cft_profile.md
  content/en/docs/central/saas_api_gateway/feauth_oauth.md
  content/en/docs/central/saas_api_gateway/fundamental_concepts.md
  content/en/docs/central/saas_api_gateway/proxy_rate_limit.md
  content/en/docs/central/saas_api_gateway/quickstart.md
  content/en/docs/central/saas_api_gateway/secure_api_jwt.md
  static/admin/config.js
Labels: size/S

#2056 RDAPI-24970 Filter requirements
  content/en/docs/apim_policydev/apigw_polref/content_max_messages.md
Labels: size/XS, August21

#2073 APIP August 21 release notes - New features and enhancements
  content/en/docs/apim_relnotes/20210830_apip_relnotes.md
Labels: size/S, August21

#2069 RDAPI-24517 Add SameSite cookie attribute description
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_config_ps.md
Labels: size/S, netlify-cms/pending_publish

#2077 RDAPI-24517 Add information about SameSite parameter
  content/en/docs/apim_policydev/apigw_oauth/gw_oauth_resource_server.md
Labels: size/S, netlify-cms/pending_publish

#2072 Amplify Central August Release Notes
  content/en/docs/central/amplify_relnotes/20210831_ampc_agents_relnotes.md
  content/en/docs/central/amplify_relnotes/20210831_ampc_relnotes.md
Labels: size/M
