Repository Axway/axway-open-docs, pull requests merged in 2021-06, with the labels that each got.

#1896 RDAPI-24302 - Added advisory to increase Transaction Timeout when importing large .dat files in API Manager
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_consume.md
Labels: May21, size/XS

#1883 RDAPI-24366 - Documentation Review for May21
  content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
Labels: May21, size/S

#1904 RDAPI-24402 Add note to Provide the passphrase automatically at startup using a script
  content/en/docs/apim_administration/apigtw_admin/general_passphrase.md
Labels: size/S

#1906 RDAPI-24284 Modsecurity Alert policy not triggered in DetectionOnly m…
  content/en/docs/apim_administration/apigtw_admin/admin_waf.md
Labels: size/XS

#1866 Create May Release Notes
  content/en/docs/central/amplify_relnotes/20210531_ampc_relnotes.md
Labels: size/S

#1907 IAP-4250 Add list of fixed issues to May 21 release notes
  content/en/docs/apim_relnotes/20210530_apip_relnotes.md
Labels: May21, size/S

#1900 RDAPI-24314 Update May21 fixed/known issues in release notes.
  content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
Labels: May21, size/M

#1889 IAP-4298 - Describe CSP in API Portal;
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
Labels: May21, size/S

#1912 [RDAPI-14603] Moving CSP header related to API Gateway and Manager to 'Security Configuration' section.
  content/en/docs/apimgmt_security/c_secgd_config_secconfig.md
Labels: May21, size/XS

#1901 RDAPI-24374 Database driver documentation update and May 21 Deprecated features
  content/en/docs/apim_installation/apigtw_install/metrics_db_install.md
  content/en/docs/apim_installation/apigtw_install/system_requirements.md
  content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
Labels: May21, size/XS

#1903 IAP-3508 Enhance unattended mode installer/uninstaller to use a config file for parameters
  content/en/docs/apim_installation/apiportal_install/install_unattended.md
Labels: May21, size/XS

#1915 RDAPI-14603 Make description of CSP consistent between API Gateway and APIP
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
  content/en/docs/apimgmt_security/c_secgd_config_secconfig.md
Labels: May21, size/XS

#1916 RDAPI-24222 update for release notes fixed issues
  content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
Labels: May21, size/XS

#1917 API Portal May 21 Update description of New Features section
  content/en/docs/apim_relnotes/20210530_apip_relnotes.md
Labels: size/XS

#1918 RDAPI-24337 update for release notes fixed issues
  content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
Labels: May21, size/XS

#1922 7.7 May 21 Merge developmay21 branch into master
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_config.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_consume.md
  content/en/docs/apim_administration/apiportal_admin/customize_page_content.md
  content/en/docs/apim_installation/apigtw_install/metrics_db_install.md
  content/en/docs/apim_installation/apigtw_install/system_requirements.md
  content/en/docs/apim_installation/apiportal_install/install_unattended.md
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
  content/en/docs/apim_policydev/apigw_external_connections/common_db_conf.md
  content/en/docs/apim_policydev/apigw_gw_instances/configure_http_strict_transport_security.md
  content/en/docs/apim_policydev/apigw_gw_instances/general_ftp_scanner.md
  content/en/docs/apim_policydev/apigw_kps/how_to_use_kpsadmin_command.md
  content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
  content/en/docs/apim_policydev/apigw_polref/routing_additional.md
  content/en/docs/apim_reference/general_activemq_settings.md
  content/en/docs/apim_reference/system_props.md
  content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20210530_apip_relnotes.md
  content/en/docs/apim_yamles/_index.md
  content/en/docs/apim_yamles/apim_yamles_cli/_index.md
  content/en/docs/apim_yamles/apim_yamles_cli/yamles_cli_convert.md
  content/en/docs/apim_yamles/apim_yamles_cli/yamles_cli_importexport.md
  content/en/docs/apim_yamles/apim_yamles_cli/yamles_cli_upgrade.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_team_development.md
  content/en/docs/apimanager_analytics/analytics_config.md
  content/en/docs/apimgmt_security/c_secgd_config_secconfig.md
  content/en/docs/cass_admin/cassandra_setup_script.md
Labels: May21, size/XL

#1923 RDAPI-24475 Updates for API Gtw May 21 release
  content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
Labels: May21, size/M

#1924 RDAPI-24381 yaml schema specs Replaces PR-1919
  content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_yaml_schema.md
  content/en/docs/apim_yamles/yamles_environmentalization.md
  content/en/docs/apim_yamles/yamles_structure.md
Labels: May21, size/M

#1875 Update page on redaction to clarify use of HTTP Redactors, location of redaction.xml
  content/en/docs/apim_administration/apigtw_admin/admin_redactors.md
Labels: size/XS

#1928 RDAPI-23867 Remove issue from Known Issues in May21 Release Notes
  content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
Labels: May21, size/XS

#1934 Docs - Netlify deploys are failing for all sites
  package-lock.json
  package.json
Labels: size/XL

#1935 RDAPI-24501 Update section Install NodeJS and PostCSS on Contributions Guidelines
  content/en/docs/contribution_guidelines/setup_work_locally.md
Labels: size/XS

#1926 Update steps for API Gateway Analytics update
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
Labels: size/XS

#1925 remove change passphrase API Manager limitation
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
Labels: size/XS

#1929 KPS Scripting API - Delete instruction to configure Cassandra with Read/Write Consistency Level of ONE
  content/en/docs/apim_policydev/apigw_kps/kps_script_api.md
Labels: size/XS

#1938 RDAPI-24271 update fixed issues in May21 Release Note
  content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
Labels: size/XS

#1931 APIGOV-19118 update axway central CLI get command output to show updated r…
  content/en/docs/central/cli_central/cli_apiservices.md
  content/en/docs/central/cli_central/cli_create_fetch_resources.md
  content/en/docs/central/connected_agent_common_reference/upgrade_agent.md
  content/en/docs/central/env_gw_mgmt/environment_agent_resources.md
  content/en/docs/central/mesh_management/traceability_agent_configuration.md
Labels: size/M

#1936 Update page in APIM ref section “allReleasesChangeLog”
  content/en/docs/apim_reference/allReleasesChangeLog.md
Labels: May21, size/S

#1941 RMF-145 Update link to AWS Integration Guide
  content/en/docs/apim_policydev/apigw_gw_instances/general_aws_poller.md
Labels: size/XS

#1942 Update page in Axway Central CLI “cli_create_fetch_resources”
  content/en/docs/central/cli_central/cli_create_fetch_resources.md
Labels: netlify-cms/pending_publish, size/XS

#1943 RMF-190 Update config files for Aug 21 development branch
  .github/workflows/ciworkflow.yml
  .github/workflows/merge_to_develop.yml
  layouts/partials/page-meta-links.html
  static/admin/config.js
Labels: size/S

#1949 RMF-190 Update page in glossary section
  content/en/docs/glossary/_index.md
Labels: netlify-cms/pending_publish, size/S

#1954 RMF-190 Create release notes pages for Aug 21 in development
  content/en/docs/apim_relnotes/20210830_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20210830_apip_relnotes.md
  content/en/docs/apim_relnotes/20219999_apimgr_relnotes_template.md
Labels: August21, size/L

#1937 RDAPI-24390 Zero downtime update page is really minimal downtime
  content/en/docs/apim_installation/apigw_upgrade/upgrade_zdu_overview.md
Labels: more info needed, size/S

#1950 Update page in Connect Azure Gateway “deploy-your-agents-with-amplify-cli”
  content/en/docs/central/connect-azure-gateway/deploy-your-agents-with-amplify-cli.md
Labels: netlify-cms/pending_review, size/XS

#1951 Update page in Connect Azure Gateway “_index”
  content/en/docs/central/connect-azure-gateway/_index.md
Labels: netlify-cms/pending_review, size/XS

#1960 APIGOV-19277 Create agent resources
  content/en/docs/central/cli_central/cli_command_reference.md
  content/en/docs/central/env_gw_mgmt/environment_agent_resources.md
Labels: size/S

#1956 RMF-184 Review YAML Schema page
  content/en/docs/apim_yamles/apim_yamles_references/yamles_yaml_schema.md
Labels: more info needed, size/M

#1962 RMF-184 Move YAML Syntax Considerations as a section within Edit the YAML configuration
  content/en/docs/apim_yamles/apim_yamles_references/yamles_syntax_considerations.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_yaml_schema.md
  content/en/docs/apim_yamles/yamles_edit.md
  content/en/docs/apim_yamles/yamles_structure.md
Labels: size/M

#1964 RMF-194 Fix broken link to YAML Entity Store course
  content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
Labels: May21, size/XS

#1959 APIGOV-18650 - add open traffic config settings
  content/en/docs/central/connect-api-manager/agent-variables.md
  content/en/docs/central/connect-api-manager/deploy-your-agents.md
  content/en/docs/central/connect-api-manager/discovery-agent-flags.md
  content/en/docs/central/connect-api-manager/gateway-administation.md
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
Labels: size/M

#1963 RDAPI-24557 - Update kpsadmin documentation to include new scripting commands for table CRUD and recreate
  content/en/docs/apim_policydev/apigw_kps/how_to_use_kpsadmin_command.md
Labels: August21, size/S

#1961 Update section on Execute External Process
  content/en/docs/apim_policydev/apigw_polref/utility_additional.md
Labels: size/XS

#1965 APIGOV-19402 - Add bool to sendAllTraffic to be reported
  content/en/docs/central/connect-api-manager/agent-variables.md
  content/en/docs/central/connect-api-manager/gateway-administation.md
Labels: size/S

#1966 APIGOV-18930 - Azure Traceability Agent upgrade procedure
  content/en/docs/central/connected_agent_common_reference/upgrade_agent.md
Labels: netlify-cms/draft, size/M

#1955 Create 20210630 AMPC Release Notes
  content/en/docs/central/amplify_relnotes/20210630_ampc_relnotes.md
Labels: size/S

#1967 RDAPI-24557 Manage KPS editorial and formatting updates
  content/en/docs/apim_policydev/apigw_kps/how_to_use_kpsadmin_command.md
Labels: August21, size/S

#1958 [RDAPI-23557] Adding flags 'multi' and 'utf' to regex redaction
  content/en/docs/apim_administration/apigtw_admin/admin_redactors.md
Labels: August21, more info needed, size/XS

#1969 RDAPI-24390 ZDU Clarify text about when to use sample scripts
  content/en/docs/apim_installation/apigw_upgrade/upgrade_zdu_overview.md
Labels: size/XS

#1968 Create page in AMPLIFY Unified Catalog Release notes section “amplify-unified-catalog-june-release-notes”
  content/en/docs/catalog/catalog_relnotes/20210631_catalog_relnotes.md
Labels: needs push to prod

#1970 Change filename to meet naming conventions
  content/en/docs/catalog/catalog_relnotes/20210531_catalog_relnotes.md
Labels: size/XS
