Repository Axway/axway-open-docs, pull requests merged in 2021-02, with the labels that each got.

#1546 Add CLI command reference docs page; update API Services docs page; add create/fetch docs page with more sample files and examples
  content/en/docs/central/cli_central/cli_apiservices.md
  content/en/docs/central/cli_central/cli_command_reference.md
  content/en/docs/central/cli_central/cli_create_fetch_resources.md
Labels: more info needed, size/M

#1570 Create page in AMPLIFY Unified Catalog “unified-catalog-january-2021-release-notes”
  content/en/docs/catalog/unified-catalog-january-2021-release-notes.md
  content/en/docs/catalog/unified-catalog-november-2020-release-notes.md
Labels: size/XS

#1606 APIGOV-17429 Change AMPLIFY to Amplify
  content/en/docs/central/connect-api-manager/Agent-security-api-manager.md
  content/en/docs/central/connect-api-manager/_index.md
  content/en/docs/central/connect-api-manager/agent-variables.md
  content/en/docs/central/connect-api-manager/deploy-your-agents-quickstart.md
  content/en/docs/central/connect-api-manager/deploy-your-agents-with-amplify-cli.md
  content/en/docs/central/connect-api-manager/deploy-your-agents.md
  content/en/docs/central/connect-api-manager/discovery-agent-flags.md
  content/en/docs/central/connect-api-manager/filtering-apis-to-be-discovered.md
  content/en/docs/central/connect-api-manager/gateway-administation.md
  content/en/docs/central/connect-api-manager/impact-of-unpublishing-an-api.md
  content/en/docs/central/connect-api-manager/network-traffic-apimanager.md
  content/en/docs/central/connect-api-manager/prepare-amplify-central.md
  content/en/docs/central/connect-api-manager/subscription-for-the-consumer.md
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
Labels: size/M

#1590 Update page in APIM release note section “20210130_apimgr_relnotes”
  content/en/docs/apim_relnotes/20210130_apimgr_relnotes.md
Labels: more info needed, size/XS

#1608 APIGOV-17429 Change AMPLIFY to Amplify
  content/en/docs/central/connect-aws-gateway/_index.md
  content/en/docs/central/connect-aws-gateway/agent-security-aws.md
  content/en/docs/central/connect-aws-gateway/cloud-administration-operation.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-1.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-quickstart.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-with-amplify-cli.md
  content/en/docs/central/connect-aws-gateway/filtering-apis-to-be-discovered-1.md
  content/en/docs/central/connect-aws-gateway/impact-of-deleting-an-api-stage.md
  content/en/docs/central/connect-aws-gateway/network-traffic-aws.md
  content/en/docs/central/connect-aws-gateway/prepare-amplify-central-1.md
  content/en/docs/central/connect-aws-gateway/prepare-aws-api-gateway.md
  content/en/docs/central/connect-aws-gateway/subscription-for-the-consumer.md
  content/en/docs/central/connect-aws-gateway/tips-and-troubleshooting.md
  content/en/docs/central/connect-azure-gateway/_index.md
  content/en/docs/central/connect-azure-gateway/agent-variables.md
  content/en/docs/central/connect-azure-gateway/deploy-your-agents-with-amplify-cli.md
  content/en/docs/central/connect-azure-gateway/manage-subscriptions.md
  content/en/docs/central/connect-azure-gateway/tips-and-troubleshooting.md
Labels: size/L

#1605 Update page in Mesh management “discover-apis-and-services”
  content/en/docs/central/mesh_management/discover-apis-and-services.md
Labels: size/XS

#1609 APIGOV-17429 Update AMPLIFY to Amplify in images
  static/Images/central/connect-api-manager/ServiceDiscoveryAPIM.png
  static/Images/central/connect-api-manager/servicediscoveryapim.png
  static/Images/central/connect-aws-gateway/aws-discovery-agent_v2.png
  static/Images/central/connect-aws-gateway/aws-traceability-agent_v2.png
  static/Images/central/connect-azure-gateway/discoveryagent.png
  static/Images/central/connect-azure-gateway/traceabilityagent.png
Labels: size/XS

#1610 APIGOV-17429 Change AMPLIFY to Amplify in Central RN
  content/en/docs/central/amplify_relnotes/20201030_ampc_relnotes.md
  content/en/docs/central/amplify_relnotes/_index.md
  content/en/docs/central/amplify_relnotes/amplify-central-november-2020-release-notes.md
Labels: size/M

#1615 RDAPI-23183 OpenDocs: automate updating developer branch versions
  scripts/update_dev_branch_name.sh
Labels: size/S

#1616 RMF-107 Update dev branch name in configuration files
  .github/workflows/ciworkflow.yml
  layouts/partials/page-meta-links.html
  static/admin/config.js
Labels: size/S

#1617 RMF-107 Recreate merge workflow
  .github/workflows/merge_to_develop.yml
Labels: size/S

#1624 Update known issues with RDAPI-21363 and RDAPI-22218 in APIM release note section “20210130_apimgr_relnotes”
  content/en/docs/apim_relnotes/20210130_apimgr_relnotes.md
Labels: more info needed, size/XS

#1629 RMF-103 Create release notes structure for Unified Catalog
  content/en/docs/catalog/catalog_relnotes/20201130_catalog_relnotes.md
  content/en/docs/catalog/catalog_relnotes/20210130_catalog_relnotes.md
  content/en/docs/catalog/catalog_relnotes/_index.md
  static/admin/config.js
Labels: size/S

#1630 RMF-103 Update image folder in Catalog release notes collection
  static/admin/config.js
Labels: size/XS

#1633 Create Mar 21 Release note pages into developmar21 branch
  content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20210330_apip_relnotes.md
  content/en/docs/apim_relnotes/20219999_apimgr_relnotes_template.md
  content/en/docs/apim_relnotes/20219999_apip_relnotes_template.md
Labels: size/L

#1627 Fix broken links in Connect API Manager
  content/en/docs/central/connect-api-manager/Agent-security-api-manager.md
  content/en/docs/central/connect-api-manager/_index.md
  content/en/docs/central/connect-api-manager/deploy-your-agents-with-amplify-cli.md
  content/en/docs/central/connect-api-manager/gateway-administation.md
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
Labels: size/S

#1626 APIGOV-17480 Add section describing how to add an api service
  content/en/docs/central/env_gw_mgmt/_index.md
  content/en/docs/central/env_gw_mgmt/add_api_service.md
  content/en/docs/central/env_gw_mgmt/view_environments.md
Labels: more info needed, size/M

#1637 APIGOV-17201 Update CLI Kubernetes install steps, and resources used by the Kubernetes discovery agent
  content/en/docs/central/mesh_management/deploy-your-agents-with-the-amplify-cli.md
  content/en/docs/central/mesh_management/discover-apis-and-services.md
Labels: needs push to prod, size/S

#1628 IAP-3508 Add options file documentation
  content/en/docs/apim_installation/apiportal_install/install_unattended.md
Labels: size/S

#1648 Fix broken links from Connect AWS Gateway reorg
  content/en/docs/central/connect-aws-gateway/_index.md
  content/en/docs/central/connect-aws-gateway/agent-security-aws.md
  content/en/docs/central/connect-aws-gateway/cloud-administration-operation.md
  content/en/docs/central/connect-aws-gateway/deploy-your-agents-1.md
  content/en/docs/central/connect-aws-gateway/tips-and-troubleshooting.md
Labels: size/S

#1634 RDAPI-22974 Add section about crit Headers to JWT Verify filter
  content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
Labels: more info needed, size/S

#1640 RDAPI-22668 and RDAPI-22669 API Gateway should support Signature Payloads and Advanced JWS/T signing options
  content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
Labels: size/S

#1653 Create back-end REST API in APIM and APIP Overview - Review for Axway style and improve readability
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_register_web.md
  content/en/docs/apim_administration/apiportal_admin/apip_overview.md
Labels: size/S

#1663 RMF-115 Update Contribution guidelines
  content/en/docs/contribution_guidelines/_index.md
Labels: size/XS

#1654 Update page in Connect API Manager “gateway-administation”
  content/en/docs/central/connect-api-manager/gateway-administation.md
Labels: netlify-cms/draft, size/L

#1642 RDAPI-22833 - Add jersey level filter that reads rate limiting config and invalidates a session if the threshold is broken
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_config.md
Labels: size/S

#1645 Customized files need to be highlighted
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
Labels: more info needed, size/XS

#1652 (IAP-3998) Added instructions for removing MySQL password encryption
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
Labels: more info needed, size/XS

#1643 RDAPI-22833 - Update Mar21 Release Notes - New features and enhancements
  content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
Labels: size/XS

#1671 RDAPI-22833 New features and enhancements - review
  content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
Labels: size/XS

#1646 RDAPI-22904 Update list of System properties with com.axway.apimanager.user.tlds
  content/en/docs/apim_reference/system_props.md
Labels: size/XS

#1635 RDAPI-22974 Update March release notes with Crit header
  content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
Labels: more info needed, size/S

#1649 Create February Release Notes topic for Amplify Central
  content/en/docs/central/amplify_relnotes/20210228_ampc_relnotes.md
Labels: size/S
