Repository Axway/axway-open-docs, pull requests merged in 2021-09, with the labels that each got.

#2079 Update link to sample yaml
  content/en/docs/central/cli_central/build-an-asset-using-the-axway-central-cli.md
Labels: size/XS, netlify-cms/pending_review

#2081 Add a link to YAML Docs in release notes
  content/en/docs/apim_relnotes/20210830_apimgr_relnotes.md
Labels: August21

#2080 Update APIM release notes to add Elastic-Stack version
  content/en/docs/apim_relnotes/20210830_apimgr_relnotes.md
Labels: August21

#2084 APIGOV-20162 - reorganize Istio agent doc
  content/en/docs/central/mesh_management/_index.md
  content/en/docs/central/mesh_management/build_hybrid_env.md
  content/en/docs/central/mesh_management/deploy-your-agents-with-the-axway-cli.md
  content/en/docs/central/mesh_management/discover-apis-and-services.md
  content/en/docs/central/mesh_management/traceability_agent_configuration.md
  content/en/docs/central/mesh_management/using_redhat_openshift.md
  static/Images/central/hybrid_control_data_plane.png
Labels: size/S

#2082 APIGOV-20284 - update subject body with recommended if else tags
  content/en/docs/central/connect-api-manager/gateway-administation.md
  content/en/docs/central/connected_agent_common_reference/manage_subscription_workflow.md
Labels: size/M

#2075 RDAPI-25047 - Updated release notes for Cassandra Upgrade, ICAP Message Preview and APIM Unauthenticated req rate limiter
  content/en/docs/apim_policydev/apigw_external_connections/common_icap_conf.md
  content/en/docs/apim_reference/system_props.md
  content/en/docs/apim_relnotes/20210830_apimgr_relnotes.md
Labels: size/S, August21

#2086 RMF-230 Release notes Aug 21 update Documentation section
  content/en/docs/apim_relnotes/20210830_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20210830_apip_relnotes.md
Labels: size/S, August21

#2074 IAP-4480: create elasticsearch page ...
  content/en/docs/apim_installation/apiportal_install/install_software_elastic.md
Labels: size/S, August21

#2091 APIGOV-19450 - add details for helm deployment
  content/en/docs/central/connect-api-manager/deploy-your-agents-with-amplify-cli.md
Labels: size/XS, netlify-cms/draft

#2088 APIGOV-19801 - add missing error codes
  content/en/docs/central/connect-api-manager/tips-troubleshooting-and-limitations.md
  content/en/docs/central/connect-aws-gateway/tips-and-troubleshooting.md
  content/en/docs/central/connect-azure-gateway/tips-and-troubleshooting.md
Labels: size/L

#2087 API Portal Aug 21 release - Update Known issues section
  content/en/docs/apim_relnotes/20210830_apip_relnotes.md
Labels: size/S, August21

#2092 Update steps on Install API Portal software section
  content/en/docs/apim_installation/apiportal_install/install_software.md
Labels: size/XS, August21

#2093 RMF-230 General updates for completeness
  content/en/docs/apim_relnotes/20210830_apimgr_relnotes.md
Labels: size/M, August21

#2097 RMF-224 Customer fixed issues for Aug21 Release Notes
  content/en/docs/apim_relnotes/20210830_apimgr_relnotes.md
Labels: size/S, August21

#2094 [RDAPI-24851] [RDAPI-25249] Introduce new flags
  content/en/docs/apim_reference/system_props.md
Labels: size/XS, August21

#2099 APIP Aug 21 Add Known issue
  content/en/docs/apim_relnotes/20210830_apip_relnotes.md
Labels: size/XS, August21

#2098 Update install_software_elastic.md
  content/en/docs/apim_installation/apiportal_install/install_software_elastic.md
Labels: size/S, August21

#2100 7.7 August 21 Merge develop branch into master
  content/en/docs/apim_administration/apigtw_admin/admin_redactors.md
  content/en/docs/apim_administration/apigtw_admin/logging.md
  content/en/docs/apim_administration/apigtw_admin/managetopology.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_config.md
  content/en/docs/apim_installation/apigtw_install/cassandra_install.md
  content/en/docs/apim_installation/apigtw_install/system_requirements.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_cassandra.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
  content/en/docs/apim_installation/apiportal_install/install_software.md
  content/en/docs/apim_installation/apiportal_install/install_software_elastic.md
  content/en/docs/apim_policydev/apigw_external_connections/common_icap_conf.md
  content/en/docs/apim_policydev/apigw_kps/how_to_use_kpsadmin_command.md
  content/en/docs/apim_policydev/apigw_polref/attributes_manipulate.md
  content/en/docs/apim_policydev/apigw_polref/authz_common.md
  content/en/docs/apim_policydev/apigw_polref/content_max_messages.md
  content/en/docs/apim_policydev/apigw_polref/virus_scanning.md
  content/en/docs/apim_reference/api_mgmt_config_web.md
  content/en/docs/apim_reference/cassandra_settings.md
  content/en/docs/apim_reference/system_props.md
  content/en/docs/apim_relnotes/20210830_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20210830_apip_relnotes.md
  content/en/docs/apim_relnotes/20219999_apimgr_relnotes_template.md
  content/en/docs/apim_relnotes/20219999_apip_relnotes_template.md
  content/en/docs/apimgmt_multi_dc/multi_datacenter_config.md
  content/en/docs/cass_admin/cassandra_bestpractices.md
  content/en/docs/cass_admin/cassandra_manage.md
  content/en/docs/cass_admin/cassandra_ops.md
  content/en/docs/cass_admin/cassandra_setup_script.md
  content/en/docs/cass_admin/cassandra_troubleshooting.md
  content/en/docs/glossary/_index.md
  static/Images/docbook/images/content/compareattributefilter.png
  static/Images/docbook/images/content/ldapattributeauthzfilter.png
  static/samples/apimanagement/cassandra/cassandra.centos.service
  static/samples/apimanagement/cassandra/cassandra.debian.service
Labels: size/XL, August21

#2090 Update page in Manage your environments and gateways “add_endpoints”
  content/en/docs/central/env_gw_mgmt/add_endpoints.md
Labels: size/S, netlify-cms/draft

#2102 Remove HTML comments
  content/en/docs/apim_installation/apigw_upgrade/upgrade_cassandra.md
Labels: size/M

#2104 RDAPI-24662 - Cassandra Upgrade 3.11.11: Hosting 2.2.19 and 3.11.11 on webliv
  content/en/docs/apim_installation/apigw_upgrade/upgrade_cassandra.md
Labels: size/XS

#2106 RMF-105 Update Amplify capitalization
  content/en/_index.html
  content/en/blog/news/api-gateway-and-api-manager-documentation-are-now-open-source.md
  content/en/docs/api_mgmt_overview/_index.md
  content/en/docs/api_mgmt_overview/api_mgmt_components/_index.md
  content/en/docs/api_mgmt_overview/api_mgmt_components/analytics.md
  content/en/docs/api_mgmt_overview/api_mgmt_components/pipeline.md
  content/en/docs/api_mgmt_overview/api_mgmt_components/stoplight.md
  content/en/docs/api_mgmt_overview/api_mgmt_components/tools.md
  content/en/docs/api_mgmt_overview/api_mgmt_lifecycle.md
  content/en/docs/api_mgmt_overview/key_concepts/_index.md
  content/en/docs/api_mgmt_overview/key_concepts/api_mgmt_tests.md
  content/en/docs/api_mgmt_overview/key_concepts/policies.md
  content/en/docs/apim-reference-architectures/_index.md
  content/en/docs/apim-reference-architectures/container-aws/_index.md
  content/en/docs/apim-reference-architectures/container-azure/_index.md
  content/en/docs/apim_administration/apigtw_admin/admin_open_logging.md
  content/en/docs/apim_administration/apiportal_admin/apip_overview.md
  content/en/docs/apim_administration/apiportal_admin/customize_APICatalog_overview.md
  content/en/docs/apim_administration/apiportal_admin/expose_APIs_published_from_catalog.md
  content/en/docs/apim_howto_guides/_index.md
  content/en/docs/apim_howto_guides/apigw_in_containers.md
  content/en/docs/apim_howto_guides/apigw_mqclient_tlssetup.md
  content/en/docs/apim_installation/apigw_containers/configure_edge_agent.md
  content/en/docs/apim_relnotes/201904_release/apig_relnotes.md
  content/en/docs/apim_relnotes/201904_release/apim_relnotes.md
  content/en/docs/apim_relnotes/201904_release/apip_relnotes.md
  content/en/docs/apim_relnotes/20200530_apip_relnotes.md
  content/en/docs/apim_yamles/_index.md
  content/en/docs/catalog/discover-and-consume-catalog-assets.md
  content/en/docs/central/cli_central/cli_install.md
  content/en/docs/central/saas_api_gateway/fundamental_concepts.md
  content/en/docs/glossary/_index.md
  layouts/shortcodes/variables/catalog_prod_name.html
  layouts/shortcodes/variables/platform_prod_name.html
  static/admin/config.js
Labels: size/M

#2107 RMF-233 Update linter rules to allow specific HTML tags
  .markdownlint.json
  content/en/docs/contribution_guidelines/linktosamplefolder.md
Labels: size/S

#2109 Update link in Amplify Unified Catalog “manage_subscriptions”
  content/en/docs/catalog/manage_subscriptions.md
Labels: size/XS, netlify-cms/pending_review

#2111 Fix broken link on section Disk space and RAM requirements
  content/en/docs/apim_installation/apigtw_install/system_requirements.md
Labels: size/XS

#2112 RMF-237 Update files for Nov 21 development branch
  .github/workflows/ciworkflow.yml
  .github/workflows/merge_to_develop.yml
  layouts/partials/page-meta-links.html
  static/admin/config.js
Labels: size/S

#2110 [RDAPI-25379] [PS] Remove New Yaml Project option
  content/en/docs/apim_policydev/apigw_poldev/gs_project.md
Labels: size/S

#2116 RMF-237 Create release notes pages for Nov 21
  content/en/docs/apim_relnotes/20211130_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20211130_apip_relnotes.md
Labels: size/M

#2115 [RDAPI-25349] New project from YAML .tar.gz
  content/en/docs/apim_policydev/apigw_poldev/gs_project.md
Labels: size/S, November21

#2113 Amplify CLI used amplify command for package removal
  content/en/docs/central/cli_central/cli_install.md
Labels: size/S, size/XS, netlify-cms/pending_review

#2085 APIGOV-20276 Add CFT profile to Unified Catalog
  content/en/docs/catalog/discover-and-consume-catalog-assets.md
  content/en/docs/central/saas_api_gateway/cft_profile.md
Labels: size/S

#2118 RMF-239 Update API Gateway System requirements Fix typo
  content/en/docs/apim_installation/apigtw_install/system_requirements.md
Labels: size/XS

#2119 [RDAPI-25352] Create yaml tar.gz deployment package docs change
  content/en/docs/apim_administration/apigtw_admin/deploy_get_started.md
Labels: size/XS, November21

#2120 [RDAPI-25429] - Updated to clarify that Gateway instances should be updated and restarted individually
  content/en/docs/apim_installation/apigw_upgrade/upgrade_cassandra.md
Labels: size/XS, November21

#2124 Update Axway Documentation tagline for Google results
  config.toml
Labels: size/XS
