Repository Axway/axway-open-docs, pull requests merged in 2021-12, with the labels that each got.

#2170 Update install_software_elastic.md
  content/en/docs/apim_installation/apiportal_install/install_software_elastic.md
Labels: size/XS

#2169 IAP-4780 - Updates to API Portal release notes Nov 21
  content/en/docs/apim_relnotes/20211130_apip_relnotes.md
Labels: size/S, November21

#2172 RDAPI-25965 Update GW/APIMGR November2021 Release Notes sustaining issues
  content/en/docs/apim_relnotes/20211130_apimgr_relnotes.md
Labels: size/S, November21

#2173 RMF-263 Final review of release notes Nov 21
  content/en/docs/apim_relnotes/20211130_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20211130_apip_relnotes.md
Labels: size/S, November21

#2176 7.7 November 21 Merge develop branch into master
  content/en/docs/apigtw_devops/team_dev_practices.md
  content/en/docs/apim_administration/apigtw_admin/deploy_get_started.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_config.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_custom.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_custom_policies.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_virtualize_web.md
  content/en/docs/apim_installation/apigw_containers/docker_scripts_prereqs.md
  content/en/docs/apim_installation/apiportal_docker/docker_portal_run_image.md
  content/en/docs/apim_installation/apiportal_install/install_software.md
  content/en/docs/apim_installation/apiportal_install/install_unattended.md
  content/en/docs/apim_policydev/apigw_gw_instances/common_compress_encoding.md
  content/en/docs/apim_policydev/apigw_poldev/general_import.md
  content/en/docs/apim_policydev/apigw_poldev/general_project.md
  content/en/docs/apim_policydev/apigw_poldev/gs_project.md
  content/en/docs/apim_reference/general_settings.md
  content/en/docs/apim_relnotes/20211130_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20211130_apip_relnotes.md
Labels: size/L, November21

#2178 [RDAPI-25321] Add new system property to Nov 21 release
  content/en/docs/apim_reference/system_props.md
Labels: size/S

#2179 [RDAPI-25592] New SSO system properties
  content/en/docs/apim_reference/system_props.md
Labels: size/XS

#2180 Fix bad formatting on the pages
  content/en/docs/apim_policydev/apigw_external_connections/common_smtp_server.md
  content/en/docs/apim_policydev/apigw_external_connections/common_user_store.md
Labels: size/M

#2181 [RDAPI-15490] Documenting property 'com.axway.apigw.request.headers.reflect'
  content/en/docs/apim_reference/system_props.md
Labels: size/XS

#2183 [IAP-4833] - Update PHP versions
  content/en/docs/apim_installation/apiportal_install/install_dependencies.md
Labels: size/XS

#2184 IAP-4897: remove API Portal specific selinux commands
  content/en/docs/apim_installation/apiportal_install/install_software.md
Labels: size/XS
