Repository Axway/axway-open-docs, pull requests merged in 2022-06, with the labels that each got.

#2337 RDAPI-27476 Make the build.sh script show an error in Netlify dashboard when Hugo build fails
  build.sh
Labels: size/XS

#2342 RMF-297 Update description of May 22 release notes
  content/en/docs/apim_relnotes/20220530_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20220530_apip_relnotes.md
Labels: size/S

#2346 RMF-298 Minor change to trigger dev site
  content/en/docs/apim_relnotes/20220530_apip_relnotes.md
Labels: size/XS, May22_Portal

#2352 Update Aug 21 release - Installation section
  content/en/docs/apim_relnotes/20210830_apip_relnotes.md
Labels: size/XS

#2351 Update Nov 21 release - Installation section
  content/en/docs/apim_relnotes/20211130_apip_relnotes.md
Labels: size/XS

#2350 Update Feb 22 release - Installation section
  content/en/docs/apim_relnotes/20220228_apip_relnotes.md
Labels: size/XS
