Repository Axway/axway-open-docs, pull requests merged in 2022-10, with the labels that each got.

#2441 [RDAPI-28116] Update Aug 22 release note to include JRE upgrade
  content/en/docs/apim_relnotes/20220830_apimgr_relnotes.md
Labels: size/XS

#2444 Update install_software_redis.md
  content/en/docs/apim_installation/apiportal_install/install_software_redis.md
Labels: size/XS

#2445 Update docker to use latest Joomla third party package
  content/en/docs/apim_installation/apiportal_docker/docker_portal_upgrade.md
Labels: size/XS

#2446 RDAPI-27046 update May22 release notes
  content/en/docs/apim_relnotes/20220530_apimgr_relnotes.md
Labels: size/XS

#2459 Delete information on customization via Joomla plugins and Code
  content/en/docs/apim_administration/apiportal_admin/customize_getting_started.md
Labels: size/XS

#2457 IAP-5516 Updates for ThemeMagic and Joomla 4
  content/en/docs/apim_administration/apiportal_admin/customize_getting_started.md
Labels: size/S

#2462 RDAPI-27927 New page about deploying API Gateway using helm using Openshift
  content/en/docs/apim_installation/apigw_containers/container_helm_deployment.md
Labels: size/M

#2465 RMF-334 Delete page Deploy API Gateway using Helm published on wrong branch
  content/en/docs/apim_installation/apigw_containers/container_helm_deployment.md
Labels: size/M

#2461 IAP-4930- Optimyzing Software install section
  content/en/docs/apim_administration/apiportal_admin/customize_getting_started.md
  content/en/docs/apim_administration/apiportal_admin/expose_APIs_published_from_catalog.md
  content/en/docs/apim_installation/apiportal_install/installConfigure.md
  content/en/docs/apim_installation/apiportal_install/install_software.md
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
Labels: size/S, size/XS, size/M

#2468 IAP-4930 Fix note about Two-factor authentication
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
Labels: size/XS
