Repository Axway/axway-open-docs, pull requests merged in 2022-04, with the labels that each got.

#2279 RMF-273 Delete Contribution section from index page and Update PR template
  .github/pull_request_template.md
  content/en/docs/_index.md
Labels: size/XS

#2277 RDAPI-23379 Add known issues to API Gateway release notes May 22
  content/en/docs/apim_relnotes/20220530_apimgr_relnotes.md
Labels: size/S, May22

#2275 IAP-5073 Release Logs Update 2019 table
  content/en/docs/apim_reference/allReleasesChangeLog.md
Labels: size/S

#2282 Remove package-lock.json file
  package-lock.json
Labels: size/XL

#2281 [RDAPI-24024] - Documentation changes for the 1.8.0_322 JRE Upgrade
  content/en/docs/apim_reference/system_props.md
  content/en/docs/apim_relnotes/20220530_apimgr_relnotes.md
Labels: size/S, May22

#2283 [RDAPI-26817] - Mount Persistent YAML Volume as Directory in EMT
  content/en/docs/apim_howto_guides/configuring_apigw_container.md
Labels: size/S, May22

#2284 [RDAPI-26612] Updating definition of finalStatus
  content/en/docs/apim_reference/log_global_settings.md
  content/en/docs/apim_reference/open_logging_schema.md
Labels: size/XS

#2285 RMF-288 Test 01 to delete extra text from search results
  config.toml
Labels: size/XS

#2287 RMF-288 Test 03 to delete pipe character
  layouts/docs/list.html
Labels: size/XS

#2294 Fix typo
  content/en/docs/apigtw_kerberos/kerberos_use_case_client.md
Labels: size/XS

#2296 RMF-290 Revert "Fix typo"
  content/en/docs/apigtw_kerberos/kerberos_use_case_client.md
Labels: size/XS

#2297 RMF-290 Update Workflow merge_to_develop to work around permission issue
  .github/workflows/merge_to_develop.yml
Labels: size/XS

#2298 RMF-290 Manually merge master into develop
  .github/workflows/merge_to_develop.yml
Labels: size/XS

#2299 Change wording choice
  content/en/docs/apigtw_kerberos/kerberos_overview.md
Labels: size/XS

#2302 Fix typo in FIPS acronym
  content/en/docs/apim_administration/apigtw_admin/admin_fips.md
Labels: size/XS

#2303 Manually merge master into develop - 20220425
  content/en/docs/apim_administration/apigtw_admin/admin_fips.md
Labels: size/XS

#2304 RMF-290 Update Workflow merge_to_develop to fix permission issue
  .github/workflows/merge_to_develop.yml
Labels: size/XS

#2291 [RDAPI-26813] Policystudio: Modify Connection/ConnectToUrl filter UI to include new timeout overrides
  content/en/docs/apim_policydev/apigw_polref/routing_common.md
Labels: size/S, May22

#2288 [RDAPI-26402] New redaction features
  content/en/docs/apim_administration/apigtw_admin/admin_redactors.md
  content/en/docs/apim_relnotes/20220530_apimgr_relnotes.md
Labels: size/M, May22
