Repository Axway/axway-open-docs, pull requests merged in 2022-08, with the labels that each got.

#2369 [RDAPI-16377] Update OAuth flow pages to explain scope delimiters better
  content/en/docs/apim_policydev/apigw_oauth/oauth_flows/oauth_flows_auth_code.md
  content/en/docs/apim_policydev/apigw_oauth/oauth_flows/oauth_flows_client_credentials.md
  content/en/docs/apim_policydev/apigw_oauth/oauth_flows/oauth_flows_resource_owner.md
  content/en/docs/apim_policydev/apigw_oauth/oauth_flows/oauth_flows_user_agent.md
Labels: size/S

#2376 IAP-5278: fix customize 404 page section
  content/en/docs/apim_administration/apiportal_admin/customize_getting_started.md
Labels: size/S

#2375 API Portal upgrade - add videos on how to update from February 2022 to May 2022
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
Labels: size/S, size/XS

#2381 IAP-5192 - Add clarification around Enforce password policies
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_custom.md
  content/en/docs/apim_administration/apiportal_admin/customize_page_content.md
Labels: size/S, size/XS

#2386 RDAPI-27443 Policy Studio\Configuration Studio remove plugins dir during update
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
Labels: size/XS, August22

#2384 [RDAPI-27966] Added 7.7 August 2022 'com.axway.apigw.cookie.validation.ignore' system property.
  content/en/docs/apim_reference/system_props.md
Labels: August22

#2383 IAI-5449: update run container volumes section
  content/en/docs/apim_installation/apiportal_docker/docker_portal_run_image.md
Labels: size/S, size/XS, August22

#2390 Add a direct link to APIM Security guide
  content/en/docs/apim_sec_guide/_index.md
  static/admin/config.js
Labels: size/S

#2389 [RDAPI-25357] Optional --install_dir flag for PS/CS update
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
Labels: size/S, August22

#2387 RDAPI-22198 Release notes Important Changes update for Policy Studio/Configuration Studio
  content/en/docs/apim_relnotes/20220830_apimgr_relnotes.md
Labels: size/XS, August22

#2394 RDAPI-28008 update hugo to latest
  netlify.toml
Labels: size/XS

#2385 Update Export instruction. Update portal upgrade.
  content/en/docs/apigtw_devops/promotion_example.md
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
Labels: size/S, size/XS

#2396 RMF-304 Update main description of release notes pages
  content/en/docs/apim_relnotes/20220830_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20220830_apip_relnotes.md
Labels: size/XS, August22

#2393 [RDAPI-27803] Updating allowed minimum values for LDAP Connection "cachetimeout" and "cachesize" properties.
  content/en/docs/apim_policydev/apigw_external_connections/common_ldap_conf.md
Labels: August22

#2395 [RDAPI-27454] - Added details of how to configure ANM containers
  content/en/docs/apim_howto_guides/configuring_apigw_container.md
Labels: size/S, August22

#2397 [RDAPI-28086] Important changes and Fixed issues updates in “20220830_apimgr_relnotes”
  content/en/docs/apim_relnotes/20220830_apimgr_relnotes.md
Labels: August22

#2400 RMF-301 User roles - Org Admin Self-service API publishing
  content/en/docs/api_mgmt_overview/key_concepts/api_mgmt_orgs_roles.md
Labels: size/XS, August22

#2398 [RDAPI-28087] Important changes and Fixed issues updates in “20220830_apimgr_relnotes”
  content/en/docs/apim_relnotes/20220830_apimgr_relnotes.md
Labels: August22

#2401 [RDAPI-26894][RDAPI-28029] Mention that differences of case sensitivity of files and directories in Linux and Windows may affect YAML projects.
  content/en/docs/apim_policydev/apigw_poldev/gs_concepts.md
Labels: size/XS, August22

#2399 [RDAPI-28088] Important changes and Fixed issues updates in “20220830_apimgr_relnotes”
  content/en/docs/apim_relnotes/20220830_apimgr_relnotes.md
Labels: August22

#2404 IAP-5429 - Update release notes August
  content/en/docs/apim_installation/apiportal_docker/docker_portal_upgrade.md
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
  content/en/docs/apim_relnotes/20220830_apip_relnotes.md
Labels: size/S, August22

#2402 [RDAPI-26798] Removing alert about FIPS mode not being supported and …
  content/en/docs/apim_administration/apigtw_admin/admin_fips.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
  content/en/docs/apim_relnotes/20220830_apimgr_relnotes.md
Labels: size/S, August22

#2403 RDAPI-27443 update to Release note Import changes section
  content/en/docs/apim_relnotes/20220830_apimgr_relnotes.md
Labels: size/XS, August22

#2408 [RDAPI-28033] Known issue: EdDSA certs are not supported
  content/en/docs/apim_relnotes/20220830_apimgr_relnotes.md
Labels: size/XS, August22

#2406 RDAPI-27997 Release Notes Customer Issues fixed
  content/en/docs/apim_relnotes/20220830_apimgr_relnotes.md
Labels: size/S, August22

#2405 [RDAPI-27097] - Adding relevant documentation for YAML support in Policy Studio
  content/en/docs/apim_relnotes/20220830_apimgr_relnotes.md
  content/en/docs/apim_yamles/_index.md
  content/en/docs/apim_yamles/apim_yamles_references/_index.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_environmentalization_example.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_yaml_schema.md
  content/en/docs/apim_yamles/yamles_edit.md
  content/en/docs/apim_yamles/yamles_environmentalization.md
  content/en/docs/apim_yamles/yamles_migration_xml_yaml.md
  content/en/docs/apim_yamles/yamles_policy_studio.md
  content/en/docs/apim_yamles/yamles_quick_start.md
  static/Images/apim_yamles/yamles_ps_e18n_many_jump_to_config_dialog.PNG
  static/Images/apim_yamles/yamles_ps_e18n_placeholder_example.PNG
  static/Images/apim_yamles/yamles_ps_e18n_trees_comparison.PNG
  static/Images/apim_yamles/yamles_ps_e18n_xml_jump_to_config.PNG
  static/Images/apim_yamles/yamles_ps_e18n_yaml_jump_to_config.PNG
Labels: size/L, August22

#2407 Gonzo release note changes
  content/en/docs/apim_relnotes/20220830_apimgr_relnotes.md
Labels: size/S, August22

#2411 RMF-301 General fixes and updates
  content/en/docs/apim_relnotes/20220830_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20220830_apip_relnotes.md
Labels: size/S

#2410 IAP-5504 - Known issue added to release notes
  content/en/docs/apim_relnotes/20220830_apip_relnotes.md
Labels: size/XS, August22

#2409 [RDAPI-25159] Cassandra user with non-superuser level account
  content/en/docs/cass_admin/cassandra_config.md
Labels: size/S, August22

#2412 Add deprecation notice around API Portal docker image
  content/en/docs/apim_relnotes/20220830_apip_relnotes.md
Labels: size/XS, August22

#2413 RMF-310 Aug 22 Update change log
  content/en/docs/apim_reference/allReleasesChangeLog.md
Labels: size/S, August22

#2414 Aug 22 release notes - Move FIPS up as first item of Important Changes
  content/en/docs/apim_relnotes/20220830_apimgr_relnotes.md
Labels: August22

#2415 RDAPI-22218 Delete known issue around Xerces SAXParserImpl logs warnings
  content/en/docs/apim_relnotes/20220830_apimgr_relnotes.md
Labels: size/S, August22

#2416 Editorial updates to the post-upgrade scripts page
  content/en/docs/apim_reference/scripts_changelog_sp.md
Labels: documentation

#2417 7.7 Aug 22 Merge Develop branch into master branch
  content/en/docs/api_mgmt_overview/key_concepts/api_mgmt_orgs_roles.md
  content/en/docs/apim_administration/apigtw_admin/admin_fips.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_custom.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_monitor.md
  content/en/docs/apim_administration/apiportal_admin/customize_page_content.md
  content/en/docs/apim_howto_guides/configuring_apigw_container.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
  content/en/docs/apim_installation/apiportal_docker/docker_portal_run_image.md
  content/en/docs/apim_installation/apiportal_docker/docker_portal_upgrade.md
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
  content/en/docs/apim_policydev/apigw_external_connections/common_ldap_conf.md
  content/en/docs/apim_policydev/apigw_poldev/gs_concepts.md
  content/en/docs/apim_reference/allReleasesChangeLog.md
  content/en/docs/apim_reference/system_props.md
  content/en/docs/apim_relnotes/20220830_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20220830_apip_relnotes.md
  content/en/docs/apim_yamles/_index.md
  content/en/docs/apim_yamles/apim_yamles_references/_index.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_environmentalization_example.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
  content/en/docs/apim_yamles/apim_yamles_references/yamles_yaml_schema.md
  content/en/docs/apim_yamles/yamles_edit.md
  content/en/docs/apim_yamles/yamles_environmentalization.md
  content/en/docs/apim_yamles/yamles_migration_xml_yaml.md
  content/en/docs/apim_yamles/yamles_policy_studio.md
  content/en/docs/apim_yamles/yamles_quick_start.md
  content/en/docs/cass_admin/cassandra_config.md
  static/Images/apim_yamles/yamles_ps_e18n_many_jump_to_config_dialog.PNG
  static/Images/apim_yamles/yamles_ps_e18n_placeholder_example.PNG
  static/Images/apim_yamles/yamles_ps_e18n_trees_comparison.PNG
  static/Images/apim_yamles/yamles_ps_e18n_xml_jump_to_config.PNG
  static/Images/apim_yamles/yamles_ps_e18n_yaml_jump_to_config.PNG
Labels: size/XL, August22
