Repository Axway/axway-open-docs, pull requests merged in 2022-03, with the labels that each got.

#2253 RDAPI-26539 Adding more sections
  content/en/docs/apim_reference/allReleasesChangeLog.md
Labels: size/XS

#2255 Update Nov21 release for more information on Unattended installation
  content/en/docs/apim_installation/apiportal_install/install_unattended.md
  content/en/docs/apim_relnotes/20211130_apip_relnotes.md
Labels: size/S

#2257 IAP-5167 Update Issue and Resolution of fixed issue
  content/en/docs/apim_relnotes/20210830_apip_relnotes.md
Labels: size/XS

#2258 RMF-282 Update config files for May 22
  .github/workflows/ciworkflow.yml
  .github/workflows/merge_to_develop.yml
  layouts/partials/page-meta-links.html
  static/admin/config.js
Labels: size/S, May22

#2262 RMF-282 Trigger dev branch
  content/en/docs/apigtw_devops/team_dev_dependencies.md
Labels: size/XS

#2254 RMF-283 Restructuring Release change log page
  content/en/docs/apim_reference/allReleasesChangeLog.md
Labels: size/S, size/M

#2259 RDAPI-25253 Add supported WADL element XML namespace
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_register_web.md
Labels: size/XS

#2264 RMF-283 Release change log - Fix extra column
  content/en/docs/apim_reference/allReleasesChangeLog.md
Labels: size/XS

#2263 [RDAPI-26741] Cassandra backup/restore needs to be prefered over kpsadmin, with explanations for why
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
  content/en/docs/apim_policydev/apigw_kps/how_to_use_kpsadmin_command.md
Labels: size/S

#2266 [RDAPI-23779] Updating system_props.md for May 22
  content/en/docs/apim_reference/system_props.md
Labels: size/S, May22

#2265 [RDAPI-22760] - Customise the audit log directory and filename in an EMT environment
  content/en/docs/apim_installation/apigw_containers/container_getstarted.md
Labels: size/S, May22

#2256 [RDAPI-26673] Update docs to reflect new mandatory parameter for APIGW unattended mode
  content/en/docs/apim_installation/apigtw_install/cassandra_install.md
  content/en/docs/apim_installation/apigtw_install/install_analytics.md
  content/en/docs/apim_installation/apigtw_install/install_api_mgmt.md
  content/en/docs/apim_installation/apigtw_install/install_config_studio.md
  content/en/docs/apim_installation/apigtw_install/install_deploy_tools.md
  content/en/docs/apim_installation/apigtw_install/install_gateway.md
  content/en/docs/apim_installation/apigtw_install/install_node_manager.md
  content/en/docs/apim_installation/apigtw_install/install_policy_studio.md
  content/en/docs/apim_installation/apigtw_install/install_quickstart_tutorial.md
  content/en/docs/apim_installation/apigtw_install/installation_unattended.md
  static/samples/apimanagement/howto/docker/runInstall.sh
Labels: size/S, May22

#2268 RMF-282 Create release notes pages
  content/en/docs/apim_relnotes/20220530_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20220530_apip_relnotes.md
Labels: size/M, May22

#2269 RMF-273 Remove Feedback section from bottom of the page
  config.toml
  layouts/docs/list.html
Labels: size/XS

#2273 RMF-273 Delete double line
  layouts/_default/content.html
Labels: size/XS

#2272 Update links in Release Change Log page
  content/en/docs/apim_reference/allReleasesChangeLog.md
Labels: size/S

#2271 RDAPI-26535 Update doc that routing based on a query string is available only for REST APIs
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_version_routing.md
Labels: size/XS

#2274 RDAPI-25488 XPath wizard does not support DOCTYPE declaration
  content/en/docs/apim_policydev/apigw_polref/attributes_retrieve.md
  content/en/docs/apim_policydev/apigw_polref/content_additional.md
  content/en/docs/apim_policydev/apigw_polref/integrity_xml.md
  content/en/docs/apim_policydev/apigw_polref/utility_additional.md
Labels: size/L, size/M, May22
