Repository Axway/axway-open-docs, pull requests merged in 2022-02, with the labels that each got.

#2211 [RDAPI-22391] API Manager REST APIs, JVM flags to import Swagger/OAS APIs with external references.
  content/en/docs/apim_reference/api_mgmt_rest_api.md
Labels: February22

#2213 [RDAPI-22391] API Manager REST APIs, JVM flags to import Swagger/OAS APIs with external references.
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_register_web.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_workflow.md
  content/en/docs/apim_reference/api_mgmt_rest_api.md
Labels: size/XS, February22

#2209 [RDAPI-26473] Updating YAML deployment documentation
  content/en/docs/apim_yamles/yamles_packaging_deployment.md
Labels: size/S, February22

#2218 RMF-275 Fix markdown lint checks
  content/en/docs/apim-reference-architectures/container-aws/_index.md
  content/en/docs/apim-reference-architectures/container-azure/_index.md
  content/en/docs/apim_relnotes/201904_release/apig_fixedissues.md
  content/en/docs/cass_admin/cassandra_config.md
Labels: size/S

#2215 RDAPI-19492 Update Release Note Important changes for SchemaValidation
  content/en/docs/apim_relnotes/20220228_apimgr_relnotes.md
Labels: size/XS, February22

#2216 [RDAPI-26483] Document ACCEPT_GENERAL_CONDITIONS env var for EMT
  content/en/docs/apim_installation/apigw_containers/container_apigateway_analytics.md
  content/en/docs/apim_installation/apigw_containers/container_migration.md
  content/en/docs/apim_installation/apigw_containers/docker_script_anmimage.md
  content/en/docs/apim_installation/apigw_containers/docker_script_gwimage.md
  content/en/docs/apim_installation/apigw_containers/docker_scripts_prereqs.md
Labels: size/M, February22

#2220 [RDAPI-19915] Update minimum system requirements in regards to cassandra prod use
  content/en/docs/apim_installation/apigtw_install/cassandra_install.md
Labels: size/S, February22

#2217 [RDAPI-26366] Document availability of YAML for EMT GW images
  content/en/docs/apim_howto_guides/apigw_in_containers.md
  content/en/docs/apim_installation/apigtw_install/system_requirements.md
  content/en/docs/apim_installation/apigw_containers/docker_script_gwimage.md
  content/en/docs/cass_admin/cassandra_config.md
Labels: size/S, February22

#2219 RDAPI-26403 Support E18n external files and yaml specific syntax expressions
  content/en/docs/apigtw_devops/promotion_example.md
  content/en/docs/apim_installation/apigtw_install/install_quickstart_tutorial.md
  content/en/docs/apim_yamles/yamles_environmentalization.md
  static/Images/docbook/images/deploy/env_off.png
  static/Images/docbook/images/deploy/env_on.png
  static/Images/docbook/images/promotion/yaml_values_settings.png
Labels: size/S, February22

#2249 7.7 February 22 Merge develop branch into master
  content/en/docs/apigtw_devops/deploy_package_tools.md
  content/en/docs/apigtw_devops/promotion_example.md
  content/en/docs/apigtw_devops/promotion_scripts.md
  content/en/docs/apim-reference-architectures/container-aws/_index.md
  content/en/docs/apim-reference-architectures/container-azure/_index.md
  content/en/docs/apim_administration/apigtw_admin/general_passphrase.md
  content/en/docs/apim_administration/apigtw_admin/general_rbac.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_connect_mobile_backend_services.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_custom.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_register_web.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_workflow.md
  content/en/docs/apim_administration/apiportal_sso/_index.md
  content/en/docs/apim_howto_guides/apigw_in_containers.md
  content/en/docs/apim_howto_guides/configuring_apigw_container.md
  content/en/docs/apim_installation/apigtw_install/cassandra_install.md
  content/en/docs/apim_installation/apigtw_install/install_config_studio.md
  content/en/docs/apim_installation/apigtw_install/install_quickstart_tutorial.md
  content/en/docs/apim_installation/apigtw_install/system_requirements.md
  content/en/docs/apim_installation/apigw_containers/container_apigateway_analytics.md
  content/en/docs/apim_installation/apigw_containers/container_getstarted.md
  content/en/docs/apim_installation/apigw_containers/container_migration.md
  content/en/docs/apim_installation/apigw_containers/docker_script_anmimage.md
  content/en/docs/apim_installation/apigw_containers/docker_script_gwimage.md
  content/en/docs/apim_installation/apigw_containers/docker_scripts_prereqs.md
  content/en/docs/apim_installation/apiportal_install/install_dependencies.md
  content/en/docs/apim_installation/apiportal_install/install_software_configure_database.md
  content/en/docs/apim_installation/apiportal_install/install_software_prereqs.md
  content/en/docs/apim_policydev/apigw_poldev/general_ps_settings.md
  content/en/docs/apim_policydev/apigw_polref/api_mgr_ps_filters.md
  content/en/docs/apim_reference/allReleasesChangeLog.md
  content/en/docs/apim_reference/api_mgmt_config_web.md
  content/en/docs/apim_reference/api_mgmt_rest_api.md
  content/en/docs/apim_reference/managedomain_ref.md
  content/en/docs/apim_reference/monitor_traffic_events_metrics.md
  content/en/docs/apim_reference/system_props.md
  content/en/docs/apim_relnotes/201904_release/apig_fixedissues.md
  content/en/docs/apim_relnotes/20210830_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20211130_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20220228_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20220228_apip_relnotes.md
  content/en/docs/apim_yamles/yamles_environmentalization.md
  content/en/docs/apim_yamles/yamles_packaging_deployment.md
  content/en/docs/cass_admin/cassandra_config.md
  content/en/docs/glossary/_index.md
  static/Images/docbook/images/deploy/env_off.png
  static/Images/docbook/images/deploy/env_on.png
  static/Images/docbook/images/promotion/yaml_values_settings.png
Labels: size/XL, February22
