Repository Axway/axway-open-docs, pull requests merged in 2022-01, with the labels that each got.

#2186 Update PHP 7.1 - 7.4 sucently supported versions, exclude PHP 8.x
  content/en/docs/apim_installation/apiportal_install/install_software_prereqs.md
Labels: size/XS

#2188 Enable Prims to allow for Copy to clipboard buttons on code blocks
  config.toml
Labels: size/XS

#2189 Enable Copy to clipboard buttons on code blocks
  config.toml
Labels: size/XS

#2190 APIM System requirements - Update link to anchor on the same page
  content/en/docs/apim_installation/apigtw_install/system_requirements.md
Labels: size/XS

#2187 Corrects Certificate chain check filter information
  content/en/docs/apim_policydev/apigw_polref/cert_validation.md
Labels: size/XS

#2192 RDAPI-26399 Fixt typo rmiURLs in Multi-datacenter configuration
  content/en/docs/apimgmt_multi_dc/multi_datacenter_config.md
Labels: size/XS

#2193 RMF-266 Delete Netlify hardcoded links
  content/en/docs/apim_relnotes/20200330_apip_relnotes.md
  content/en/docs/apim_relnotes/20200530_apip_relnotes.md
  content/en/docs/apim_relnotes/20200730_apip_relnotes.md
  content/en/docs/apim_relnotes/20210130_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20211130_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20211130_apip_relnotes.md
Labels: size/S

#2194 RMF-266 Delete Netlify hardcoded links - complementary
  content/en/docs/apim_yamles/yamles_packaging_deployment.md
Labels: size/XS

#2196 RMF-268 Update files for Feb 22 development branch
  .github/workflows/ciworkflow.yml
  .github/workflows/merge_to_develop.yml
  layouts/partials/page-meta-links.html
  static/admin/config.js
Labels: size/S, February22

#2198 Update _index.md
  content/en/docs/glossary/_index.md
Labels: size/XS, February22

#2199 RMF-268 Create release notes pages for February 22
  content/en/docs/apim_relnotes/20220228_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20220228_apip_relnotes.md
Labels: size/M, February22

#2201 RDAPI-25904 Ehcache timeout added. System Property update.
  content/en/docs/apim_reference/system_props.md
Labels: size/XS, February22

#2185 [RDAPI-20726] Changed default selector for Read Application filter
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_custom.md
  content/en/docs/apim_policydev/apigw_polref/api_mgr_ps_filters.md
Labels: size/XS, February22

#2205 RDAPI-26451 Docs - Fix potential security vulnerabilities in open-doc…
  package-lock.json
  package.json
Labels: size/L

#2208 RDAPI-25904 updates to system properties and Feb22 release note
  content/en/docs/apim_reference/system_props.md
  content/en/docs/apim_relnotes/20220228_apimgr_relnotes.md
Labels: size/XS, February22

#2202 Update description of spilltodisk
  content/en/docs/apim_administration/apigtw_admin/admin_performance.md
Labels: size/XS

#2206 [RDAPI-23715] SSO users in API Manager are not logged out when logging out of API Portal
  content/en/docs/apim_administration/apiportal_sso/_index.md
Labels: size/S, February22
