Repository Axway/axway-open-docs, pull requests merged in 2022-05, with the labels that each got.

#2306 Fix issue #2191 Update section Real-time monitoring metrics
  content/en/docs/apim_reference/monitor_traffic_events_metrics.md
Labels: size/XS

#2295 [RDAPI-23471] Routing Policy with service URL in APIM
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_custom_policies.md
  static/Images/docbook/images/api_mgmt/api_mgmt_custom_policy_configure_api_key.png
  static/Images/docbook/images/api_mgmt/api_mgmt_custom_policy_configure_apimgr.png
  static/Images/docbook/images/api_mgmt/api_mgmt_custom_policy_configure_apimgr_oauth.png
  static/Images/docbook/images/api_mgmt/api_mgmt_custom_policy_configure_apimgr_ssl_policy.png
  static/Images/docbook/images/api_mgmt/api_mgmt_custom_policy_oauth_credentials.png
  static/Images/docbook/images/api_mgmt/api_mgmt_fault_handler_api.png
  static/Images/docbook/images/api_mgmt/api_mgmt_fault_handler_api_method.png
  static/Images/docbook/images/api_mgmt/api_mgmt_global_policy_apply.png
  static/Images/docbook/images/api_mgmt/api_mgmt_global_policy_frontend.png
  static/Images/docbook/images/api_mgmt/api_mgmt_global_policy_monitor.png
Labels: size/S, size/XS, May22

#2312 Upgrade One Version - Adds missing slash in java.library.path setting
  content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
Labels: size/XS

#2309 RDAPI-27247 Update May22 release notes with Policy Studio JRE TLS
  content/en/docs/apim_relnotes/20220530_apimgr_relnotes.md
Labels: size/S, May22

#2308 RDAPI-27014 Discovery and Traceability agents are shipped with API Gateway, delete Configure usage tracking page
  content/en/docs/apim_administration/apigtw_admin/admin_performance.md
  content/en/docs/apim_installation/apigtw_install/install_agents.md
  content/en/docs/apim_installation/apigtw_install/installation.md
  content/en/docs/apim_installation/apigtw_install/post_overview.md
  content/en/docs/apim_installation/apigw_containers/configure_edge_agent.md
  content/en/docs/apim_installation/apigw_containers/container_intro.md
  content/en/docs/apim_installation/apigw_containers/docker_script_anmimage.md
  content/en/docs/apim_installation/apigw_containers/docker_script_gwimage.md
  content/en/docs/apim_installation/apigw_containers/docker_scripts_prereqs.md
Labels: size/L, May22

#2317 RDAPI-27318 - Include links to timeout overrides, plus describe fallback mechanism for filter-level timeout overrides
  content/en/docs/apim_policydev/apigw_gw_instances/general_remote_hosts.md
  content/en/docs/apim_policydev/apigw_polref/routing_common.md
  content/en/docs/apim_reference/general_settings.md
Labels: size/S, May22

#2315 RDAPI-25822 Query String Pass Through at API Level
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_virtualize_web.md
  static/Images/docbook/images/api_mgmt/api_mgmt_frontend_api_inbound_advanced.png
Labels: size/XS, May22

#2322 May 22 Update deprecation section about removing the Edge agent
  content/en/docs/apim_relnotes/20220530_apimgr_relnotes.md
Labels: size/XS, May22

#2320 [RDAPI-27059] OpenSSL 3.0 Release note and docs update
  content/en/docs/apim_administration/apigtw_admin/general_certificates.md
  content/en/docs/apim_policydev/apigw_gw_instances/general_services.md
  content/en/docs/apim_relnotes/20220530_apimgr_relnotes.md
Labels: size/S, May22

#2321 [RDAPI-27014] Add information regarding agent configuration in a clustered environment.
  content/en/docs/apim_installation/apigtw_install/post_overview.md
Labels: size/S, size/XS, May22

#2324 RMF-297 May 22 Do not show APIP release notes page
  content/en/docs/apim_relnotes/20220530_apip_relnotes.md
Labels: size/XS, May22

#2323 RDAPI-26745 Policy Studio YAML Windows performance Release Notes update
  content/en/docs/apim_relnotes/20220530_apimgr_relnotes.md
Labels: size/S, May22

#2325 [RDAPI-27191] Add SSO host verification release note
  content/en/docs/apim_relnotes/20220530_apimgr_relnotes.md
Labels: May22

#2326 Call out this important change to the api manager global fault handler
  content/en/docs/apim_relnotes/20220530_apimgr_relnotes.md
Labels: size/XS, May22

#2328 IAP-5238 - Update APIP Feb 22 with API Manager May 22 compatibility
  content/en/docs/apim_relnotes/20220228_apip_relnotes.md
Labels: size/XS

#2313 API Gtw May 22 Release notes for Gonzo
  content/en/docs/apim_reference/allReleasesChangeLog.md
  content/en/docs/apim_relnotes/20220530_apimgr_relnotes.md
Labels: size/S, May22

#2329 [RDAPI-23779] Obs-folded system property added to important updates
  content/en/docs/apim_relnotes/20220530_apimgr_relnotes.md
Labels: May22

#2330 RDAPI-26743 Remove Policy Studio installation update issue from Known Issues
  content/en/docs/apim_relnotes/20220530_apimgr_relnotes.md
Labels: size/XS, May22

#2331 RDAPI-26370 API Manager lightweight APIs
  content/en/docs/apim_relnotes/20220530_apimgr_relnotes.md
Labels: size/S, May22

#2333 RDAPI-26866 Agents added to new features in Release Notes
  content/en/docs/apim_relnotes/20220530_apimgr_relnotes.md
Labels: size/XS, May22

#2318 RDAPI-27323 Update May22 release notes with customer issues
  content/en/docs/apim_relnotes/20220530_apimgr_relnotes.md
Labels: size/S, May22

#2327 RDAPI-26585 Add section for changes in a list of allowed HTTP methods for API Gateway CORS request
  content/en/docs/apim_relnotes/20220530_apimgr_relnotes.md
Labels: May22

#2332 RMF-297 May 22 release notes final updates
  content/en/docs/apim_relnotes/20220530_apimgr_relnotes.md
Labels: size/S, May22

#2334 RMF-297 Final updates to May 22 release notes
  content/en/docs/apim_relnotes/20220530_apimgr_relnotes.md
Labels: size/S, May22

#2335 7.7 May 22 Merge Develop branch into master branch
  content/en/docs/apigtw_devops/team_dev_dependencies.md
  content/en/docs/apim_administration/apigtw_admin/admin_performance.md
  content/en/docs/apim_administration/apigtw_admin/admin_redactors.md
  content/en/docs/apim_administration/apigtw_admin/general_certificates.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_custom_policies.md
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_virtualize_web.md
  content/en/docs/apim_howto_guides/configuring_apigw_container.md
  content/en/docs/apim_installation/apigtw_install/cassandra_install.md
  content/en/docs/apim_installation/apigtw_install/install_agents.md
  content/en/docs/apim_installation/apigtw_install/install_analytics.md
  content/en/docs/apim_installation/apigtw_install/install_api_mgmt.md
  content/en/docs/apim_installation/apigtw_install/install_config_studio.md
  content/en/docs/apim_installation/apigtw_install/install_deploy_tools.md
  content/en/docs/apim_installation/apigtw_install/install_gateway.md
  content/en/docs/apim_installation/apigtw_install/install_node_manager.md
  content/en/docs/apim_installation/apigtw_install/install_policy_studio.md
  content/en/docs/apim_installation/apigtw_install/install_quickstart_tutorial.md
  content/en/docs/apim_installation/apigtw_install/installation.md
  content/en/docs/apim_installation/apigtw_install/installation_unattended.md
  content/en/docs/apim_installation/apigtw_install/post_overview.md
  content/en/docs/apim_installation/apigw_containers/configure_edge_agent.md
  content/en/docs/apim_installation/apigw_containers/container_getstarted.md
  content/en/docs/apim_installation/apigw_containers/container_intro.md
  content/en/docs/apim_installation/apigw_containers/docker_script_anmimage.md
  content/en/docs/apim_installation/apigw_containers/docker_script_gwimage.md
  content/en/docs/apim_installation/apigw_containers/docker_scripts_prereqs.md
  content/en/docs/apim_policydev/apigw_gw_instances/general_remote_hosts.md
  content/en/docs/apim_policydev/apigw_gw_instances/general_services.md
  content/en/docs/apim_policydev/apigw_polref/attributes_retrieve.md
  content/en/docs/apim_policydev/apigw_polref/content_additional.md
  content/en/docs/apim_policydev/apigw_polref/integrity_xml.md
  content/en/docs/apim_policydev/apigw_polref/routing_common.md
  content/en/docs/apim_policydev/apigw_polref/utility_additional.md
  content/en/docs/apim_reference/allReleasesChangeLog.md
  content/en/docs/apim_reference/general_settings.md
  content/en/docs/apim_reference/system_props.md
  content/en/docs/apim_relnotes/20220530_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20220530_apip_relnotes.md
  static/Images/ContainerGuide/container_gw_domain.png
  static/Images/ContainerGuide/elastic_topology_arch.png
  static/Images/docbook/images/api_mgmt/api_mgmt_custom_policy_configure_api_key.png
  static/Images/docbook/images/api_mgmt/api_mgmt_custom_policy_configure_apimgr.png
  static/Images/docbook/images/api_mgmt/api_mgmt_custom_policy_configure_apimgr_oauth.png
  static/Images/docbook/images/api_mgmt/api_mgmt_custom_policy_configure_apimgr_ssl_policy.png
  static/Images/docbook/images/api_mgmt/api_mgmt_custom_policy_oauth_credentials.png
  static/Images/docbook/images/api_mgmt/api_mgmt_fault_handler_api.png
  static/Images/docbook/images/api_mgmt/api_mgmt_fault_handler_api_method.png
  static/Images/docbook/images/api_mgmt/api_mgmt_frontend_api_inbound_advanced.png
  static/Images/docbook/images/api_mgmt/api_mgmt_global_policy_apply.png
  static/Images/docbook/images/api_mgmt/api_mgmt_global_policy_frontend.png
  static/Images/docbook/images/api_mgmt/api_mgmt_global_policy_monitor.png
  static/samples/apimanagement/howto/docker/runInstall.sh
Labels: size/XL, May22

#2336 RMF-297 Update release change log for May 22
  content/en/docs/apim_reference/allReleasesChangeLog.md
  content/en/docs/apim_relnotes/20220530_apimgr_relnotes.md
  content/en/docs/apim_relnotes/_index.md
Labels: size/S, May22
