Repository Axway/axway-open-docs, pull requests merged in 2022-07, with the labels that each got.

#2358 Configure Public API mode - update link
  content/en/docs/apim_installation/apiportal_install/install_software.md
Labels: size/XS

#2357 IAP- 5276 - CSP update notice for Joomla 4
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
Labels: size/XS, May22_Portal

#2349 IAP-5089 - Release notes May 2022 update
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
  content/en/docs/apim_relnotes/20220530_apip_relnotes.md
Labels: size/S, May22_Portal

#2356 IAP-5309 May 22 - Docker deployment - Add info on how to upgrade to Joomla 4 system based
  content/en/docs/apim_installation/apiportal_docker/docker_portal_upgrade.md
Labels: size/S, May22_Portal

#2365 API Portal 7.7 May 22 Merge Develop branch into master branch
  content/en/docs/apim_administration/apiportal_admin/customize_APICatalog_overview.md
  content/en/docs/apim_administration/apiportal_admin/customize_css_styles.md
  content/en/docs/apim_administration/apiportal_admin/customize_getting_started.md
  content/en/docs/apim_administration/apiportal_admin/customize_page_content.md
  content/en/docs/apim_administration/apiportal_admin/localize_language.md
  content/en/docs/apim_administration/apiportal_admin/manage_privacy_personal_data.md
  content/en/docs/apim_administration/apiportal_admin/role_mapping.md
  content/en/docs/apim_installation/apiportal_docker/docker_portal_upgrade.md
  content/en/docs/apim_installation/apiportal_install/install_service_pack.md
  content/en/docs/apim_installation/apiportal_install/install_software_configure_database.md
  content/en/docs/apim_installation/apiportal_install/install_software_elastic.md
  content/en/docs/apim_installation/apiportal_install/install_software_redis.md
  content/en/docs/apim_installation/apiportal_install/secure_harden_portal.md
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
  content/en/docs/apim_relnotes/20220530_apip_relnotes.md
  static/Images/APIPortal/JoomlaThemeMagicStyles.png
  static/Images/APIPortal/JoomlaThemeMagicStyles_j4.png
  static/Images/APIPortal/api-catalog.png
  static/Images/APIPortal/api-catalog_j4.png
  static/Images/APIPortal/customation_puritIII_detailsandfiles.png
  static/Images/APIPortal/customation_puritIII_detailsandfiles_j4.png
  static/Images/APIPortal/jai_customize_apps.png
  static/Images/APIPortal/jai_customize_apps_j4.png
  static/Images/APIPortal/jai_mainmenuall_home.png
  static/Images/APIPortal/jai_mainmenuall_home_j4.png
  static/Images/APIPortal/joomla_install_lang.png
  static/Images/APIPortal/joomla_install_lang_j4.png
  static/Images/APIPortal/role_mapping_expanded.png
  static/Images/APIPortal/role_mapping_expanded_j4.png
  static/Images/APIPortal/tiles-homepage.png
  static/Images/APIPortal/tiles-homepage_j4.png
  static/Images/APIPortal/user_actions_logs_table.png
  static/Images/APIPortal/user_actions_logs_table_j4.png
Labels: size/M, May22_Portal

#2367 RMF-301 Update config files for August 22
  .github/workflows/ciworkflow.yml
  .github/workflows/merge_to_develop.yml
  layouts/partials/page-meta-links.html
  static/admin/config.js
Labels: size/S, August22

#2368 RMF-301 APIM Aug 22 Create release notes pages
  content/en/docs/apim_relnotes/20220830_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20220830_apip_relnotes.md
Labels: size/M, August22

#2371 [RDAPI-27635] Added details for "Monitoring metrics" section in “api_mgmt_monitor” page.
  content/en/docs/apim_administration/apimgr_admin/api_mgmt_monitor.md
Labels: August22

#2372 IAP-5320: Remove CentOS7 references
  content/en/docs/apim_installation/apiportal_install/install_dependencies.md
  content/en/docs/apim_installation/apiportal_install/install_software_prereqs.md
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
Labels: size/S

#2370 IAP-4924: add Known issues section to Elasticsearch page
  content/en/docs/apim_installation/apiportal_install/install_software_elastic.md
Labels: size/S

#2373 Upgrade API Portal - Update prereq section to be more specific about taking a snapshot of the environment
  content/en/docs/apim_installation/apiportal_install/upgrade_automatic.md
Labels: size/XS

#2374 [RDAPI-22959] Update to more accurately represent the API retirement process
  content/en/docs/api_mgmt_overview/api_mgmt_components/apimanager.md
Labels: size/XS

#2377 Introduction to API Manager - changes to improve readability
  content/en/docs/api_mgmt_overview/api_mgmt_components/apimanager.md
Labels: size/S

#2378 Install API Portal - Make step more clear
  content/en/docs/apim_installation/apiportal_install/install_software.md
Labels: size/XS
