Repository Axway/axway-open-docs, pull requests merged in 2022-09, with the labels that each got.

#2422 RMF-314 Update config files for November 22
  .github/workflows/ciworkflow.yml
  .github/workflows/merge_to_develop.yml
  layouts/partials/page-meta-links.html
  static/admin/config.js
Labels: November22

#2423 RMF-314 Create release notes pages for Nov 22
  content/en/docs/apim_relnotes/20221130_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20221130_apip_relnotes.md
Labels: size/M, November22

#2424 [RDAPI-27721] MimeType Body Factory field
  content/en/docs/apim_policydev/apigw_polref/content_additional.md
  content/en/docs/apim_policydev/apigw_polref/content_common.md
  content/en/docs/apim_reference/general_settings.md
Labels: size/S, size/XS, November22

#2428 [RDAPI-27445][RDAPI-28268] Update for 7.7 November 2022 system properties
  content/en/docs/apim_reference/system_props.md
Labels: November22

#2429 [RDAPI-27792] nodetool repair needs the -pr flag
  content/en/docs/apim_installation/apigw_upgrade/upgrade_cassandra.md
  content/en/docs/apimgmt_multi_dc/multi_datacenter_config.md
Labels: size/XS

#2434 Correct links to mysql docs for version 8
  content/en/docs/apim_installation/apigtw_install/metrics_db_install.md
Labels: size/XS, netlify-cms/pending_review

#2433 update troubleshooting needs to be included
  content/en/docs/apim_installation/apigw_upgrade/upgrade_troubleshoot.md
Labels: size/S, netlify-cms/draft

#2436 RDAPI-28348 Fix link to Javadoc
  content/en/docs/apigtw_devguide/unit_test_traffic_monitor.md
  content/en/docs/apim_policydev/apigw_poldev/general_selector.md
  content/en/docs/apim_reference/log_global_settings.md
Labels: size/S
