Repository Axway/axway-open-docs, pull requests merged in 2023-09, with the labels that each got.

#2721 RDAPI-30232 Update release notes fix issues for May23
  content/en/docs/apim_relnotes/20230530_apimgr_relnotes.md
Labels: May23

#2723 RMF-418 Update configuration files for November 23 Update
  .github/workflows/ciworkflow.yml
  .github/workflows/merge_to_develop.yml
Labels: November23

#2720 [RDAPI-30389] - Updated for Cassandra 4.0.11.
  content/en/docs/apim-reference-architectures/container-openshift/_index.md
  content/en/docs/apim_installation/apigtw_install/install_cassandra.md
  content/en/docs/apim_installation/apigw_upgrade/upgrade_cassandra/upgrade_cassandra_v4.md
  content/en/docs/apimgmt_multi_dc/multi_datacenter_config.md
  content/en/docs/cass_admin/admin_cassandra_classic/cassandra_bur.md
Labels: November23

#2725 IAP-4926: update supported PHP version
  content/en/docs/apim_installation/apiportal_install/install_dependencies.md
  content/en/docs/apim_installation/apiportal_install/install_software_prereqs.md
Labels: November23

#2726 [RDAPI-30522] Clarify OAuth message attribute
  content/en/docs/apim_policydev/apigw_oauth/oauth_message_attributes.md
Labels: November23

#2731 Delete API Analytics PDF reports from Known issues section
  content/en/docs/apim_relnotes/20230530_apimgr_relnotes.md
  content/en/docs/apim_relnotes/20230830_apimgr_relnotes.md
Labels: May23, August23

#2732 Delete API Analytics PDF reports from Known issues section
  content/en/docs/apim_relnotes/20231130_apimgr_relnotes.md
Labels: November23

#2734 Aug 23 release notes update for Cassandra incompatibility with Java 11
  content/en/docs/apim_relnotes/20230830_apimgr_relnotes.md
Labels: August23
